### ISSUE TITLE
GAPI oAuth Broken - Returning uncaught TypeError

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#106]
_From [freeman...@gmail.com](https://code.google.com/u/112021665778836726680/) on September 04, 2013 18:30:35_

What steps will reproduce the problem? If possible, provide a live demo of the issue. 1.Go to gaevolution.appspot.com
2. Click Login
3. Follow steps on oAuth Pop-Up
4. Sign-in What is the expected output? What do you see instead? The popup should close and the login button should turn into a new button saying let's go.

Instead I get a JS error saying "Uncaught TypeError: undefined is not a function "

Here is the stack:
ncaught TypeError: undefined is not a function cb=gapi.loaded_0:223
lk cb=gapi.loaded_0:223
(anonymous function) cb=gapi.loaded_0:231
(anonymous function) cb=gapi.loaded_0:226
h cb=gapi.loaded_0:64
c cb=gapi.loaded_0:55 What version of the product are you using? On what operating system? JS API Beta Please provide any additional information below. This was working fine until today as far as I can tell. I've made no code changes and it just stopped working.

You can reach me via email or @spanishgringo

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=106_

**Comment by s00071609** [comment]
wonderfly, how did you fix this issue?

Thanks

**Comment by bsittler** [comment]
@s00071609 wonderfly was not the author of those comments but rather the one who migrated them from the previous issue tracker on the old Google Code site. If you are encountering a similar-looking issue I encourage you to open a new issue for it as this one hasn't had significant updates since 2013.
