### ISSUE TITLE
Multiple user auth popup requires click, reload, click to select account

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#108]
_From [davidjgr...@gmail.com](https://code.google.com/u/106160348960403302854/) on September 23, 2013 12:36:32_

What steps will reproduce the problem? If possible, provide a live demo of the issue. 1. Go to https://www.draw.io whilst logged into at least two Google accounts.
2. Click on the "connect to Drive" button (top right).
3. Click on one of the accounts What is the expected output? What do you see instead? A single click on the required account should select the account. Instead you have to click, wait for reload and click again. What version of the product are you using? On what operating system? The hosted version of the JS client API library is used, this behaviour has been present since at least the start of 2013. The behaviour is the same on all OSes and browsers we've test, Chrome, FF, Safari, IE 9, 10 and 11. Please provide any additional information below. We had this initial discussion - http://stackoverflow.com/questions/13366254/is-it-possible-to-be-able-to-correctly-select-any-available-google-account-to-us - to get to this stage. We're setting immediate to false and authUser to -1 on the gapi.auth.authorize call, that's the only option that allows us to get the multiple account handling to work in any way.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=108_

**Comment by vidyai** [comment]
Sorry that we did not answer this question in a timely fashion. I am closing this for now, but if you still need help with this question, please reopen.
