### ISSUE TITLE
Google Drive Picker not working in PhoneGap app

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#116]
_From [and...@powerednow.com](https://code.google.com/u/101863726969645324394/) on November 25, 2013 07:00:56_
1. We retrieve the authorization code within our phonegap app
2. We can exchange that for an access_token
3. We can show the filepicker popup, navigate through files, but we can't select any files, can't close the popup, and we see these error messages:

[Error] Unable to post message to https://docs.google.com . Recipient has origin file://.

[Error] Error: Incorrect origin value. Please set it to - (window.location.protocol + '//' + window.location.host) of the top-most page (3681498537-picker_modularized_opc.js, line 822)

On some other devices and when testing from desktop (locally, so the url is file://) we get a white empty popup with these same errors. What is the expected output? What do you see instead? the picker should call the callback with the selected files. What version of the product are you using? On what operating system? multiple iPads with PhoneGap 3, but it's also not working on desktop.

The code we use is from: http://phonegap-tips.com/articles/google-api-oauth-with-phonegaps-inappbrowser.html This issue I've found seems to be relevant: http://stackoverflow.com/questions/20006916/bug-google-drive-picker-stopped-loading-today Our Project number is: 792303685670.

Here's the code we use:

var client_id = "XX";
var client_secret = "YY"; 

var authUrl = " https://accounts.google.com/o/oauth2/auth"; var authOptions = {
client_id: client_id,
redirect_uri: "http://localhost
response_type: "code",
scope: " https://www.googleapis.com/auth/drive.file "
};

var url = authUrl + "?" + Ext.Object.toQueryString(authOptions);

var authWindow = window.open(url, '_blank', 'location=no,toolbar=no');

authWindow.addEventListener("loadstart", function(e) {
    parseUrl(e.url);
});

function parseUrl(url) {

```
var queryString = url.split('?')[1] || "";
var queryObject = Ext.Object.fromQueryString(queryString);
var code = queryObject.code;
var error = queryObject.error;

if (code || error) {
    authWindow.close();
}

if (error) {
    alert(error);
    return true;
}

// exchange code for access token

if (code) {

    Ext.Ajax.request({
        url: " https://accounts.google.com/o/oauth2/token ",
        success: function(response) {
            var resObj = Ext.decode(response.responseText);
            var access_token = resObj.access_token;
            var expires_in = resObj.expires_in;
            var refresh_token = resObj.refresh_token;
            var token_type = resObj.token_type; // "Bearer"

            gapi.load('picker', {'callback': function() {
                var picker = new google.picker.PickerBuilder().
                addView(google.picker.ViewId.DOCUMENTS).
                setAppId(client_id).
                setOAuthToken(access_token).
                setCallback(function(){console.log(arguments);}).
                build().
                setVisible(true);
            }});

        },
        failure: function(e) {
        },
        params: {
            code: code,
            client_id: authOptions.client_id,
            client_secret: client_secret,
            redirect_uri: authOptions.redirect_uri,
            grant_type: "authorization_code"
        }
    });

    return true;
}
```

}

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=116_

**Comment by ccapndave** [comment]
On Cordova iOS this gives the error `Refused to display ... in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

**Comment by bsittler** [comment]
Unfortunately PhoneGap/Cordova is not currently supported by this library.

**Comment by qertis** [comment]
+1

**Comment by petervojtek** [comment]
I face this error as well:
`Refused to display ... in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'`

on Android 4.2 when using Ionic 2 framework after calling `gapi.auth.authorize()`.

It's bit funny that code written by Google cannot access backend API written by Google from smartphone OS written by Google :)

**Comment by bmwertman** [comment]
Getting this same error using [angular-google-picker](https://github.com/softmonkeyjapan/angular-google-picker) in my ionic app. Any solution?

**Comment by ccapndave** [comment]
The only solution I found was to open a page on the server as a popup window using https://github.com/apache/cordova-plugin-inappbrowser or something similar.

**Comment by bferreirainfo** [comment]
any solution for this without pop up people?  please i really need this to launch my app XD

**Comment by JuanFerrer** [comment]
Necroing a bit, but I found the same problem using [Electron](https://electronjs.org/):
> Refused to display ... in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by bochunz** [comment]
@JuanFerrer According to https://developers.google.com/api-client-library/javascript/start/start-js#supported-environments. PhoneGap and Electron are both not officially supported environments.
