### ISSUE TITLE
https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.5GL3tg_C6Nc.O/m=card,gapi_iframes/rt=j/sv=1/d=1/ed=1/rs=AItRSTPfsfz-ifAZeiHMk7mKfiGQJuhVFw/cb=gapi.loaded_0

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#117]
_From [jonnywil...@gmail.com](https://code.google.com/u/100534961820119493040/) on December 05, 2013 19:33:30_

What steps will reproduce the problem? If possible, provide a live demo of the issue. 1. 2. 3. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=117_

**Comment by akumarmca** [comment]
Same problem with me.. 

https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.g0SsD3nZybw.O/m=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNy9nhO1CNK4nx_ImBk80FYyCM9Ig/cb=gapi.loaded_0

Status : 404

**Comment by TMSCH** [comment]
@akumarmca how are you loading that URL?

**Comment by bsittler** [comment]
@akumarmca saving a copy of the scripts from https://apis.google.com is not supported and leads to exactly these errors. I think that was a version from four months ago so I'm not surprised a copy of it no longer works.

**Comment by albertotorresfoltyn** [comment]
I don't have a copy of the js and have the same issue... 

Here is my code...

```
  const script = document.createElement("script");
  script.src = "https://apis.google.com/js/platform.js";
  script.onload = () => {
    debugger;
    gapi.load('client:auth2', {
      callback: function() {
        // Handle gapi.client initialization.
        //initGapiClient();
        debugger;
      },
      onerror: function() {
        // Handle loading error.
        alert('gapi.client failed to load!');
      },
      timeout: 5000, // 5 seconds.
      ontimeout: function() {
        // Handle timeout.
        alert('gapi.client could not load in a timely manner!');
      }
    })
```
What can be wrong?

**Comment by TMSCH** [comment]
@albertotorresfoltyn what URL is 404?

**Comment by johannesjo** [comment]
Same issue here.

**Comment by jerdoflerd** [comment]
yo what is this u just got a email saying "is this even legal" so i checked the links and this came up inside its elements

**Comment by FelipeDac** [comment]
How did u guys resolve that?

**Comment by dvanderb** [comment]
> How did u guys resolve that?

What is the current issue?

**Comment by FelipeDac** [comment]
same error message, i'm using Angular 8 with Ionic, i think thats the problem hahaha

**Comment by MarcoCenturion** [comment]
Same error 

Script error.

https://apis.google.com/_/scs/abc-static/_/js/k=gapi.lb.es.9NxwC-PXr0k.O

**Comment by dvanderb** [comment]
> Same error
> 
> Script error.
> 
> https://apis.google.com/_/scs/abc-static/_/js/k=gapi.lb.es.9NxwC-PXr0k.O

As indicated in earlier responses.. this is a link to an old version. Please load GAPI using the script at https://apis.google.com/js/api.js so that an up to date version is always used.

**Comment by mgreen12206** [comment]
why does google make these insanely cumbersome and bloated uris?

**Comment by Kakum7** [comment]
What’s this about again
