### ISSUE TITLE
groupsmigration discovery doc getting a 404

### ISSUE THREAD

**Issue by Faelbac** [google/google-api-javascript-client#1211]
**Summary**

Same thing of issue https://github.com/google/google-api-javascript-client/issues/801, which was fixed, but for Groups Migration API:

When using gapi with a discovery doc for the Google Business Communications API (which is specified in the docs as https://groupsmigration.googleapis.com/$discovery/rest, visible in any web browser ), I get a 404 in the js setup code and cannot use any of the gapi.client.groupsmigration functions. It seems that gapi is rewriting this request to use https://content-groupsmigration.googleapis.com/static/proxy.html, which is returning a 404 to the request, preventing it from adding the client.

**Browser(s)/Version(s)**
Chrome.

**Expected Behavior**

A discovery doc that works as expected is https://businesscommunications.googleapis.com/$discovery/rest, which redirects via gapi to https://content-businesscommunications.googleapis.com/static/proxy.html, which does not have a 404 and works as expected.

**Actual Behavior**
https://content-groupsmigration.googleapis.com/static/proxy.html is returning a 404 to the request

**Steps to Reproduce**
Run this within an async js function in browser script;
`js
await import("https://apis.google.com/js/api.js");
await window.gapi.client.init({ discoveryDocs: ['https://groupsmigration.googleapis.com/$discovery/rest?version=v1'] });
`

Thanks in advance!

**Comment by dvanderb** [comment]
Thanks for the report. We will investigate.

**Comment by dvanderb** [comment]
This has now been fixed.
