### ISSUE TITLE
Broken link for supported api's in README

### ISSUE THREAD

**Issue by carafelix** [google/google-api-javascript-client#1227]
https://github.com/google/google-api-javascript-client/blob/96cf6057f03c5e56179e83869828a06c47ce571b/README.md?plain=1#L12 this links is broken
![imagen](https://github.com/user-attachments/assets/05eb3838-4d3a-487d-a6ae-075106b0c1d7)

**Comment by mnjit20** [comment]
Hello @carafelix,
I just found its working fine for me.

![image](https://github.com/user-attachments/assets/8b95dd09-36f9-4ea8-824d-1708af733671)

Thanks

**Comment by carafelix** [comment]
Now it is
