### ISSUE TITLE
Setup the development of client.js as a repo on GitHub

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#139]
_From [e.pt...@gmail.com](https://code.google.com/u/105380157389113696457/) on April 09, 2014 04:00:02_

Yesterdays outage was caused by some untested code being deployed to production.

This could have been avoided if the code, tests, commits etc. and deployments was accessible to the open.

Please setup/move this project to GitHub, to follow your other good examples at: https://github.com/google The actual client.js file is not even a part of this repo.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=139_

**Comment by grant** [comment]
This project is now on GitHub.
