### ISSUE TITLE
Integration picasa to client api

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#140]
_From [tomas.be...@gmail.com](https://code.google.com/u/101568393026408573945/) on April 10, 2014 01:38:08_

Will you integrate picasa to client api? I mean, will be  possible access to data through gapi.client.picasa or something like this..

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=140_

**Comment by vidyai** [comment]
Sorry that we did not answer this question in a timely fashion. I am closing this since it is obsolete.
