### ISSUE TITLE
gapi.auth.signin callback does not return an error if user denies oauth request

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#144]
_From [Travis.C...@scotts.com](https://code.google.com/u/115797892424733192739/) on May 01, 2014 11:06:11_

What steps will reproduce the problem? If possible, provide a live demo of the issue. 1. Go To: https://google-developers.appspot.com/+/demos/signin_demo_trigger 2. Click the "Click me" button to trigger the sign-in flow with gapi.auth.signIn()
3. Click "Cancel" when asked for permission.
4. Open the Developer Tools of your choice to see the error Message What is the expected output? What do you see instead? As described in:
Step 5 Handling the sign-in in https://developers.google.com/+/web/signin/javascript-flow#step_5_handling_the_sign-in The callback should be called to update the user with the following error values
  "user_signed_out" - User is signed-out  
  "access_denied" - User denied access to your app
  "immediate_failed" - Could not automatically log in the user What version of the product are you using? On what operating system? Google Chrome, Mac OSX 10.8 Please provide any additional information below. I've attached a screen shot of the gapi error message

**Attachment:** [Screen Shot 2014-05-01 at 2.02.54 PM.png](http://code.google.com/p/google-api-javascript-client/issues/detail?id=144)

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=144_

**Comment by alalonde** [comment]
Still an issue with the auth2 client. See #25

**Comment by jessehattabaugh** [comment]
Is it really a "Promise" if it doesn't always resolve?

**Comment by TMSCH** [comment]
Hi @jessehattabaugh, please refer to the issue #25. We are working on a fix. Closing this one in favor of the other issue.
