### ISSUE TITLE
gapi.client.load() failed .. 404 (Not Found) 

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#147]
_From [vegaquem...@gmail.com](https://code.google.com/u/109593224040402681337/) on May 22, 2014 21:24:42_

it seems trying to access an url with double '/_ah/api' paths: https://xxxxx.appspot.com/_ah/api/_ah/api/discovery/v1/apis/..... .

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=147_

**Comment by alpocr** [comment]
I have same problem. I can't load my endpoint api.  I'm getting a 404 error.


<script>
function loadGapi(){
gapi.client.setApiKey('AIzaSyBvg9bSWGUHhAO-TPIww3KuKh_XXXXX');
gapi.client.load('myCustomApi', 'v1', function() {
    gapi.client.myCustomApi.list().execute(function(resp) {
        console.log(resp);
    });
}, 'https://my-backend-project.appspot.com/_ah/api');
}
 </script>
<script src="https://apis.google.com/js/client.js?onload=loadGapi"> </script>

**Comment by alpocr** [comment]
Anyone from Google is watching this repo?  Any update?

**Comment by smaheshbhat** [comment]
Hi,

The following call doesnt end up in this._driveApiLoaded
gapi.client.load('drive', 'v2', this._driveApiLoaded.bind(this)

Can some one please suggest any workaround if I don't want to create a back end project ?

Any pointers would be great.

**Comment by bsittler** [comment]
Is this issue still occurring?

**Comment by CrandellWS** [comment]
+1

**Comment by smaheshbhat** [comment]
Thanks for getting back to this qn. It no more occurs now. This was due to the older version of json.js loaded by my browser. However there is another question I have now for which if I get an answer, would be helpful.
In IE11, even after adding to the list of trusted sites in Google developer console for the specific key, attempt to open file picker ends up with the 401 error. Please note that in Chrome, Firefox, it works fine.

**Comment by PedroDava** [comment]
Hey guys i need somehelp.

  i having this error:
** https://content.googleapis.com/discovery/v1/apis/oath2/v2/rest?fields=rootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods&pp=0**

**Comment by bsittler** [comment]
I think that API name might be spelled wrong, can you check the spelling? I know about an "oauth" API but not "oath".

**Comment by PedroDava** [comment]
@bsittler  it was that thank  you...

**Comment by pupster90** [comment]
I believe I am have the same glitch that is described above. On deployment the api appears in the api explorer, but it is causing a 404 error when trying to be loaded by javascript. It works fine on the local host.

Any solutions yet?

Another person with the same problem:  http://stackoverflow.com/questions/39682799/google-cloud-endpoints-api-gets-404/39692404#39692404
