### ISSUE TITLE
connect with google Problem in iPhone Browser

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#176]
_From [di...@funmango.com](https://code.google.com/u/115971934181845417363/) on December 05, 2014 04:50:59_

Hi,
i am using connect with google (g+ siginin) in my website it's working fine in desktop and android browsers. but 
not wortking in ipad and iphone browsers.i used javascript api for google siginin.
here my Example is https://www.funmango.com/search/test and i also checked google developer example in iphone browser . but not working what you give in google developer website https://google-developers.appspot.com/+/demos/signin_demo_basic

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=176_

**Comment by TMSCH** [comment]
`gapi.auth2` now supports iPhone and iPad. Closing this issue as obsolete.
