### ISSUE TITLE
gapi.auth.authorize with immediate=false fails on Internet Explorer 11

### ISSUE THREAD

**Issue by ovoytovich** [google/google-api-javascript-client#180]
Using Internet Explorer 11, go to " http://royalpvpgod.com/t0.html "

Hit Authorize (immediate=false). It will bring up a popup window that is empty. No authentication happening.

**Comment by TMSCH** [comment]
Hi @ovoytovich, sorry for the very late reply. `gapi.auth` has been deprecated, we recommend migrating to `gapi.auth2` that works under IE11. Doc: https://developers.google.com/identity/sign-in/web/. Closing this issue as the new library supports IE11.
