### ISSUE TITLE
Java long values are parsed as string instead of number

### ISSUE THREAD

**Issue by willlma** [google/google-api-javascript-client#181]
Java objects' `long` attributes are parsed as a `string`, whereas `int` attributes are parsed as `number` in JavaScript. I can't tell whether this is happening during cloud endpoints' serialization process or google-api-javascript-client's parsing process, but it should be fixed.

**Comment by rsolomon** [comment]
We are experiencing this issue as well. I know this has been open for more than a year-- any comment on if we can expect a fix?

**Comment by bsittler** [comment]
This is expected. A Java `long` is not representable in a JavaScript `number` without loss of precision, so the `string` type is used instead in order to avoid data corruption.

**Comment by bsittler** [comment]
(Note that there is a proposal to fix this https://littledan.github.io/int64.html however it has not yet become a standard part of the language.)

**Comment by rsolomon** [comment]
I may just be experiencing a similar bug on a different part of the platform. I'm using GAE endpoints, which will send a long serialized as a String. However, sending a String back to the endpoint results in a `Can not set java.lang.Long field` issue. I would think that if it serializes automatically, it should do the same on submission.

It very well might just be an issue in my code, so I'll dig deeper.

**Comment by bsittler** [comment]
Indeed, that may be a bug on the Endpoints side. I encourage you to report it through the appropriate forum for Endpoints.

**Comment by bsittler** [comment]
Also, JSON (being based on a subset JavaScript types) cannot represent 64-bit integers. I encourage you to switch to a type that is portably representable without data loss (e.g. string)
