### ISSUE TITLE
Google Client Authorize doesn't work on Mobile Chrome IPhone(41.0.2272.58)

### ISSUE THREAD

**Issue by blackrabbit99** [google/google-api-javascript-client#189]
We use gapi.js for Google authorising. It works correct on majority of desktop browsers and on mobile Safari. But it doesn't on Mobile Chrome IPhone(41.0.2272.58).

In the begging we load your gapi.js script

```
require(['https://apis.google.com/js/client.js?onload=gapiIsLoaded'];
```

Then we try authorize using:

```
gapi.auth.authorize(params, handler);
```

Params are

```
var params = {
                client_id: MY_CLIENT_ID,
                scope: MY_SCOPES,
                immediate: false // to open popup
            };
```

Browsers shows popup and I can autorize and continue work. Iphone Safari works correct too.

But Chrome IPhone never calls `handler`` callback.

We also reproduced the same issue on your resource.

https://developers.google.com/drive/v2/reference/files/get

**Comment by yetithefoot** [comment]
Vote for that!

**Comment by rakib32** [comment]
Yes we are facing the same issue. Is there any workaround for this?

**Comment by blackrabbit99** [comment]
Looks like a dead repo =(

**Comment by yetithefoot** [comment]
@wonderfly Please attn this.

**Comment by wonderfly** [comment]
@bsittler Can you take a look?

**Comment by bsittler** [comment]
We are aware of this issue and do not currently have a workaround. If you use your own redirect-based OAuth 2 flow you can store the resulting access token using gapi.auth.setToken({'access_token':'...'}) and use it to make API calls, though.

**Comment by bsittler** [comment]
See also http://stackoverflow.com/questions/14637937/window-opener-not-set-in-ios-chrome

**Comment by blackrabbit99** [comment]
Thanks I was sure that it's chromium issue but i couldn't to reproduce this because same behaviour works in Safari(((. Hope it would be easy to fix. Stackoverflow.com thread was updated.

**Comment by nicmendoza** [comment]
Any updates on this? Has anyone used the linked workaround successfully with the Google API client?

**Comment by TMSCH** [comment]
Hi @nicmendoza @blackrabbit99 @yetithefoot, I apologize that this issue has been opened for so long.

We have just released a new feature that allows to perform the sign-in flow using redirect instead of popup, which should provide a workaround to `window.opener` not set on Chrome iOS. See the doc: https://developers.google.com/identity/sign-in/web/reference#gapiauth2initparams

Let me know if that fixes your issue!
