### ISSUE TITLE
gapi.auth.authorize callback doesn't get called when doing sign-in via Google on node-webkit app

### ISSUE THREAD

**Issue by Kufert** [google/google-api-javascript-client#194]
I have an issue when doing sign-in from node-webkit app. In the node-webkit application, I open a page on my domain with the following code:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8' />
        <link rel="stylesheet" src="style.css" />
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script type="text/javascript">
             var CLIENT_ID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
             var SCOPE = 'https://www.googleapis.com/auth/userinfo.email';               

            function authorization() {
                   gapi.auth.authorize({
                     client_id: CLIENT_ID,
                     immediate: false,
                     scope: SCOPE
                   }, function(authResult) {
                        alert('CALLBACK');
                      }
                   );
                 }
        </script>       
        <script src="https://apis.google.com/js/client:platform.js?onload=authorization"></script>
        <title>Google Sign In</title>
    </head>
    <body></body>
</html>
```

For some reason the callback never fires when running on node-webkit. While trying to debug it I saw something strange. When I run this from node-webkit, this code will open the google sign-in screen. When the node-webkit developer console is open for the google page, the callback fires successfully. 

When I load the same page on chrome, the callback fires and I can see the alert, so I don't think the issue is with the code. Before running this code I programmatically clean the node-webkit cache so each time the user is required to enter his credentials.

**Comment by Kufert** [comment]
Eventually I solved it using server side authentication. If anyone ever manage to solve this issue, please post the solution on stackoverflow too:

http://stackoverflow.com/questions/30438556/gapi-auth-authorize-callback-doesnt-get-called-when-doing-sign-in-via-google-on/31868047#31868047

**Comment by TMSCH** [comment]
Hi @Kufert, node-webkit is not a supported environment so server-side authentication is the way to go!

**Comment by Kufert** [comment]
Oh wow never thought I'll hear back :) thanks for the update!

**Comment by TMSCH** [comment]
You're welcome! Sorry it took so long...
