### ISSUE TITLE
Help with gapi.authorize callback OAuth2.0 token object error messages

### ISSUE THREAD

**Issue by JaKXz** [google/google-api-javascript-client#196]
It would be really nice to know what error messages I can expect to get back from the [`gapi.authorize`](https://developers.google.com/api-client-library/javascript/reference/referencedocs#--------gapiauthauthorizeparams--------callback------) method's [token object](https://developers.google.com/api-client-library/javascript/reference/referencedocs#--------oauth-20-token-object------), and best practices for handling them.

A great place for this documentation would be the test suite, if available!

**Comment by TMSCH** [comment]
Hi @JaKXz, this is a good point. `gapi.auth` is now deprecated so the doc has been removed, however, we should document error messages for `gapi.auth2`.

**Comment by TMSCH** [comment]
Hi @JaKXz, we published in the documentation the errors that methods can raise: https://developers.google.com/identity/sign-in/web/reference.

Closing this issue.

**Comment by JaKXz** [comment]
Thanks!
