### ISSUE TITLE
Google API client fails to load googleapis_proxy feature inside proxy.html with ?jsh value m;/_/scs/apps-static/_/js/k=oz.gapi.en.KJ-h_65Y6II.O/m=__features__/am=QQ/rt=j/d=1/t=zcms/rs=AGLTcCNjocO07LI68Fpz0bNn0c3yotgAsQ - HTTP 404

### ISSUE THREAD

**Issue by dustinsoftware** [google/google-api-javascript-client#204]
This URL works:

https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.KJ-h_65Y6II.O/m=client/rt=j/sv=1/d=1/ed=1/am=QQ/rs=AGLTcCNjocO07LI68Fpz0bNn0c3yotgAsQ/t=zcms/cb=gapi.loaded_0

But this one gives me a 404:

https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.KJ-h_65Y6II.O/m=googleapis_proxy/rt=j/sv=1/d=1/ed=1/am=QQ/rs=AGLTcCNjocO07LI68Fpz0bNn0c3yotgAsQ/t=zcms/cb=gapi.loaded_0

Which is referenced by this page:

https://content.googleapis.com/static/proxy.html?jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.KJ-h_65Y6II.O%2Fm%3D__features__%2Fam%3DQQ%2Frt%3Dj%2Fd%3D1%2Ft%3Dzcms%2Frs%3DAGLTcCNjocO07LI68Fpz0bNn0c3yotgAsQ

Any ideas?

**Comment by minwan** [comment]
May I know which request did you make to trigger that URL? can you still reproduce?

**Comment by minwan** [comment]
After some debugging, it looks you are using an old version of client.js. can you make sure to fetch current client.js from Google server. Using a cached copy of the client is not supported. thanks!

**Comment by dustinsoftware** [comment]
You are correct, we have a local copy of client.js cached on our end. I'll re-open this issue if we continue to have problems. Thanks!
