### ISSUE TITLE
Exception thrown on receiving a message containing a key "f"

### ISSUE THREAD

**Issue by chrisdoble** [google/google-api-javascript-client#205]
Steps to reproduce:
1. Navigate to a page that loads the JavaScript client library
2. Execute the following in the developer console:
   
   ``` js
   window.postMessage('{"f":"fdsafdsafdsa"}', window.location.origin);
   ```
3. :boom: An exception is thrown:
   
   ```
   Uncaught TypeError: Cannot read property 'src' of null
   ```

**Comment by bsittler** [comment]
You should be able to safely ignore that exception.
