### ISSUE TITLE
gapi.client.load() 404 Error - URGENT!

### ISSUE THREAD

**Issue by Jennydmz** [google/google-api-javascript-client#206]
I'm getting a 404 response each time I try to load the gapi client (javascript Library).

function loadGmailApi() {
    gapi.client.load('gmail', 'v1', myfun);
}

Request URL:https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.70k-Pga9TXQ.O/m=googleapis_proxy/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCOWP1o8NgsIgsYWhFlVd2d-ijg0vQ/t=zcms/cb=gapi.loaded_0
Request Method:GET
Status Code:404 OK

It was working fine two days ago.

Is this a bug? or I have to change something in my code?

Anyone with the same problem? I will appreciate your help.

**Comment by DillonGray** [comment]
Same issue here. Was working fine previously and I've made no updates to my own code.

**Comment by dptucunduva** [comment]
Same issue here. Everything was working just fine, no updates in my code. It started failing about 2 weeks ago.

https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.pt_BR.Bia2S4D645M.O/m=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNR0lTTr8UX8IIvbVBj3qgMblx3zA/t=zcms/cb=gapi.loaded_0

**Comment by bsittler** [comment]
Is this still failing? What steps are you using to load the client library?

**Comment by DillonGray** [comment]
If anyone finds there way here, grab the latest JS if you're loading it locally. My issue was caused by some change in their API. I grabbed the latest from https://apis.google.com/js/platform.js

**Comment by dptucunduva** [comment]
Everything seems to be just fine now. At the end, the problem was actually my code - we copied locally gapi JS instead of using the one provided by google servers.

**Comment by bsittler** [comment]
Downloading our JS and serving it locally is not supported and is likely to lead to this sort of breakage.

**Comment by michal-husak** [comment]
@DillonGray why [platform.js](https://apis.google.com/js/platform.js) and not [client.js](https://apis.google.com/js/client.js)?

**Comment by pikitgb** [comment]
@michal-husak and @bsittler suggestions fixed for me.

**Comment by bsittler** [comment]
As in https://github.com/google/google-api-javascript-client/issues/204 using a downloaded/cached copy of the JS client script is not supported and will cause breakage.
