### ISSUE TITLE
When the user successfully authenticates promise callback is never called in IE9/10

### ISSUE THREAD

**Issue by mvolodin** [google/google-api-javascript-client#207]
I'm trying to handle successful sign in callback when Promise returned. Also I have attached all libraries needed for Promise support 'es5-shim', 'promise'.

``` javascript
var auth2 = gapi.auth2.getAuthInstance();
 auth2.signIn({
    scope: 'https://www.google.com/m8/feeds'
  }).then(function (currentUser) {
  // Is never executed
})
```

Is this a bug? Or I'm doing something wrong.

**Comment by TMSCH** [comment]
Hi @mvolodin, sorry for the late reply. Could you try again with the following snippet:

```
var auth2 = gapi.auth2.getAuthInstance();
auth2.signIn({
  scope: 'https://www.google.com/m8/feeds'
}).then(function(currentUser) {
  // Is never executed
}, function(error) {
  console.log(error);
});
```

and report any console logs?

**Comment by TMSCH** [comment]
Closing the issue as no follow up was given. Please reopen with more details if necessary.
