### ISSUE TITLE
404 on gapi.load

### ISSUE THREAD

**Issue by gojko** [google/google-api-javascript-client#212]
Hi,

we started getting 404 errors on gapi.load calls in the last few days. Two scripts that seem to cause problems for a lot of people are drive-share and drive-realtime. Here's an example:

![screen shot 2016-01-04 at 13 26 44](https://cloud.githubusercontent.com/assets/38767/12089855/79c66acc-b2e9-11e5-8ad7-a61ba93d4cf0.png)

The code worked perfectly until a few days ago, and is only affecting some users, so it's likely to be something with a partial deployment on the Google CDN. I'd appreciate quite a lot if someone could look into this.

Just for a reference, this is what's in the page:
```
<script src="https://apis.google.com/js/client.js?onload=initGoogleAPI" async defer></script>
...
window.initGoogleAPI = function () {
	if (!gapi.drive || !gapi.drive.realtime) {
		gapi.load('drive-realtime', window.initGoogleAPI);
                return;
        }
        ....
}
```

**Comment by ianbamforth** [comment]
Also seeing the same effects, with IP addresses including 216.58.210.78.

**Comment by fredrikbonander** [comment]
@gojko Does this work?

```
<script src="https://apis.google.com/js/client.js?onload=initGoogleAPI" async defer></script>
...
window.initGoogleAPI = function () {
    if (!gapi.client.drive || !gapi.clientdrive.realtime) {
        gapi.client.load('drive-realtime', window.initGoogleAPI);
                return;
        }
        ....
}
```

**Comment by gojko** [comment]
@fredrikbonander gapi.client.load requires the second argument to be a version, and as far as I know, it's not possible to load the drive-realtime library via gapi.client.load, only via gapi.load; anyway, this problem cleared up meanwhile
