### ISSUE TITLE
Add API from multiple GAE endpoints with different client ids

### ISSUE THREAD

**Issue by Burtan** [google/google-api-javascript-client#213]
Hi,
is it currently possible to authenticate with multiple client ids for multiple GAE apps? I have tried to chain-authenticate but it seems only one reponse token is saved.
Best,
BurtaN

**Comment by bsittler** [comment]
Why are multiple client IDs involved?

**Comment by Burtan** [comment]
I had GAE modules of different projects.

**Comment by bsittler** [comment]
Can you explain the scenario where this is needed? Please pardon my ignorance, but I don't yet understand what operation (or operations?) require the user to authorize multiple clients in a single step. Are the permissions granted to all the applications identical, or are they distinct? Is the end-user authorizing the access aware of the distinct identities of each client, or not?

**Comment by TMSCH** [comment]
@Burtan we are working on a new feature that would allow several `client_id` in the same app. I'll keep this thread updated.

**Comment by TMSCH** [comment]
@Burtan, the new feature has been released: https://developers.google.com/identity/sign-in/web/reference#advanced. Each call is independent from the other so you can change the `client_id` in each. As @bsittler noted however, we do not recommend to have several `client_id` in the same application.

**Comment by Burtan** [comment]
Thanks for the update!
