### ISSUE TITLE
Param include_granted_scopes not supported by Google SignIn for Websites

### ISSUE THREAD

**Issue by maelcaldas** [google/google-api-javascript-client#214]
When login with [Server-Side flow](https://developers.google.com/identity/sign-in/web/server-side-flow), or ask authorization for additional scopes, with `auth2.grantOfflineAccess`, the result access/refresh token is not getting combined with previous authorized scopes, overriding the previous ones.

Even passing the param to js calls, e.g. `auth2.grantOfflineAccess({'include_granted_scopes' : 'true', ...})`, the param **`include_granted_scopes=true`** is NOT added to the generated URL. 

When I manually append the param `&include_granted_scopes=true` to the generated url on popup window, the incremental combined authorization works, as [described in the protocol](https://developers.google.com/identity/protocols/OAuth2UserAgent#incrementalAuth).

This problem is described at Stackoverflow: 

[http://stackoverflow.com/questions/35023983/incremental-combined-authorisation-with-google-signin-for-server-side-apps](http://stackoverflow.com/questions/35023983/incremental-combined-authorisation-with-google-signin-for-server-side-apps)

Not being able to implement incremental **combined** authorization, makes things hard, since every incremental scope authorization overrides the previous authorized ones.

**Comment by yk1711** [comment]
+1 this is a fundamental parameter that is strangely missing

We opted to drop the client-side permission prompts and go with the server-side redirect flow and PHP SDK which at least has unminified source available to look into.

JS SDK seems to be severely neglected and unsupported and source code is not provided to look at/fork.

**Comment by TMSCH** [comment]
Thanks for raising this issue, and sorry for the late reply. We are investigating.

**Comment by TMSCH** [comment]
@yk1711 @maelcaldas the issue has been fixed, `include_granted_scopes=true` is added to the URL (sorry for the late update, it has been for while).
