### ISSUE TITLE
gapi.auth.authorize does not work on safari

### ISSUE THREAD

**Issue by maelcaldas** [google/google-api-javascript-client#215]
Call to 'gapi.auth.authorize' on Safari Version 9.0.3 (10601.4.4) does NOT open the popup and call the callback.

E.g. In the code below:
`
  	 function handleAuthResult(authToken) {
  	 	alert('It worked!!')
  	 }

	 function initGoogleClientLogin() {
    	  gapi.auth.init(function() {
    	  	gapi.auth.authorize({client_id: 'YOUR_CLIENT_ID', scope: 'email profile'}, handleAuthResult);
    	  });
   	 };

`
Is expected the alert popup appears after the flow complete. It worked on Chrome and Firefox, but not on Safari (Version 9.0.3 - 10601.4.4)

**Comment by bsittler** [comment]
Authorization popups should only work (at least in general) when created in the context of a user input event. See the discussion and examples at https://developers.google.com/api-client-library/javascript/features/authentication#about-scope

**Comment by maelcaldas** [comment]
The problem occurs on safari no matter if the action is fired by a button click or onLoad. The code is just for example purposes...

**Comment by maelcaldas** [comment]
Hi @bsittler , you are right. Actually, what happened was, due to the call outside user input event, Safari blocked popup without any warning. I just allowed it to show popups, and started working normally.

Thanks for clarifying it :-)

I will close it now, as it seems to work as intended.

Cheers

**Comment by bsittler** [comment]
Glad the issue is resolved!

**Comment by Burtan** [comment]
I've made the experience that the login popup is blocked even when it is triggered by user action, when you initialize the popup from a deferred function. It seems that especially Safari does not recognize it to be user triggered then.

**Comment by bsittler** [comment]
Right, "in the context of" is a bit different across browsers -  the only portable definition is "in the synchronous call stack of an event handler for"
