### ISSUE TITLE
files.list() doesn't return a 401 error code when the access token expires

### ISSUE THREAD

**Issue by peveuve** [google/google-api-javascript-client#216]
hi,

I am using the Google Drive Javascript API v2 to access the user drive.
The user was authenticated and gave the necessary OAuth authorizations previously with a server-side call.
I noticed the files.list() call doesn't return a 401 error code when the access token expires, but no code and an empty list. It should return a 401 code so I can refresh the token with an immediate authorize call.

My simplified code is the following:

```
function authorize(clientId, immediate, callback) {
    gapi.auth.authorize({
    'client_id': clientId,
    'scope': ["https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive.readonly"],
    'immediate': immediate
    },
    function(authResult) {
        if (authResult && !authResult.error) {
            oauthToken = authResult.access_token;
            if (callback && typeof(callback) === "function") {
                callback();
            }
        } else {
            // triggers non immediate authorize()
        }
    });
}

[...]

authorize(clientId, true, function() {
    gapi.client.load('drive', 'v2', listFile);
}

[...]

function listFiles() {
    var listRequest = gapi.client.drive.files.list({q: queryString});
    listRequest.execute(function(response) {
        if (response.code == 401) {
            // never happens
        } else {
            // no code and no items in the list is returned if token expired
        }
    }
}

```

I call https://accounts.google.com/o/oauth2/revoke?token=xxxxx to invalid the access token.

**Comment by bsittler** [comment]
I encourage you to switch to the modern Promise style (.then with two arguments, one for success and one for failure, rather than .execute - careful, it changes the response object shape!) and see whether the issue persists.

**Comment by peveuve** [comment]
OK, good to know. This would deserve to be documented.

**Comment by bsittler** [comment]
https://developers.google.com/api-client-library/javascript/features/promises#using-promises

**Comment by peveuve** [comment]
Ah great, thanks for the url! 
Can we expect the callback  to be fixed, or should I close the issue?

**Comment by bsittler** [comment]
I suspect that there is a real problem here which needs to be addressed.

What does the overall "response" parameter look like (e.g. what gets logged by console.log(JSON.stringify(response)) ) in the error case when using the .execute method? Also, what does the second ("rawResponse") parameter to your callback look like in the error case when using the .execute method?

Separately, once you switch to the Promises interface/.then, does the Promise reject when the token is invalid? If so, what does the parameter to the rejection look like?

**Comment by peveuve** [comment]
Sorry to answer lately, I worked around the problem with another design, so I can't answer this question.
