### ISSUE TITLE
Unicode character mangling

### ISSUE THREAD

**Issue by cowsrule** [google/google-api-javascript-client#221]
I opened [an issue against the Realtime API](https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?can=1&start=0&num=100&q=API%3Drealtime&colspec=Stars%20Opened%20ID%20Type%20Status%20Summary%20API%20Owner&groupby=&sort=&id=4063) where ekoleda recommended I follow up here instead as the issue is broader than just with them.

In summary data that flows through the JavaScript library has the potential to have unicode mangling occur. I also posted a [second issue](http://stackoverflow.com/questions/36302075/realtime-api-decode-error-with-utf-8-encoding-in-safari) about issues decoding/encoding UTF-8 characters in Safari while using the Realtime API. It is possible that this is the same or a similar encoding issue.

**Comment by grant** [comment]
Sorry to report, this API has since been shut down.
https://developers.google.com/realtime/deprecation
