### ISSUE TITLE
gapi.auth.authorize doesn't work in windows mobile IE  browsers

### ISSUE THREAD

**Issue by karthikeyan-vk** [google/google-api-javascript-client#223]
on Executing below code for google sign in in my website,   

```
doLoginFromGoogle : function(cbk) 
    {
        var _this = this; this.skAuthCbk = cbk;
        var handleAuthResult_cbk = function(authResult)
        {
            _this.handleAuthResult(authResult, cbk);
        };
        gapi.auth.authorize({client_id: _this.clientId, scope: _this.scopes, immediate: false}, handleAuthResult_cbk);
        return false;
    },
```

Google account's login screen is shownafter signing in with valid credentials, it returns to my webpage but login is not happening. It remains same as before clicking the login button? Need Help...! It works fine in all other browsers, also in IE in desktop only in IE mobile it is not working.

**Comment by bsittler** [comment]
Mobile IE is not currently a supported browser for this project. I don't currently have access to a device that runs it nor any way to automate testing for it.

That said, does login finish if you then reload the page? Are you doing an immediate: true auth check prior to the one displayed in the pop-up window?

Also, does the pop-up window have an "opener" property which is a working reference to the app page and allows traversal of the app page's frame hierarchy and same-origin script execution between the pop-up and a same-origin-with-the-popup IFRAME? That capability is currently required for the pop-up authorization flow to succeed. See https://github.com/google/google-api-javascript-client/issues/222 for a slightly more detailed description of the issues in the context of a different unsupported browser.

**Comment by karthikeyan-vk** [comment]
Answers to your questions:
No login is not finished on reloading the page.
Yes we are doing an immediate true auth check.

Actually its a mobile website to which we have integrated the google sign in process. 

Also in that browser we have already have a signed in google account user. So on clicking the signup with google button, URL is getting redirected as expected to google api URL(a blank window with google login URL appears, keeps on loading on refreshing it returns to our site and nothing happens). I think we don't receive any response back to our call back function from google api.

**Comment by bsittler** [comment]
Any idea whether pop-up windows have a working window.opener reference to the page that opened them? Also, are third-party cookies blocked? That will likely prevent sign-in from working.

**Comment by karthikeyan-vk** [comment]
No third party cookies are not blocked and pop-windows have a working.opener reference

**Comment by TMSCH** [comment]
@karthikeyan-vk `gapi.auth.authorize` has been deprecated, please migrate to `gapi.auth2`. Doc: https://developers.google.com/identity/sign-in/web/sign-in. However, we do not officially support windows mobile so there's no guarantee it will work.

**Comment by TMSCH** [comment]
Hi @karthikeyan-vk , have you been able to migrate to GSI v2? Are you still experiencing the issue there?

**Comment by karthikeyan-vk** [comment]
Hi,

Yes was able to migrate to GSI v2 without any issues. And we discontinued our support for windows IE browsers, So haven't tested out there. Thanks!

**Comment by TMSCH** [comment]
Thanks @karthikeyan-vk for the update! Glad the migration went well.
