### ISSUE TITLE
Google api taking default account token while we have multiple user accounts 

### ISSUE THREAD

**Issue by pramock4bs** [google/google-api-javascript-client#225]
I'm using php google client api for login. And Im using js api on client side to call drive api.
The issue is, if we have multiple accounts logged in google. And you used different google account other than default account , when we call drive api from js google sending default google account token. We can't force user to select the again the accounts, because he already selected that fr login purpose.

Steps to reproduce,
1. Add multiple accounts to google.
2. Using php client api  login to system  and select an account which is not default
3. Then from js side call any api like drive , plus or etc 
4. That time google sending the default account token, on that page you can see welcome back message to default user also

**Comment by TMSCH** [comment]
Hi @pramock4bs I don't think I understand fully. Are you using `gapi.auth2` to authenticate the user?

**Comment by TMSCH** [comment]
Closing this issue as inactive and the bug observed is not defined with enough details. Please reopen and provide details so we can address the issue.
