### ISSUE TITLE
Google + sign up api  not Providing gender 

### ISSUE THREAD

**Issue by ravindrasapkal** [google/google-api-javascript-client#227]
In my web application, I am using google+ sign up API. In that, I have problem for fetching the gender of the user (i.e. gmail user). In some of the user it shows nothing.
Plz guide me what I have to do for getting the gender of user.

Google+ sigup code as below:

function validateToken(token) {
        $.ajax(
            {
                url: VALIDURL + token,
                data: null,
                success: function (responseText) {
                    getUserInfo();
                },
                dataType: "jsonp"
            });
    }

function getUserInfo() {

```
    $.ajax({
        url: 'https://www.googleapis.com/oauth2/v1/userinfo?access_token=' + acToken,
        data: null,
        success: function (resp) {
            var Fname = resp.given_name;
            var Lname = resp.family_name;
            var Gender = resp.gender;
        },
        dataType: "jsonp"
    });
}
```

**Comment by TMSCH** [comment]
Hi @ravindrasapkal, this is working as intended, some users do not provide their gender.
