### ISSUE TITLE
I LOVE YOU GOOGLE

### ISSUE THREAD

**Issue by gasplumber** [google/google-api-javascript-client#231]
THE BEST THING EVER google-api-javascript-client.  

I'V JUST LEARNT THE NEXT LEVEL INTELLIGENCE.  THANK YOU FOR THIS BLESSING, 

GOOGLE YOU ARE THE BEST AND YOU DON'T PAY TAX.  

" YOU MAKE ME SMARTER" I WOULD BE NOTHING WITH OUT YOUR BLESSING!!!!

**Comment by bsittler** [comment]
This does not appear to be an issue report relevant to this client library

**Comment by gasplumber** [comment]
Thank you Bsittler but its bigger then you and me together.  its all mirros and shadows.
