### ISSUE TITLE
gapi.auth2 needs supported manual token update

### ISSUE THREAD

**Issue by rhashimoto** [google/google-api-javascript-client#234]
In normal operation, the client library updates access tokens 5 minutes before they expire, but this doesn't work properly when the computer sleeps. On most platforms, apparently, `setTimeout()` does not recognize time elapsed while the computer sleeps, which is likely to delay token update past the expiration.

With the older but now deprecated `gapi.auth` API, we could pass `immediate: true` to `authorize()` if we detected that the token had expired to update the token bypassing the UI. There does not appear to be a supported way to do this with `gapi.auth2`.

It does, however, appear there is an [undocumented solution in `GoogleUser.reloadAuthResponse()`](http://stackoverflow.com/a/37896285/1462337). Is it possible to document this method so it becomes part of the public and supported API? Or even better, perhaps the API could check for token expiration before any request and update if necessary.

**Comment by TMSCH** [comment]
Hi @rhashimoto, this method is now documented: https://developers.google.com/identity/sign-in/web/reference#googleuserreloadauthresponse

**Comment by TMSCH** [comment]
Closing this issue as this method is now documented. `gapi.auth2` also handles refreshing the token automatically every hour.

**Comment by pravincar** [comment]
@TMSCH . Does this hourly autorefresh allow for a callback to be attached? I store the id_token as a cookie on my domain and verify the validity with each request at my API. So I need to update this cookie if auth2 refreshes the token.
Is there a better way of doing this?

**Comment by TMSCH** [comment]
Hi @pravincar, you can listen to the currentUser changes: [doc](https://developers.google.com/identity/sign-in/web/reference#googleauthcurrentuserlistenlistener). It will be triggered every time the tokens are refreshed.
