### ISSUE TITLE
Google sign-in doesn't work on Safari (private window)

### ISSUE THREAD

**Issue by raymondnam** [google/google-api-javascript-client#235]
I was trying to use `gapi.auth2.getAuthInstance().signIn()` on Safari (private window) but it looks like it is relying on localStorage and throws this exception:

```
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
```

I get the same error when I try to login using the buttons on this page:
https://developers.google.com/identity/sign-in/web/build-button

**Comment by egid** [comment]
I'm able to reproduce this issue as well, with the same `QuotaExceededError`.

**Comment by jdelaney44** [comment]
Me too. This error below is from the console log for an iPhone 5 on IOS 10.0.2 (Verizon). I'm getting the same on and iPhone 6 on 10.0.2 (T-Mobile). In regular mode the iPhone 5 works but the 6 just keeps reloading the page. 

![dom22](https://cloud.githubusercontent.com/assets/6717050/19201422/9fcc6096-8c82-11e6-8e41-f96c5ccdf47c.jpg)

So if we should be going to Firebase for auth, please advise.

**Comment by spacenick** [comment]
@egid Hi, did you get around that issue?

**Comment by TMSCH** [comment]
Hi @spacenick,
This issue has been fixed recently (on Google Sign-In v2), it should now let the user sign in - with some limitations due to the Private mode. Have you tried again?

**Comment by spacenick** [comment]
Well I'm able to get the google popup, but then I don't get any response back in my callback

**Comment by TMSCH** [comment]
Are you still seeing the "Quota Exceeded" issue? Are you using `gapi.auth2`? Could you show me a code snippet that reproduces the issue? I was able to successfully sign in myself in Safari Private Mode.

**Comment by TMSCH** [comment]
@spacenick Have you been able to make it work on Safari Private mode?

**Comment by TMSCH** [comment]
Closing this issue as the issue has been fixed and the thread has been inactive for a couple months.

**Comment by aaronbuchanan** [comment]
How was the issue "fixed"?

**Comment by TMSCH** [comment]
@aaronbuchanan by using different cross-window cross-origin communication mechanism.
