### ISSUE TITLE
How to call gapi.auth2.init with different options?

### ISSUE THREAD

**Issue by vhmh2005** [google/google-api-javascript-client#242]
Whenever I called gapi.auth2.init with different client ID, there was an exception thrown: `gapi.auth2 has been initialized with different options.`

Is there any way to deinit / reset gapi.auth2 config so that I can call gapi.auth2.init again without reloading the page?

**Comment by TMSCH** [comment]
This is working as intended, there is no way to reset gapi.auth2 as it has not been designed to support such use case. If you want to validate `client_id`, you should use a different method. Closing this issue.
