### ISSUE TITLE
How to catch iframe exception?

### ISSUE THREAD

**Issue by vhmh2005** [google/google-api-javascript-client#243]
![image](https://cloud.githubusercontent.com/assets/877578/18872969/585b83a6-84e7-11e6-9f21-647226915b6c.png)

If I use the wrong client ID, sometimes I got the issue in the above picture. However, I couldn't catch that in order to show a custom error message to users. 

How can I catch that exception?

**Comment by TMSCH** [comment]
@vhmh2005 at what point is the error happening? On initialization or calling `signIn`?

We have added a onError callback to the `then` method that should help you: https://developers.google.com/identity/sign-in/web/reference#googleauththenoninit-onerror. An invalid `client_id` would be caught there.

**Comment by TMSCH** [comment]
Closing the issue. Please reopen if the solution mentioned above does not solve your problem.
