### ISSUE TITLE
gapi.auth2.init does not work with hosts have have underscores (_) in them

### ISSUE THREAD

**Issue by mtpettyp** [google/google-api-javascript-client#244]
The prettified code from apis.google.com:
`var tY = function(a) {
        if (!a)
            throw new uO("No cookiePolicy");
        var c = window.location.hostname;
        "single_host_origin" == a && (a = window.location.protocol + "//" + c);
        if ("none" == a)
            return null ;
        var f = /^(https?:\/\/)([0-9.\-A-Za-z]+)(?::(\d+))?$/.exec(a);
        if (!f)
            throw new uO("Invalid cookiePolicy");
        a = f[2];
        var g = f[1]
          , f = {};
        f.dotValue = a.split(".").length;
        f.isSecure = -1 != g.indexOf("https");
        f.domain = a;
        a = "." + a;
        if (c.lastIndexOf(a) !== c.length - a.length)
            throw new uO("Invalid cookiePolicy domain");
        return f
    }`

The line 'var f = /^(https?:\/\/)([0-9.\-A-Za-z]+)(?::(\d+))?$/.exec(a);' does not accept underscores in the hostname.

**Comment by bochunz** [comment]
I did a brief search and found out underscores are not allowed in host name.

http://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

**Comment by mtpettyp** [comment]
Let me clarify - this is a domain name. Chrome/IE/Safari are all happy to load this domain, so I'm not sure exactly what the harm is in adding one character to your regex.

**Comment by bochunz** [comment]
Did you get an error saying "Invalid cookiePolicy" or "Invalid cookiePolicy domain" ?

**Comment by mtpettyp** [comment]
"Invalid cookiePolicy"

**Comment by bochunz** [comment]
I'm working on a fix. Thanks for filing an issue with us.

**Comment by bochunz** [comment]
I think this is fixed. Please have a try (don't forget to clear browser cache)

**Comment by mtpettyp** [comment]
Looks good. Thanks @bochunz!
