### ISSUE TITLE
API breaks when using apple-mobile-web-app-view-enabled

### ISSUE THREAD

**Issue by geoffdavis92** [google/google-api-javascript-client#245]
[Reference this issue](https://github.com/GoogleWebComponents/google-signin/issues/142#issuecomment-208470826).

When my app is saved to the home screen on an iOS device, the Mobile Web App view that is used to display saved apps does not allow for cross-referencing scripts/redirects.

It appears that the gAPI client is setting then trying to access `sessionStorage`, which is not supported in the headless Safari browser for Mobile Web App views.

**Comment by TMSCH** [comment]
@geoffdavis92 we have made some updates in gapi.auth2 recently that may have fixed your problem. Could you try again?

**Comment by TMSCH** [comment]
@geoffdavis92 please try again to make sure our fix addressed your issue. Thanks!

**Comment by TMSCH** [comment]
Closing the issue, please follow up with more details if you are still experiencing the issue.
