### ISSUE TITLE
authSample.html throws SecurityError

### ISSUE THREAD

**Issue by carlospalol** [google/google-api-javascript-client#246]
**1949109082-idpiframe.js:6 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.**
- OS X 10.11.6
- Chrome 53.0.2785.143 (64-bit)
  - Allow local data to be set
  - Block third-party cookies and site data
- Serving on http://localhost:5000/authSample.html
- apiKey and clientId set OK

Seems related to googlesamples/google-services#190

**Comment by santihbc** [comment]
Seeing the same problem using both authentication with the idToken as well as authorization with the authorization code:

```
gapi.auth2.getAuthInstance()
    .grantOfflineAccess({ redirect_uri: "postmessage" })
    .then(({ code }) => code)
```

```
gapi.auth2.getAuthInstance()
    .signIn({ prompt: "select_account" })
    .then((googleUser) => {
        const idToken = googleUser.getAuthResponse().id_token;
        if (!idToken) {
	    throw new Error("Authentication failed.");
	}
	return idToken;
    });
```
The callback (`then`) is never fired. When implementing this with sign in listeners, the same problem happens.

The error I see in the console is:
````
1949109082-idpiframe.js:6 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.(…)
```

**Comment by bochunz** [comment]
santihbc@ Could you mention what browser version are you using when you see this problem?

I'm able to get idToken by 
`gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse().id_token`

**Comment by bsittler** [comment]
gapi.auth2 requires third-party cookies to be allowed

**Comment by TMSCH** [comment]
Duplicate of #260. Closing this one.
