### ISSUE TITLE
Breaking changes to how the GET url is generated

### ISSUE THREAD

**Issue by delian7** [google/google-api-javascript-client#252]
We are relying using Google javascript client APIs for sheets and oauth. Over the weekend I noticed that the function: 

`(a = h.getElementsByTagName(U)[0]) ? a.parentNode.insertBefore(b, a) : (h.head || h.body || h.documentElement).appendChild(b)`

yielded a 404 error.

Our company policy is to save js libraries and call them from our internal server rather than pointing out to an external library to prevent breaking changes.

Thus, Rather than loading the library from `<script src="https://apis.google.com/js/api.js"></script>` we'd rather load and call it from our internal server. Ironically we introduced an outage.

**Comment by bochunz** [comment]
We currently don't support downloading the library and serve statically. The library has dynamic modules that will only be loaded if your logic needs it. So I'm not surprised there's an error if you save the library statically.

**Comment by delian7** [comment]
@bochunz I understand. Thanks for your fast reply.
