### ISSUE TITLE
 Users.messages.attachments: get return wrong name and no id

### ISSUE THREAD

**Issue by OriAmir** [google/google-api-javascript-client#255]
Hey ,I create some chrome extension and I need to get all the attachments from gmail .
In my background page I success to create request to get attachment with 
https://developers.google.com/gmail/api/v1/reference/users/messages/attachments/get

I have 2 problems with this:
1. When I have just on attachment so it's OK and I get file name and type OK , but when I have more then one I get always the same name of attachment and type... I don't know any idea way  I see exactly same issue in [stackoverflow](http://stackoverflow.com/questions/32052207/gmail-rest-api-users-messages-attachments-get-not-returning-filename) but without solution
 
  2. Second problem is that the response not return attachment_ID as excepted and write in the    documentation , if it was return I could solve it with the ID.

Hope that someone could help me please .....

Tnx

**Comment by bochunz** [comment]
I think this question should be for the Gmail API. 

Looking roughly at the Gmail API I guess an attachment is a separate message from the email message (i.e. atachment does not belong to an email message, but may be a sibling message to the email message). https://developers.google.com/gmail/api/v1/reference/users/messages#resource

(I may be totally wrong here as I don't understand much about Gmail. You can get more help on Gmail API here: https://developers.google.com/gmail/api/support)

**Comment by OriAmir** [comment]
But already ask this question in stackoverflow.. so where did I need to get help about it ?

**Comment by OriAmir** [comment]
@bochunz  ... I dont find solution ...where could I search for something?

**Comment by bochunz** [comment]
Personally I would suggest to read Gmail API's doc and try more. I don't think they have such an obvious flaw in their API.
