### ISSUE TITLE
typescript client

### ISSUE THREAD

**Issue by robert-king** [google/google-api-javascript-client#256]
an api that has models.ts for strongly typed models is extremely useful for guarding the frontend against backend api changes using compiler checks.

Wouldn't be much work, first iteration you could give the model properties "any" type, just like the current javascript, no need to worry about if something is a string or integer etc, but at least then refactoring person.email_address to person.email, or adding / removing a property from person model, would be checked by compiler, and any createPerson() or savePerson() method would fail by the compiler, making it simple to react to backend changes.

**Comment by TMSCH** [comment]
Hi @robert-king what is your question about? Is it about gapi.client or gapi.auth2?

**Comment by robert-king** [comment]
hmmm try google generating typescript models from api for strongly typed client.
something like this [typewriter](https://kamranicus.com/posts/2016-02-02-typewriter )

**Comment by TMSCH** [comment]
@robert-king thanks for the follow up. I don't understand how this applies to `gapi.client` or `gapi.auth2`. Could you be more specific? Is it .d.ts files for `gapi.client` that you are looking for?

**Comment by TMSCH** [comment]
Closing this issue as inactive thread. Please reopen with more details if the issue remains.
