### ISSUE TITLE
gapi fails if we enter a wrond id and then try with a correct id

### ISSUE THREAD

**Issue by miteshpant** [google/google-api-javascript-client#257]
I have an application where user is required to enter the client id. If the user enters a wrong client id then it throws 401, this is expected. 
But now unless user refreshes the page, he cannot proceed even with a correct client id. It give externalvisibility erorr

 gapi.load('auth2', function() { //load in the auth2 api's, without it gapi.auth2 will be undefined
                gapi.auth2.init({
                    client_id: id
                });
                var GoogleAuth = gapi.auth2.getAuthInstance(); //get's a GoogleAuth instance with your client-id, needs to be called after gapi.auth2.init

             //   console.log(GoogleAuth.signIn());

                GoogleAuth.signIn().then(function(response) { //request to sign in
                    console.log(response);
                    do something
                });
              //  $scope.validateGoogleUser = $scope.validateGoogleUser;

            });

**Comment by bochunz** [comment]
In our current implementation, gapi.auth2 can only be initialized with one client_id.

Personally, I think sending the client_id to your server and verify it with Google OAuth would solve your problem.

**Comment by TMSCH** [comment]
@miteshpant gapi.auth2 is not meant to be used like that. You should follow @bochunz advice if you want to verify the clientId. Closing this issue.
