### ISSUE TITLE
Failed to laod resource: the server responded withe a sttaus of 404 (https://apis.google.com/)

### ISSUE THREAD

**Issue by amelielefloch** [google/google-api-javascript-client#262]
Hi,
We have an issue in our application since 2 days. The authentification fail. We haven't made corrections or evolutions in our application. So we though it was the google api wich evolved.

**Here is the url which fail.**
https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.fr.tqX5SofV1Q8.O/m=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCPnst4kmCYtomOTqsi-iYDscj8J4g/cb=gapi.loaded_0

I have tried to resolve the issue by downloading the api client on https://github.com/google/google-api-javascript-client. But, it didn't succeed. Do you have any explications ?

Thanks
Amelie

**Comment by bochunz** [comment]
Did you download the script and serve it statically? We only support loading the library dynamically.

**Comment by bsittler** [comment]
I believe that URL is from a very old release (several months old, at least.) How are you loading the client library?

**Comment by ccdunder** [comment]
Sorry that we did not answer this question in a timely fashion. I am closing this for now, but if you still need help with this question, please reopen.
