### ISSUE TITLE
How to Load Google API Javascript Library on Server

### ISSUE THREAD

**Issue by rlcauvin** [google/google-api-javascript-client#264]
I'm trying to access the Google Sheets API from an hMailServer script. The script is Javascript and executes on a server, not in a browser. If you're unfamiliar with hMailServer, consider a script periodically running on a server as a chron job.

Google's documentation gives plenty of information on how to load the Google API Javascript client from HTML, but I haven't found any that describes how to do it from Javascript that runs on the server side and not in a browser context.

How do you load the Google API Javascript library in a script running on a server?

Also, what are the differences among:

```
https://apis.google.com/js/api.js
https://apis.google.com/js/client.js
https://apis.google.com/js/client:platform.js
```

**Comment by bochunz** [comment]
As shown in our [documentation for supported environments](https://developers.google.com/api-client-library/javascript/start/start-js#supported-environments), the library only work in HTML pages. It uses HTML functionalities such as iframe, and browser APIs such as XMLHttpRequest. 

`https://apis.google.com/js/api.js` loads the gapi loader. You can then use the loader to load other modules, such as load the client module with `gapi.load('client', callback)`.

`https://apis.google.com/js/client.js` loads the gapi loader and then asynchronously loads the `client` module.

Similarly, `https://apis.google.com/js/client:platform.js` loads the gapi loader and then asynchronously loads the `client` module and the `platform` module.

**Comment by bsittler** [comment]
Closing this as the environment is not a supported one.

**Comment by rlcauvin** [comment]
Thanks for replying, @bochunz. I'll look into using HTTP requests from the Javascript server side to access the Google Sheets API.
