### ISSUE TITLE
auth2 instance as thenable may cause issues in Promise-based environments

### ISSUE THREAD

**Issue by jPeterek** [google/google-api-javascript-client#268]
Could anybody explain me reasons why a `then` method is attached to auth2 instance object, specially when it passes itself as argument into the callback function, as imho it may cause an **infinite `then` recursion trap** when connected to Promise constructs?

Let's take an example when I might want for some reasons achieve a true Promise behavior:
```javascript
(new Promise((resolve, reject) => {
    resolve(
        gapi.auth2.init({...})
    );
    // same as gapi.auth2init({...}).then(authInstance => resolve(authInstance ));
})).then(...);
```
**KABOOM**, wonders can happen...

Sure, there is easy workaround by wrapping the content passed to resolve method into some other object, but even though I'm not sure if it is a lucky call to make the instance to be thenable.

P.S. To simulate what can happen, try this in the browser (or rather not):
```javascript
let o = {
    then(cb) { cb(o); }
};
Promise.resolve(o).then(i => console.log('no way to get here', i));

**Comment by bochunz** [comment]
The return value of gapi.auth2.init is not a ES6 Promise, but a [goog.Thennable](https://google.github.io/closure-library/api/goog.Thenable.html).

**Comment by jPeterek** [comment]
Then maybe something similar to example below could at least prevent issues that might appear.
```javascript
let stack = 0;
let o = {
    then(cb) {
        if (stack++) {
            stack = 0;
            throw new Error("Prevented recursive call");
        }
        cb(o);
    }
};
Promise.resolve(o).then(i => console.log('never gets here'));
```

**Comment by renarsvilnis** [comment]
Today spent half a day wondering why my application was getting froze on `getAuthInstance`, till debugged that `GoogleAuth` is a promise (using [`is-promise`](https://github.com/then/is-promise)). Thus endless promise loop happens and hangs the browser.

```javascript
const googleAuth = gapi.auth2.init({
  client_id: '...'
});

function getAuthInstance () {
  return googleAuth.then(() => { googleAuth; });
}

function signIn () {
  return getInstance()
    .then((googleAuth) => googleAuth.signIn())
    .then(onSignIn);
},
```

I find this polymorphic API design choice kinda frustrating. Presuming that API change is harder can you document the behavior, so others don't fall on the same trap as me and @jPeterek.


For anyone looking for a "solution". I wrapped `goolgeAuth` in a object in `getAuthInstance` and desctructed the object in `signIn`

```javascript
function getAuthInstance () {
  return googleAuth.then(() => ({googleAuth}));
}

function signIn () {
  return getInstance()
    .then(({googleAuth}) => googleAuth.signIn())
    .then(onSignIn);
},
```

**Comment by TMSCH** [comment]
Hi @jPeterek and @renarsvilnis,
This is indeed confusing, we'll look into documenting this method better to prevent this issue.

@renarsvilnis, in the code example you provide, you should not call the `signIn` method after a promise resolution. Some browsers will prevent the popup from being opened if it is not synchronously opened after a user interaction.

You could use the `gapi.auth2.getAuthInstance()` method to get the `GoogleAuth` instance synchronously.

**Comment by renarsvilnis** [comment]
@TMSCH Thanks for the tip, will try to rewrite so that I allow clicks only once `GoogleAuth` initiates.

**Comment by TMSCH** [comment]
@renarsvilnis I am not able to provide a list of browsers that would fail, it is not a very consistent issue (it can change from version to version). Hence it is safer to not open a popup asynchronously.

**Comment by TMSCH** [comment]
@jPeterek @renarsvilnis, we have updated the documentation to mention this issue: https://developers.google.com/identity/sign-in/web/reference#googleauththenoninit

**Comment by jPeterek** [comment]
@TMSCH Thank you!

**Comment by TMSCH** [comment]
@jPeterek would you mind closing the bug if you think the documentation is enough? We are unlikely to change this behavior as this would break the current API.

**Comment by philBrown** [comment]
Where has the documentation note gone? The link above no longer navigates to a named anchor :(

**Comment by TMSCH** [comment]
Here it is: https://developers.google.com/identity/sign-in/web/reference#googleauththenoninit-onerror. We recently updated the doc.

**Comment by philBrown** [comment]
That's not the only thing you've updated.

What does the `then` method resolve with now if there is no `onInit` passed?

**Comment by TMSCH** [comment]
What do you mean? If there's no `onInit` passed, it just returns a `Promise` that resolves with `undefined`.

**Comment by philBrown** [comment]
Thanks @TMSCH, that's pretty much what I was after.

Having the `GoogleAuth` object appear promise-like really makes it difficult to have some promise-based code resolve with it. It would be really nice if you could move the promise part into something like a `$promise` property like AngularJS does with its `ngResource` instances but anyway, there are workarounds as mentioned earlier in this thread.

**Comment by TMSCH** [comment]
@philBrown I agree with you, unfortunately this decision has been made long ago and now developers rely on it. Changing this would break production apps, so we are stuck with it... We're investigating solutions to avoid the infinite loop though, to address part of the issue.
