### ISSUE TITLE
Auth Without Javascript Client

### ISSUE THREAD

**Issue by Jeckstart** [google/google-api-javascript-client#269]
Hi
I want to get refresh token and since it isn't possible to do with Javascript Client Library, how can I do auth without it?
Even manually doing it is fine, I only need it once anyway

**Comment by TMSCH** [comment]
You could still use the JS client and request an offline code, refer to the documentation here: https://developers.google.com/identity/sign-in/web/server-side-flow. Would that work?

**Comment by Jeckstart** [comment]
Well it requires server-side code aswell, I needed to do it client-side only

**Comment by TMSCH** [comment]
By design, it is not possible to get a refresh token without any server side code.

Could you explain a bit more your use case? Why isn't Google Sign-In JS client library good for it? It handles refreshing token automatically.

**Comment by PDSBGreg** [comment]
Is the JS client library refreshing the token automatically a new feature? When I implement gapi.auth2 last year the auth token invalidated itself every hour and never refreshed.

**Comment by TMSCH** [comment]
This is not a new feature. How do you get the token? Once a user is signed in, `gapi.auth2` automatically refreshes the token. You should be able to get a valid one at all time, by calling [`GoogleUser.getAuthResponse(true)`](https://developers.google.com/identity/sign-in/web/reference#googleusergetauthresponseincludeauthorizationdata). Have you tried recently?

**Comment by PDSBGreg** [comment]
Nope. Maybe I just didn't see that in the docs when I started writing the app last year.

I worked around it by getting a refresh token for the server and then having my server get a new auth token at ~50 minute intervals. It works well...but I'll look into changing that to use the method you mentioned above. Thanks.

**Comment by TMSCH** [comment]
@Jeckstart could you expand a bit more on your use case?

**Comment by TMSCH** [comment]
@Jeckstart please reopen if you still need guidance on this issue. Closing as the thread is inactive.
