### ISSUE TITLE
Sudden gapi.auth2.init invalid scope error

### ISSUE THREAD

**Issue by miyakoj** [google/google-api-javascript-client#270]
I'm suddenly receiving an "invalid scope" error for code that hasn't been changed since the end of December and it worked fine then. It's an AppEngine application. The problem occurs when using localhost and on the live site ([http://www.mywater-flint.com](http://www.mywater-flint.com)).

These are the parameters being sent to Google:

action: listSessions
app_package_name:
client_id: [...].apps.googleusercontent.com
origin: http://localhost:8080
redirect_uri:
response_type:
scope: openid profile email https:// www.googleapis.com/auth/devstorage.read_only https://www.googleapis.com/auth/fusiontables.readonly
ss_domain: http://localhost:8080

I appreciate any help you can give me.

**Comment by TMSCH** [comment]
It seems there is an extra space in your scopes, could you try with:

```
scope: 'openid profile email https://www.googleapis.com/auth/devstorage.read_only https://www.googleapis.com/auth/fusiontables.readonly'
```

**Comment by miyakoj** [comment]
That's what's sent to the server in the XHR request. My string is just "https:// www.googleapis.com/auth/devstorage.read_only https://www.googleapis.com/auth/fusiontables.readonly"

**Comment by TMSCH** [comment]
No, your string has an extra space between the first `https://` and `www.googleapis.com/auth/devstorage.read_only`, I also verified the full URL in your app. It is sent to the server as 2 scopes instead of one. Remove that space and it should work.

**Comment by miyakoj** [comment]
I understand what you mean now. I should have known it was something silly. It works now, thanks for your help.

**Comment by TMSCH** [comment]
You're welcome, glad it worked!
