### ISSUE TITLE
Enable CORS request 

### ISSUE THREAD

**Issue by kavithaLK** [google/google-api-javascript-client#273]
The documentation is not clear about how to enable CORS request. I found this in stackoverflow website , but it is breaking now. 

 gapi.config.update('client/cors', true);

I am getting this error 

:8080/users/password/edit?reset_password_token=XXXXXXXXXXX#parent=http%3A%2F%2Flocalhost%3A7001&rpctoken=XXXXXXXX:1 Refused to display 'http://localhost:8080/users/password/edit?reset_password_token=XXXXXXXXXX-Gvq#parent=http%3A%2F%2Flocalhost%3A7001&rpctoken=XXXXXX' in a frame because it set 'X-Frame-Options' to 'DENY'.

I need to enable CORS to test my application.

**Comment by kavithaLK** [comment]
It was a mistake from my end. Closing it.

**Comment by bsittler** [comment]
FYI: gapi.config.update('client/cors', true) is not part of our official documentation, is not officially supported, and may change or break without notice even if it does happen to work right now. You are strongly discouraged from relying on all such undocumented features of the client library in your application.
