### ISSUE TITLE
404 client.js 

### ISSUE THREAD

**Issue by LeonardoRamos** [google/google-api-javascript-client#276]
Hello all,

From about 3 days ago, the client.js started firing a 404 error trying to access the url bellow:
_https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.pt_BR.SJf8KvYzc0I.…sv=1/d=1/ed=1/am=AQ/rs=AGLTcCMf8jNNllka_eqxUyAY5fP-UWF3dg/cb=gapi.loaded_1_ 

Because of this problem I can't perform auth actions nor get merchant data.
What can I do to solve this problem?

Regards,
Leonardo Ramos.

**Comment by bsittler** [comment]
Hi @LeonardoRamos - what script URL do you use to load the client? In my testing it seems to be working. I've tried the pt_BR lang using a technique like this one and it seemed to load successfully then, too: https://developers.google.com/+/web/+1button/#async-defer

**Comment by ccdunder** [comment]
Sorry that we did not answer this question in a timely fashion. I am closing this for now, but if you still need help with this question, please reopen.
