### ISSUE TITLE
Google Sign-in on iOS not working

### ISSUE THREAD

**Issue by PDSBGreg** [google/google-api-javascript-client#278]
My iOS application is essentially a WKWebView and has been using the web-flow sign-in process for about a year without any issues.

Today, however, our users can't log into the iOS version of the app at all (the Android version still works). After what appears to be a successful login (according to the debug window), the pop-up window throws two errors. The first is one is "Can't close the window because it was not opened by JavaScript". This one pretty much kills the rest of the process, but I can see that lso has complete values. If I try to call lso.relayAuthResponse() in my Safari debug window, just to test, I can see an "invalid_orgin" error.

I haven't changed any of the code on my end and this has been working since about the end of Q1 2016 (when it was first implemented).

Is this related to bug #277 ? Like 277, my code uses a custom sign-in button.

**Comment by TMSCH** [comment]
HI @PDSBGreg, sorry about what seems to be a regression. The "invalid_origin" error is different: this method expects arguments and raise an error if not received.
What are you using to have your app run in a WKWebView? Cordova? Is there any chance the WKWebView plugin has been updated recently?

**Comment by PDSBGreg** [comment]
It's a self-made Cordova (but basically that). Cordova doesn't (or didn't anyway) let you encode videos to specific formats or audio the way we needed it. This is affecting all iOS versions that we've tested as of this weekend (9.3.5 up to 10.2.1). 10.2.1 is new-ish (out a couple of weeks ago), but it was working Friday and isn't today. 9.3.5 was released at some point last year.

**Comment by TMSCH** [comment]
Just to confirm: are you using `gapi.auth2`?

**Comment by davemorrissey** [comment]
@PDSBGreg Re. #277 we haven't seen any errors in the console, and this relates to the web only, so the symptoms are different but it may be a related regression. We also have Cordova apps with Google auth on Android (using cordova-plugin-chrome-apps-identity) and iOS (using cordova-plugin-googleplus) and these are both unaffected by this issue. The googleplus plugin was the only one we could find that meets Apple's current standards, and may be an alternative for you.

**Comment by PDSBGreg** [comment]
Yes, we're using gapi.auth2.

-- The following may or may not be related...

I'm not exactly sure how I would be able to use a Cordova plugin without Cordova. At this point I'm looking into using the iOS Google SignIn code. The problem with it, though, is that it uses Safari and cookies to handle the log in / out. And, since we're on shared devices (between staff and students at the school board), I need to have an actual "complete" sign out which doesn't (or didn't last year when I checked) happen with the iOS Google SignIn code.

The way the current solutions work is that when the sign-in button is pressed, the iOS ViewController intercepts the call and creates a new WKWebView using the same memory pool as the original WKWebView (which essential creates a pop-up window). When the user logs out of the app, I flush the memory pool and re-create the web views, so there is no history of the previous user. As far as I know, this can't happen with the iOS Google code.

**Comment by TMSCH** [comment]
@PDSBGreg thanks for the details. The Google Sign-In iOS SDK indeed relies on Safari and cookies to improve the sign-in experience, however, in your use case, this is detrimental. Have you considered asking your users to enable Private Mode on their devices? Once enabled, all Safari views should be using this mode, so I think this would allow to keep the signed-in Google account restricted to the sign-in flow.

GSI v2 does not officially support WKWebView as we provide the iOS SDK so we *may* have made a change that I'm not aware of that created this issue. I would highly recommend try to use GSI iOS SDK for a better and more reliable support.

**Comment by PDSBGreg** [comment]
Private mode in Safari breaks some of the in house web-only applications that use sessionStorage (pop-up windows don't inherit sessionStorage items in private mode...or, again, they didn't used to). It also blocks the single sign on information behind our Active Directory.

Looks like I'll be looking at re-writing the login process. Do you know how the request for offline access with Google Drive will be affected? That call is supposed to come directly after the 1st login attempt (and does in our current work-flow), but I'm not entirely sure how I can do that with the new sign-in way.

**Comment by TMSCH** [comment]
@PDSBGreg I am not entirely sure to understand your question: do you need to get an offline code to access Google Drive? Could you use this: https://developers.google.com/identity/sign-in/ios/offline-access?
I think setting the `serverClientId` would allow to get both `idToken` and `code`.

**Comment by PDSBGreg** [comment]
Yes, something like that. I'll see if I can get that working tomorrow.

Thanks. ... I guess there isn't any change of rolling the code back to before whatever got pushed out over the weekend?

**Comment by TMSCH** [comment]
As `gapi.auth2` do not officially support WKWebView, and, more importantly than that, we have deprecated OAuth login in UIWebView/WKWebView (see [blog post](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html)) we are not able to roll back the code for this reason.

**Comment by PDSBGreg** [comment]
Interesting. I wish I would have seen that sooner!

Last comment for the night. Any idea how I can connect the idToken, etc that I receive from the iOS SignIn code back to gapi.auth2.getAuthInstance() and the Google Drive javascript library ... gapi.client.load('drive', 'v3') ...? Since all of the application logic is held in the web view?

**Comment by TMSCH** [comment]
This is currently not possible to use `gapi.client` with a token received externally (i.e. not obtained through `gapi.auth` or `gapi.auth2`). In your use case, you probably have to query yourself the endpoints instead of using `gapi.client`.

**Comment by PDSBGreg** [comment]
Ok. Looks like I have a lot of re-writing ahead of me. I'll close this since it won't be fixed.

**Comment by TMSCH** [comment]
Thanks for your understanding!
