### ISSUE TITLE
How to get refresh token while using Google API JS Client

### ISSUE THREAD

**Issue by lchhieu** [google/google-api-javascript-client#279]
I can't login google client using google api client php. I get error miss refresh  token
I need to know how can I get the refresh_token when the user grants access for the first time so that I can save it.

**Comment by TMSCH** [comment]
@lchhieu using `gapi.auth2`, you can obtain a code that is exchangeable for a refresh token in your server. See: https://developers.google.com/identity/sign-in/web/server-side-flow. However, if you use `gapi.client` to make authenticated requests to Google APIs, you don't need to handle yourself the `refresh_token`: `gapi.auth2` will take care of that in the client.

**Comment by lchhieu** [comment]
@TMSCH, how to I can login google client in PHP using token from result return from  Google API JS Client

**Comment by TMSCH** [comment]
Once you get the code in the backend, you can follow Step 5 of this guide: https://developers.google.com/api-client-library/php/auth/web-app#exchange-authorization-code to exchange it.
This repository concerns the JS client though, if your questions are about the PHP client, please ask them on StackOverflow.

**Comment by TMSCH** [comment]
Closing this bug as the documentation pointed to should fix the issue. Please re-open if you still have issues.

**Comment by Sid21m** [comment]
@TMSCH  When i try to exchange the code for refresh token and access token, I get a redirect_uri_mismatch error. My redirect_uri is valid. So after some research I found out you need to use "postmessage" as redirect uri. Now I am only getting access token, no refresh_token. 

Note: I have already authenticated my application using web flow. I am only using gapi.auth2.authorize for incremental authorization.

**Comment by TMSCH** [comment]
Hi @Sid21m, I am not sure to understand what you are trying to achieve. What did you use to sign in the user in the first place (i.e. what do you mean by web flow)? Could you post a snippet of code for the incremental auth? In `gapi.auth1.authorize`, there is no `redirect_uri` parameter (See [doc](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeconfig)).
