### ISSUE TITLE
gapi.auth.authorize doesn't callback when landing page with back button

### ISSUE THREAD

**Issue by ristinolla** [google/google-api-javascript-client#280]
On our Angular app we are using the `gapi.auth.authorize` -function to authenticate users. It works fine when the user lands on the page or refreshes the page, but when landing on the page via browsers back button the function doesn't fire the callback function at all. The weird part is that this behaviour happens only on Chrome (56.0.2924.87) both on Windows and Mac.

I've tested the behaviour on following browsers and there it works.

- Safari (10.0.3) on Mac 
- Firefox (51.0.1) on Mac
- Firefox (51.0.1) on Windows
- Explorer (11) on Windows

The script used: https://apis.google.com/js/client.js. The script is loaded syncronously and double checked in the code if the client is available in `window.gapi.client`. When it is available then continuing the authentication.

The code we use in our Google Auth Service to authenticate users. Immediate value is true in both fresh refresh and on back button landing.

    this.googleAuth = function (immediate, callback) {        
        function _authCallback(authResult){
            if (authResult && authResult.status && authResult.status.signed_in) {
                $rootScope.loginProgress = 60;
                callback(null, authResult);
            } else {
                callback({ "error": authResult }, null);
            }
        }

        gapi.auth.authorize({
            "client_id": GoogleApp.clientId,
            "scope": GoogleApp.scopes,
            "immediate": immediate
        }, _authCallback );
    };

**Comment by TMSCH** [comment]
Hi @ristinolla, `gapi.auth` has been deprecated, I would recommend migrating to `gapi.auth2`. See doc: https://developers.google.com/identity/sign-in/web/. This new library is more secure and reliable, and it will very likely fix this issue (we haven't heard of such issue with the v2). Could you consider that? Thanks!

**Comment by ristinolla** [comment]
Thanks for the reply, @TMSCH! I wasn't quite sure if it was deprecated or not. I implemented it and now it seems to work. So I guess this can be closed. =) cheers!

**Comment by TMSCH** [comment]
Thanks for the update @ristinolla! Closing this issue.
