### ISSUE TITLE
Batch request on youtube v3 playlistItems.insert doesn't work as expected

### ISSUE THREAD

**Issue by OGPoyraz** [google/google-api-javascript-client#284]
Hi there,

I was playing with v3 Youtube API yesterday and found something unexpected / missing something.

Below code piece is creating a batch request to add multiple playlistItems.insert request and executes them. 

```es6
const gapiRequest = (playlistId,videoId,i) => gapi.client.request({
    path: '/youtube/v3/playlistItems?part=snippet',
    method:'POST',
    body:JSON.stringify({
        snippet: {
            playlistId,
            position:i,
            resourceId:{
                videoId,
                kind: 'youtube#video'
            }
        }
    })
})

let addItemsToList = gapi.client.newBatch();
songs.map((song,i) => {
    addItemsToList.add(
        gapiRequest(playlistId,song.get('id'),i)
    );
})

addItemsToList.then(result => {
    console.log(result)
    debugger;
})
```

I double checked the batch request. As I expected it has 19 (means I'm tryin to add 19 playlist item to playlist) request. 

<img width="212" alt="screen shot 2017-03-03 at 09 40 08" src="https://cloud.githubusercontent.com/assets/7644512/23542029/8f09c9a8-fff3-11e6-8bde-0b944c9cd929.png">

Also it's looks all working fine when I debug result. Batch request returns status 200 (means all playlistItems inserted) for every batch item.

<img width="374" alt="screen shot 2017-03-03 at 10 11 15" src="https://cloud.githubusercontent.com/assets/7644512/23542035/93e1bdd2-fff3-11e6-8f48-79a7e201f19b.png">

But when it comes to [youtube playlist][1] I only see 3(sometimes 5-6) song added.

 Does anyone have an idea what's going on / what am I missing ? 

  [1]: https://www.youtube.com/playlist?list=PLHeHlEd7zUAh0zHDwASJ_Nvks4VXbD8gu

**Comment by bochunz** [comment]
Does it always work if you send individual request instead of batching?

Note that this repo is for the JavaScript library (which supports all Google's APIs). Seems like the batch requests are working properly but the YouTube API is behaving unexpected. If this is the case, could you redirect the question to the YouTube API? https://developers.google.com/youtube/v3/

**Comment by OGPoyraz** [comment]
It actually works fine when I request them one by one.

Also working fine individual on [youtube/v3/playlistItems.insert api explorer.](https://developers.google.com/youtube/v3/docs/playlistItems/insert)

Actually not sure it's because youtube / batch api 😕

**Comment by OGPoyraz** [comment]
It looks batch api makes its job well might have problem on youtube api.

Gonna try my chance on [SO](http://stackoverflow.com/questions/42573723/gapi-batch-request-on-youtube-v3-playlistitems-insert-doesnt-work-as-expected)

**Comment by bochunz** [comment]
One thing you probably could look at is quota. If you don't have enough quota QPS, some of the requests in batch could get rejected.

https://console.cloud.google.com/apis/api/youtube.googleapis.com/quotas

**Comment by OGPoyraz** [comment]
I guess you mean these settings. In my console I cant see any spesific setting for Query Per Second.

 - Queries per day 
 - Queries per 100 seconds per user 
 - Queries per 100 seconds

**Comment by bochunz** [comment]
Yes. There should be a default limit on these numbers. Please verify the numbers are now too low.
