### ISSUE TITLE
How to revoke access granted for for user individual ?

### ISSUE THREAD

**Issue by lchhieu** [google/google-api-javascript-client#285]
i forgot to save token of user login, so i can't revoking using get https://accounts.google.com/o/oauth2/revoke?token={token}
If use disconnect() then all account will be revoked.

**Comment by TMSCH** [comment]
If you call `disconnect()` on the `GoogleUser` instance (see [doc](https://developers.google.com/identity/sign-in/web/reference#googleuserdisconnect)), only the current user account will be revoked.

Is that what you are looking for?

**Comment by TMSCH** [comment]
Closing this issue as `disconnect()` is the way to revoke access granted for an user to an app.
