### ISSUE TITLE
Repo misnamed?

### ISSUE THREAD

**Issue by weirdan** [google/google-api-javascript-client#286]
This repo doesn't seem to contain google api javascript client sources, as the name suggests. Since it only has samples, shouldn't it be renamed to something like `google-api-javascript-client-samples`?

Alternatively it could be used to publish client sources (would fix #211 )

**Comment by bsittler** [comment]
My hope is that we will eventually find satisfactory resolutions to the issues currently preventing a fix for #211 at which point the name would be more accurate. The repository name was chosen with that in mind.

**Comment by grant** [comment]
I think the trend with client libraries is to keep samples and the client the same. In this case, the client isn't in on GitHub yet, and so `google-api-javascript-client` is the name of this repo.

I recently took interest in this repo and will see if I can fix #211.

**Comment by gewentao** [comment]
Sorry for commenting in this closed issue.
Is there any update about #211 ? It would be very helpful to get a unminified version of js client library.
Thanks!
