### ISSUE TITLE
OAUTH and Youtube API

### ISSUE THREAD

**Issue by lorytif** [google/google-api-javascript-client#289]
Hi, 

I would like to know if it is possible to have an application in Javascript and a Youtube Channel with video in private ( just one user authorized) . The user navigate on my javascript application and decide to view my private video without logged in. I explain me. I would like my application send directly the identifiant to view my private video and this process is transparent for the user. Is it possible with Oauth 2 ? 

Thanks in advance

**Comment by TMSCH** [comment]
Hi @lorytif, OAuth 2.0 requires the user to sign in so what you want to do is not possible. I am less familiar with YouTube APIs, but it seems that if the video is private no other user besides the one authorized will be able to access it.

**Comment by lorytif** [comment]
Hum Ok :/ it's a real problem for me... Thanks

**Comment by TMSCH** [comment]
I am not sure to understand: if you want other people than you to be able to watch the video, you should change the setting of the video to allow other users. I am not familiar with the YouTube settings but I think there is one where the video is not searchable but if you have the link you can watch it. Maybe that's what you're looking for?
OAuth 2.0 is unrelated here as you don't want your users to sign in.

**Comment by seahopark** [comment]
Sorry for the interrupt, so you mean we cannot access to users private contents with OAuth 2.0? 
and only way to solve this is let users to unlock the private mode on youtube?

**Comment by TMSCH** [comment]
Closing the issue as no follow up was given. Please reopen with more info if this is still an issue.
