### ISSUE TITLE
Missing documentation on approval_prompt = "force" for grantOfflineAccess

### ISSUE THREAD

**Issue by nickrussler** [google/google-api-javascript-client#290]
I use the gapi js client to conveniently retrieve the code for offline usage by my backend by calling `grantOfflineAccess({approval_prompt : 'force'})` which works just fine, but the `approval_prompt` parameter isn't documented anywhere.

It would be great if this parameter would be added to the documentation.

**Comment by TMSCH** [comment]
This parameter has been removed from Google Sign-In v2. You should use the OpenID compliant version: `grantOfflineAccess({prompt: 'consent'})`. See [doc](https://developers.google.com/identity/sign-in/web/reference#gapiauth2offlineaccessoptions).

**Comment by ernbrn** [comment]
I'm running into an issue where `grantOfflineAccess({prompt: 'consent'})` is not always prompting for consent. If I revoke access to my app via "Apps with access to your account" and then I try to sign in again, the consent popup does not show and sign in fails. Is there a way to truly force the consent screen to always show?
