### ISSUE TITLE
500 errors from server on redirect?

### ISSUE THREAD

**Issue by eschultink** [google/google-api-javascript-client#291]
We've been using this JS library to federate identity with Google for a year or more, and today we started getting the following error in the popup:
<img width="1224" alt="error_500__server_error___1_and_worklytics" src="https://cloud.githubusercontent.com/assets/102831/25255458/8e26aeae-25df-11e7-901d-590cdb10d9f4.png">

Full URL of the popup (generated by the library) is something like below, except that I've inserted the tokens `{{domain}}` / `{{clientId}}` in place of the query param values for each of those (which appear valid):

`https://accounts.google.com/o/oauth2/auth?redirect_uri=postmessage&response_type=permission%20id_token&scope=email%20profile%20openid&openid.realm=&client_id={{clientId}}&ss_domain={{domain}}&fetch_basic_profile=true&gsiwebsdk=2`

We trigger the signon flow as follows: 
```javascript
gapi.load('auth2', function () {
        this.googleAuth = gapi.auth2.init({
          client_id: CLIENT_ID,
        });
      }.bind(this));

// then later in response to user clicking on our Google sign-on button

 this.googleAuth.signIn({'redirect_uri': 'postmessage'})
        .then(function (authResult) {
              //parse result, validate, and sign user in
        }.bind(this));
    },
```

NOTE: `gapi` is the library hosted at `https://apis.google.com/js/client:platform.js?onload=start`, which we include dynamically using requirejs.

Headers returned by Google don't suggest anything helpful:
<img width="622" alt="developer_tools_-_https___accounts_google_com_o_oauth2_auth_redirect_uri_postmessage_response_type_permission_20id_token_scope_email_20profile_20openid_openid_realm__client_id_325404107925-sglbl2lla6vc2e662uhnpk6grdmp7eua_apps_googleusercon" src="https://cloud.githubusercontent.com/assets/102831/25255871/0d2e5cfe-25e2-11e7-8dde-118b6383b00c.png">

The error is happening in all of our deployments that I've been able to test - each with different client-id / domain values, so I don't believe it's a configuration issue related to one of those.

**Comment by TMSCH** [comment]
Hi @eschultink, `{'redirect_uri': 'postmessage'}` is invalid. `'postmessage'` is not supported. See [doc](https://developers.google.com/identity/sign-in/web/reference#gapiauth2signinoptions) for the valid options (only actual URL are expected, when using `ux_mode: 'redirect'`. Remove this and it should work.

It is actually surprising that it worked so far... Would you have recently started using GSI v2? Or added this parameter?

**Comment by eschultink** [comment]
@TMSCH thanks for quick response; seems to work.  We've had that `redirect_uri` part in there for at least 11 months. As far as I can tell, since our first implementation using this library.  I'm not sure where we got it from, as I agree I don't see it mentioned in the current documentation. 

Previously we had experimented with some different approaches for integrating with Google auth, so perhaps it came from a different flow prior to us porting to this library.

I know it's tough - but something other than "500 ... please try again later" would always be helpful.  Maybe "400 Bad Request" in a case like this?

**Comment by TMSCH** [comment]
@eschultink it seems that our backend made changes that started rejecting this parameter instead of ignoring it (probably for the better), but I agree that the 500 error is not helpful. I have forwarded this issue to the relevant team.
As it is not directly related to the JS library, closing the issue.

**Comment by TMSCH** [comment]
Actually, my bad. The JS library started passing this invalid parameter to the backend. We are going to push a fix soon.

**Comment by TMSCH** [comment]
The issue has now been fixed. The client library will ignore the deprecated param`redirect_uri:  'postmessage'`. Closing.
