### ISSUE TITLE
Access to Case Sensitive Email

### ISSUE THREAD

**Issue by mjgallag** [google/google-api-javascript-client#292]
Is there any way to access a case sensitive version of the user's email?
<img width="573" alt="screen shot 2017-05-03 at 12 33 16 pm" src="https://cloud.githubusercontent.com/assets/1046027/25677957/e7a33bd8-2ffc-11e7-9f79-9cffa6cc49c7.png">

**Comment by TMSCH** [comment]
Hi @mjgallag, I am not sure to understand. What do you mean by access a case sensitive version of the user's email? In the profile info returned after a sign-in flow with the gapi.auth2 library?

**Comment by mjgallag** [comment]
Yes, exactly.

**Comment by TMSCH** [comment]
What are you using to get the email address of the user? Could you provide a snippet of code?

**Comment by mjgallag** [comment]
`email` is `temmittibal@gmail.com` for the above mentioned imaginary account I created for testing purposes.
```
    <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
    <script>
      function onSuccess(googleUser) {
        var profile = googleUser.getBasicProfile();
        var email = profile.getEmail();
        ...
```
Thank you for taking a look at this @TMSCH.

**Comment by mjgallag** [comment]
@TMSCH any advice you can give on possible workarounds  to investigate would be greatly appreciated, thanks again.

**Comment by TMSCH** [comment]
@mjgallag have you tried user the userinfo endpoint?

https://developers.google.com/apis-explorer/#search/userinfo/m/oauth2/v2/oauth2.userinfo.v2.me.get?fields=email&_h=1&

**Comment by mjgallag** [comment]
<img width="327" alt="screen shot 2017-05-10 at 6 16 59 pm" src="https://cloud.githubusercontent.com/assets/1046027/25927832/7c4c2d02-35ad-11e7-9d66-30d3dfc6cbed.png">

@TMSCH unfortunately that one is lowercased too.

**Comment by TMSCH** [comment]
@mjgallag forwarding the request internally to the right team.

Could you be more specific about the user case here? Why needing the case sensitive version?

Also, where did you get the screenshot you attached in your first comment?

**Comment by mjgallag** [comment]
@TMSCH thanks. Screenshot is from an AppEngine Java Standard environment link `https://appengine.google.com/_ah/loginform?state=...`.

We're a fork of an open source project that allows you to build android apps without code. We allow importing of android app projects from the original. The user expects the Android Application Id of their imported project to match the original. but these are not stored with the project, they are generated at build time, and email is part of them. Unfortunately Android App Ids are case sensitive and the open source project used the case sensitive version of the email. So we need some way of accessing it in order to generate a matching Android Application Id.

**Comment by TMSCH** [comment]
@mjgallag thanks for the explanation. I will forward it.

**Comment by mjgallag** [comment]
@TMSCH just checking in, any internal response? Thanks!

**Comment by TMSCH** [comment]
@mjgallag I haven't been able to find any public API that would provide a case sensitive email address. How does the original open source project get it?

**Comment by mjgallag** [comment]
@TMSCH see my previous comments above
> Screenshot is from an AppEngine Java Standard environment link `https://appengine.google.com/_ah/loginform`
<img width="573" alt="screen shot 2017-05-03 at 12 33 16 pm" src="https://cloud.githubusercontent.com/assets/1046027/25677957/e7a33bd8-2ffc-11e7-9f79-9cffa6cc49c7.png">

**Comment by TMSCH** [comment]
@mjgallag I got that, I meant to ask couldn't you get the email address using their same technique?

**Comment by mjgallag** [comment]
@TMSCH we found a workaround for this, thank you for your help!

**Comment by TMSCH** [comment]
Glad to hear that! How did you end up doing?

**Comment by mjgallag** [comment]
@TMSCH I don't think there would have been a way to get case sensitive email using the same technique (old app engine login form above) without putting the user thru a strange additional login flow. Turns out it was available in the file being imported we just couldn't trust it, but we decided it was safe to trust it assuming it only differed by case.

**Comment by TMSCH** [comment]
@mjgallag thanks for explaining.
