### ISSUE TITLE
GoogleUser.grantOfflineAccess - called by currentUser.listen() cb - TypeError: Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by ghiaia** [google/google-api-javascript-client#295]
In the streamlined attached file a "user change event" trigger a new GoogleUser.grantOfflineAccess by GoogleAuth.currentUser.listen callback.

Chrome respond: TypeError: Cannot read property 'focus' of null or popup_closed_by_user
Firefox: similar.

What is wrong ?

[index.html.txt](https://github.com/google/google-api-javascript-client/files/987928/index.html.txt)

P.S.
The original application is a React Redux app, where it works but only in dev mode.

**Comment by TMSCH** [comment]
Hi @ghiaia, I think the problem is that you trigger a `grantOfflineAccess` call, that opens a popup, asynchronously. This is not possible in most browsers. You need to open a popup *synchronously after a user interaction on the page*.
However, the error that you observe is not clear in this scenario so we're going to address this and provide better feedback in case the browser has blocked the popup.

**Comment by ghiaia** [comment]
Same problem if called in init().then().
Yes. Called asynchronously.
If I called by dev console it works.

Uhmm! I need to get an offline code after auth2.init or signIn without bother the user with a new "click"

**Comment by TMSCH** [comment]
If you just want an offline code, without client-side handling of the user's state, you can use [`gapi.auth2.authorize`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams-callback). This would obtain a code for the user in one click. Would that work for your use case?

**Comment by ghiaia** [comment]
Apparently we need a a mixed solution (client-side, server-side inside domain and outside domain, so "service_account" does not suffice).
It is a large intranet and extanet collaborative set of apps comprehending industrial plants integrations.

auth2.authorize may be a solution, but I think " incremental authorization" concept is better.

Thank you!

**Comment by TMSCH** [comment]
Incremental authorization is indeed usually a better UX for large apps. Glad you found the solution!
