### ISSUE TITLE
Google OAuth signIn() to return non-uglified response?

### ISSUE THREAD

**Issue by Aaron-Zhao** [google/google-api-javascript-client#296]
I am using https://apis.google.com/js/api.js, and calling gapi.auth2.getAuthInstance().signIn() but it's giving me all these uglified (object properties) in the response.

Is there any way to get a clean response?

**Comment by TMSCH** [comment]
@Aaron-Zhao could you be a little more specific? What response are you talking about? Please provide the snippet of code where you observe these properties.

Uglified/minified properties are extremely common in JavaScript `Object`s that are not pure maps of string to string, and required. Depending on what `Object` you are referring to, it is very likely that we cannot update the code to get a clean response.

**Comment by Aaron-Zhao** [comment]
https://developers.google.com/api-client-library/javascript/reference/referencedocs#googleauthsigninoptions

Thanks for the response. I was referring to the response from the above function.

I figured maybe I am not supposed to read the response.

**Comment by TMSCH** [comment]
Oh the doc does not mention the response returned in the promise. We will update this.

The response is a [GoogleUser](https://devsite.googleplex.com/identity/sign-in/web/reference#googleusergetid), so you should only read the exposed methods and properties defined in the doc.

```javascript
gapi.auth2.getAuthInstance().signIn().then((user) => {
  const userId = user.getId();
});
```

**Comment by Aaron-Zhao** [comment]
Cool, that's helpful. Thanks!
