### ISSUE TITLE
How to use API key

### ISSUE THREAD

**Issue by tnguyen14** [google/google-api-javascript-client#298]
Hi, this is more of a question - your sample shows that the API key should be in the client-side JS/ HTML. However, this guide https://support.google.com/cloud/answer/6310037 says that the API key should be secure and not be exposed publicly. What is the right best practice here?

**Comment by bochunz** [comment]
For web apps:

- Apply HTTP Referer restriction to the API key
- Rotate your API key periodically

**Comment by tnguyen14** [comment]
Thanks. Do you have any reference to how to "Apply HTTP Referer restriction to the API key"?

**Comment by bochunz** [comment]
Go to https://console.cloud.google.com/apis/credentials, click on the edit button on your API key.

**Comment by tnguyen14** [comment]
Ok thanks. Do you think those 2 best practices are worth documenting somewhere?

**Comment by bochunz** [comment]
They are already in the https://support.google.com/cloud/answer/6310037, right?

**Comment by tnguyen14** [comment]
That was confusing to me. In that article, it says the key should not be embedded in the code. In this repo's example, the key is supposed to be included in the code.

Furthermore, there was no mention of HTTP Referer restriction.
