### ISSUE TITLE
prompt select_account or consent causes 400 error on iframerpc

### ISSUE THREAD

**Issue by kzahel** [google/google-api-javascript-client#299]
This used to work fine but ever since the new signin screen rolled out a few weeks back I am seeing this error when I set prompt to `consent` or  `select_account` when calling `gapi.auth2.init`

Request URL:
`https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&scope=openid%20email%20profile&prompt=select_account&client_id=xxx&login_hint=xxx&ss_domain=xxx&origin=xxx`
Response body
`{
  "error" : "invalid_request",
  "error_description" : "Parameter not allowed for this message type: prompt"
}`

I am using `gapi.load('auth2',...)`and using the `https://apis.google.com/js/api.js` library

Steps to reproduce
1. include `https://apis.google.com/js/api.js`
2. initialize `gapi.load('auth2',...)`
3. Call `gapi.auth2.init` with a `prompt: 'select_account'` option as well as valid client id etc.
4. `gapi.auth2.getAuthInstance().signIn()` and authorize the login screen
5. You will see the 400 response.

**Comment by TMSCH** [comment]
Hi @kzahel, the `prompt` parameter should be passed to the `signIn` method, not the `init`.

**Comment by kzahel** [comment]
Thanks! My mistake. It's working great now.

**Comment by TMSCH** [comment]
Great!
