### ISSUE TITLE
400 Error: Request mask can not be empty

### ISSUE THREAD

**Issue by colingoldberg** [google/google-api-javascript-client#300]
The page - authSample.html - fails with a 400 error.

I copied the file as is - except filling in the apiKey and clientId.

{
  "error": {
    "code": 400,
    "message": "Request mask can not be empty. Valid paths are: [person.addresses, person.age_ranges, person.biographies, person.birthdays, person.bragging_rights, person.cover_photos, person.email_addresses, person.events, person.genders, person.im_clients, person.interests, person.locales, person.memberships, person.metadata, person.names, person.nicknames, person.occupations, person.organizations, person.phone_numbers, person.photos, person.relations, person.relationship_interests, person.relationship_statuses, person.residences, person.skills, person.taglines, person.urls].",
    "status": "INVALID_ARGUMENT"
  }
}

"Request mask" is unclear - where does this apply?

**Comment by bochunz** [comment]
Looks like there's a recent change in the People API. I have fixed the sample, please try with the new version.

**Comment by Aaron-Zhao** [comment]
On top of this, to include multiple fields you just separate the paths by comma per [this reference](https://developers.google.com/people/api/rest/v1/RequestMask). 

For example, 
`{
        'resourceName': 'people/me',
        'requestMask.includeField': 'person.names,person.photos,person.email_addresses'
      }`

I noticed that adding space after comma, such as `'person.names, person.photos'`, will give you error `' person.photos' not vaild..` as the spaces were not trimmed after parsing. It would be nice if you guys check for spaces, as comma separated without space gets hard to read pretty quickly if you have more fields. Or better yet, if we can just pass an array instead of a string.

**Comment by nkaki** [comment]
I've tried both:
'requestMask':{'includeField':'person.email_addresses'}
'requestMask.includeField':'person.email_addresses'}

and I get this error

Invalid JSON payload received. Unknown name "requestMask": Cannot bind query parameter. 'requestMask' is a message type. Parameters can only be bound to primitive types.

**Comment by bochunz** [comment]
@nkaki I think your second example should work. What error did you get from trying the second example?

**Comment by nkaki** [comment]
I get the same error.

**Comment by nkaki** [comment]
For
`'requestMask':{'includeField':'person.email_addresses'}`
I get:
Invalid JSON payload received. Unknown name "requestMask": Cannot bind query parameter. 'requestMask' is a message type. Parameters can only be bound to primitive types.


For
`'requestMask.includeField':'person.email_addresses'}`
I get:
Request mask can not be empty. Valid paths are: [person.addresses, person.age_ranges, person.biographies, person.birthdays, person.bragging_rights, person.cover_photos, person.email_addresses, person.events, person.genders, person.im_clients, person.interests, person.locales, person.memberships, person.metadata, person.names, person.nicknames, person.occupations, person.organizations, person.phone_numbers, person.photos, person.relations, person.relationship_interests, person.relationship_statuses, person.residences, person.skills, person.taglines, person.urls].

**Comment by nkaki** [comment]
Hello, has anyone looked at this issue?

**Comment by Blamo27** [comment]
@nkaki 

```
gapi.client.people.people.get({
  'resourceName': 'people/me',
  'requestMask.includeField': 'person.names,person.emailAddresses,person.genders,person.birthdays'
 })
```

**Comment by Blamo27** [comment]
You can get the list there : http://i.imgur.com/6SMn4UH.png

**Comment by nkaki** [comment]
Now I get this error for both `person.emailAddresses` and `person.email_addresses`

`personFields mask is required. Please specify one or more valid paths. Valid paths are documented at https://developers.google.com/people/api/rest/v1/people/get.`

**Comment by bochunz** [comment]
@nkaki  I think @Blamo27 's format is correct. Have you tried the exact same syntax in @Blamo27 's example?

**Comment by nkaki** [comment]
I get this error when I use the same syntax in @Blamo27 's example `Requested entity was not found.` using `people.people.get`

But I want to get the list of people in the contacts for the authorized user, so shouldn't I use `people.people.connections.list`?

**Comment by Blamo27** [comment]
@nkaki Maybe try this

```
people.people.connections.list({
    'resourceName': 'people/me',
    'requestMask.includeField': 'person.emailAddresses'
})
```

**Comment by Blamo27** [comment]
No space inside the string 'person.emailAddresses' /!\

**Comment by nkaki** [comment]
@bochunz and @Blamo27 Thanks it solved it !!

**Comment by jakal23** [comment]
maybe
{
    'resourceName': 'people/me',
    'personFields': 'emailAddresses,genders'
})

**Comment by megapat** [comment]
I've tried all of the proposed solutions, but without success. The result is always:
Error: personFields mask is required. Please specify one or more valid paths. Valid paths are documented at https://developers.google.com/people/api/rest/v1/people/get

**Comment by rakeshvasal** [comment]
Try this it works...

ListConnectionsResponse connectionsResponse = service
                        .people()
                        .connections()
                        .list("people/me")
                        .set("personFields","names,addresses,birthdays,genders,phoneNumbers,photos")
                        .execute();

**Comment by erwin16** [comment]
with the V3 APi , should write now in javascript 👍 

personFields:  ['locales','genders','names','emailAddresses'],
