### ISSUE TITLE
Loading  gapi.load('auth2'...) does not correspond to CSP 

### ISSUE THREAD

**Issue by koriguy** [google/google-api-javascript-client#302]
When lazy loading 'auth2' module we get inline style injections in the script
this doesn't correspond with CSP thus we have to allow inline-style

Is there a way to load the auth2 lib without style injection?

**Comment by TMSCH** [comment]
Hi @koriguy, I am not sure what's happening here as `gapi.auth2` library has no UI component. Would you be using by any chance, `gapi.signin2`?

**Comment by koriguy** [comment]
Hi @TMSCH 
when we make the call:
`gapi.load('client:auth2', () => {...})
`

this file is being downloaded

`https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.mLDHj5jhiDw.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCPA-o7OHfveXK_Wlg8cITPdWFou1A/cb=gapi.loaded_0`

the callback is trying to insert styling

**Comment by TMSCH** [comment]
@koriguy I think the styling coming from the library is for the IFrame required by auth2. It dynamically creates the IFrame element and style it such as it is not visible. Is that the styling you mention?

**Comment by koriguy** [comment]
I can't say for sure since CSP report doesn't specify exactly what is the styling
It just blocks all inline styling so we have a violation. Currently we added an exception for inline-style
('unsafe-inline') but this is ideal since it can expose us to risks

**Comment by TMSCH** [comment]
@koriguy thanks for the information given. I think I've identified the issue on our end. I will get back to you when it's fixed!

**Comment by TMSCH** [comment]
Hi @koriguy, the issue should have been fixed. Let me know if that works!

**Comment by koriguy** [comment]
@TMSCH great, it seems to work fine now
Thanks for the quick response

**Comment by TMSCH** [comment]
Awesome! You're welcome :)
