### ISSUE TITLE
gapi.client.init() with access token?

### ISSUE THREAD

**Issue by theunreal** [google/google-api-javascript-client#304]
I'm using Google Firebase to authenticate users, and after the user is authenticated I get an access token.

I know that I can use this access token in order to work with google api's, but I can't find any way to work with gapi using this access token.

Is there any way to use gapi assuming I already have an access token?

What I'm trying to do is access the user calendar after simply authenticating with Firebase.

**Comment by bsittler** [comment]
Have you tried gapi.auth.setToken({access_token:'.....'}) ? It's possible there is a newer/better way to do this, though.

**Comment by TMSCH** [comment]
@theunreal I would recommend using `gapi.client.setToken({access_token:'.....'})`, we added this method recently but haven't documented it yet.

**Comment by theunreal** [comment]
Thanks! @bsittler @TMSCH

**Comment by adrienjamot** [comment]
@TMSCH Can you explain how to use this method ??

I'd like to allow my users to upload their videos directly in my Youtube channel without login, is that possible ?

**Comment by mesqueeb** [comment]
@TMSCH 
Can you explain a bit more on how to use this?
My problem is: If I use firebase for auth, then try to send the token to GAPI like so:
```js
function initClient() {
  window.gapi.client.init(googleCalendarConfig)
  .then(_ => {
    console.log('init ok')
  })
  .catch(error => {
    dispatch('authenticationError', {error, note: 'Error on GAPI init.'})
  })
}
window.gapi.load('client', initClient)
window.gapi.client.setToken({access_token:'.....'})
```
Then I still get this error:
```js
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
```
How do I initialize the auth of `gapi` with just `gapi.client.setToken({access_token:'.....'})` ?
Or do I need to do other things as well?

**Comment by TMSCH** [comment]
@adrienjamot if you can obtain an Access Token from your backend (for instance using a Refresh Token) no need to "authenticate" the user. Just pass the access token to `gapi.client.setToken({access_token: 'ACCESS_TOKEN_RETURNED_FROM_BACKEND'})`.

@mesqueeb make sure you pass the `access_token` to the `setToken` call, not the `id_token` (I saw this in another of the issue you opened). ID Token is meant for **authenticating** the user in your backend, Access Token is meant for **authorizing** requests to Google APIs.

**Comment by luis-almeida** [comment]
@TMSCH first of all, thanks for your help!

I'm having the exact same problem. Passing the access token I get back from the server to `gapi.client.setToken({ access_token: 'ACCESS_TOKEN_RETURNED_FROM_BACKEND' })` is simply not enough as `gapi.auth2.getInstance()` just returns `null`.
I wonder what else is missing as this seems to be the recommended approach (?)

**Comment by TMSCH** [comment]
@luis-almeida see #401 for more details on why this is not possible, and how to make it work.

**Comment by gpashis** [comment]
@TMSCH @mesqueeb I am unable find any documentation to get new access token in exchange of expired access token using **gapi.client**. As per my requirement I have to avoid login popup once user gives their permission. Also I would be able to pass these permission to any other devices.

I see a solution to get new access token by exchanging refresh token using PHP client. https://github.com/googleapis/google-api-php-client#obtainingaccesstokens

Do we need to go through **Security Assessment** if you combine both PHP and JS client?
Or
Do we have any other ways to solve this using JS client?

Thanks.

**Comment by azumbrunnen** [comment]
> @theunreal I would recommend using `gapi.client.setToken({access_token:'.....'})`, we added this method recently but haven't documented it yet.

Is this documented somewhere now? This answer is 2 years old and I feel it's still very hard to make GAPI client work predictably.

**Comment by manishatiwari1696** [comment]
Hello everybody,
I'am facing issue with google calendar. The issue is "when user1 is connecting his google calendar with our website account and then logout his account from our website only and then user2 connect his google calendar with his account of our website and then logout. So what happening is, now if user1 is login to his account then he is not able to access his google calendar and the error image link is shown below".
(https://user-images.githubusercontent.com/38031527/88327203-730e2b00-cd44-11ea-86d2-23bea41cf789.jpeg)
. 

Please help me out, what should I need to do to make this process work. I'm stuck with this issue from long time. I must be missing something.

**Comment by sarodhesachin** [comment]
Hey @TMSCH,
I am trying to authenticate google drive api using a firebase authentication token using setToken i.e
`gapi.client.setToken({access_token: firestoreDatabase.auth().currentUser.toJSON().stsTokenManager.accessToken})`

I went through many tutorials and blogs and tried different approaches but setToken is not working as expected. Is there any other workaround to authenticate the user using firebase token(without showing a popup).

Here is my approach

```
const { email, stsTokenManager } = firestoreDatabase.auth().currentUser.toJSON();
const { accessToken } = stsTokenManager;

window.gapi.client
      .init({
        apiKey: config.apiKey,
        clientId: config.clientId,
        discoveryDocs: DISCOVERY_DOCS,
        scope: SCOPES,
        login_hint: email,
      })
      .then(async function () {
        const auth2 = window.gapi.auth2.getAuthInstance();

        if (auth2.isSignedIn.get()) {
          callback();
        } else {
          window.gapi.client.setToken({ access_token: accessToken })
        }

        console.log(window.gapi.auth2.getAuthInstance().isSignedIn.get()) //false
      });
```

**Comment by mrabro** [comment]
> @theunreal I would recommend using `gapi.client.setToken({access_token:'.....'})`, we added this method recently but haven't documented it yet.

This saved my day ... Thanks :)
