### ISSUE TITLE
Batch requests?

### ISSUE THREAD

**Issue by spyeadon** [google/google-api-javascript-client#307]
Does this API support batch requests? And can I use it in tandem with the [Google API Node.js Client](https://github.com/google/google-api-nodejs-client)?

I'm looking for a way to make batch requests to the gmail API so that I can:
1) get a list of 50 message id's using gmail.users.messages.list
2) get the message data for each of those 50 messages using gmail.users.messages.get on each message
3) then repeat the process in 1) and 2) with gmail.users.drafts **and** gmail.users.threads.

Is this possible?

**Comment by bsittler** [comment]
This Google API JavaScript client library does support request batching; see the documentation here: https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiclientnewbatch

This library only works in web browsers and does not work with Node.js - see the list of supported environments here: https://developers.google.com/api-client-library/javascript/start/start-js#supported-environments

**Comment by spyeadon** [comment]
Thank you!
