### ISSUE TITLE
Google Signin Popup Language

### ISSUE THREAD

**Issue by rahatjaan** [google/google-api-javascript-client#308]
I am using the Google Javascript API to show Google Login Popup and authenticate user, using the following sample code and it works fine : 

https://developers.google.com/api-client-library/javascript/samples/samples

Issue is that i want to have this google login popup in Swedish language and i am unable to do that. Earlier when using gapi.auth.signIn() i was able to do that using the following script, but it DOES NOT work for the above sample code. 

window.___gcfg = {
        lang: 'sv-SE',
        parsetags: 'onload'
        };

Kindly help as its urgent. Thankyou!

**Comment by TMSCH** [comment]
@rahatjaan the Google Sign-In popup language is defined by the language of the user's main Google Account. Could you explain a bit more your use case? What if some of your users' main language is not Swedish?

**Comment by TMSCH** [comment]
Closing the issue, please reopen if it's still a problem for your use case.

**Comment by moshfeu** [comment]
Is this still the official answer? Because, in maps for example, you can set the map's language regardless of the user's language..

**Comment by nagaseshadri** [comment]
> @rahatjaan the Google Sign-In popup language is defined by the language of the user's main Google Account. Could you explain a bit more your use case? What if some of your users' main language is not Swedish?

But if popup is for the user to sign in (not yet logged in), How can it use the language defined in the users main google account ?

**Comment by moshfeu** [comment]
Maybe they're using a Cookie or localStorage?

**Comment by nagaseshadri** [comment]
But my implementation needs me to open it in the language that the user has already selected on our website and I think the requirement seems correct.

**Comment by moshfeu** [comment]
I agree that this should be the behaviour. It's working for Google maps..

**Comment by toastman** [comment]
Do we have solution for this ?
