### ISSUE TITLE
Auth and API calls for multiple users in a single session

### ISSUE THREAD

**Issue by cgilboy** [google/google-api-javascript-client#310]
Hello!

We would like to be able to authorize multiple accounts (for example, a user's home account and work account) and make API calls for both accounts in one session (for example, get a list of all contacts for both home and work). Is this supported? If so, what is the best way to accomplish this?

Thanks in advance!

**Comment by TMSCH** [comment]
Hi @cgilboy, this is not currently supported. You can potentially authorize several accounts, by using `gapi.auth2.authorize`, store locally the different `access_token`s received, and use `gapi.client.setToken` before each API call to set the specific user's `access_token`. Would that work?

However, it would not allow to easily fetch a fresh `access_token` when it expires. We are working on a solution to alleviate this issue though.

**Comment by cgilboy** [comment]
Hi @TMSCH, thanks for the quick response!

Your proposed solution (`gapi.auth2.authorize` multiple users and make requests w/ the resulting `access_token`) sounds like it would indeed work for our purposes. When the token expires, would we call `gapi.auth2.authorize` again with `prompt: none`? Are there other difficulties with refreshing the token?

Thanks!

**Comment by cgilboy** [comment]
Looking more closely, there does not appear to be a way to specify which access token/user to refresh with `gapi.auth2.authorize`. Is there another way to refresh a specific user/token?

**Comment by TMSCH** [comment]
@cgilboy you're right, this is not currently possible to refresh a specific token (but you're idea of calling `authorize` with `prompt: 'none'` is correct). We're already working on a solution to be able to do so, I will update this thread when it's deployed.

**Comment by cgilboy** [comment]
Great, thank you! In the meantime, can a refresh be accomplished via a direct HTTP request?

**Comment by TMSCH** [comment]
Without refresh token, unfortunately not.

**Comment by cgilboy** [comment]
Interesting! How does `gapi.auth2.authorize` accomplish refreshing without a refresh token?

**Comment by TMSCH** [comment]
The IFrame loaded by `gapi.auth2.authorize` is responsible for managing the token refresh, and does not provide the required data or mechanism to the client application, to avoid security issues.

**Comment by cgilboy** [comment]
Thanks for helping me understand this. If we want to make progress on supporting multiple users right now, is there a way we can use our server to refresh `access_token`s on behalf of the browser clients?

**Comment by TMSCH** [comment]
For now, if the token expires, you will have to use `gapi.auth2.authorize` with `prompt: 'select_account'` so the user can select the right account to get a token from. This is unfortunately not a good UX... It depends how long your users's sessions are. The token expires in 1 hour.

**Comment by cgilboy** [comment]
Thanks again. I see that it is possible for installed apps to refresh their access tokens:
https://developers.google.com/identity/protocols/OAuth2InstalledApp#offline

I realize that we would not want to let our browser client have access to our refresh token or client secret, but would it be possible to use our server as a proxy to make these refresh requests?

**Comment by TMSCH** [comment]
You can use the server side flow, i.e. Authentication Code exchange to get a refresh token in the server and use it to get fresh access tokens: https://developers.google.com/identity/sign-in/web/server-side-flow

**Comment by cgilboy** [comment]
Can the fresh access tokens that the server retrieves be sent to and used by the client to make calls to Google APIs? From the docs, I could not tell if those access tokens are only be meant to be used by the server.

**Comment by TMSCH** [comment]
Yes, they can.

**Comment by cgilboy** [comment]
Great. Thanks again for bearing with me!

**Comment by cgilboy** [comment]
Hi again,

We have implemented the server-side flow as described in the above document. We got an auth `code` by calling `grantOfflineAccess` on the client, but when the server calls `oauth2Client.getToken` (from the [nodejs lib](https://github.com/google/google-api-nodejs-client)) with the auth code or when we manually building a curl request to `https://www.googleapis.com/oauth2/v4/token`, we receive an `access_token` but not a `refresh_token` in return. Do you know if there’s currently any issue with the `grantOfflineAccess` call, or is there some other way to get a code that would be exchangeable for a `refresh_token`?

Thanks!

**Comment by TMSCH** [comment]
@cgilboy there should not be as far as I know. Could you paste:

```javascript
window.open = (function() {
    var open = window.open;
	return function(url) {
      console.log(url);
      return open.apply(window, arguments);
    };
})();
```

In the console, and start the sign-in flow (with the popup opening) and let me know the URL logged in the console?

**Comment by cgilboy** [comment]
@TMSCH My mistake! We did successfully receive the refresh token once when we initially ran the authorization flow. Once the app was already authorized, we only received an access token. I believe this behavior is consistent with the documentation. Thanks again for your help.

**Comment by TMSCH** [comment]
Great! Closing the issue.

**Comment by sodacode** [comment]
Is there a timeline of when an official solution will be available?

**Comment by TMSCH** [comment]
@sodacode could you be more specific? Are you looking for a solution to refresh a specific `access_token` without UI? (i.e. https://github.com/google/google-api-javascript-client/issues/310#issuecomment-309517122)

**Comment by ryanmcgary** [comment]
@TMSCH Is there an update for this statement? I would like to support multiple concurrent google accounts in a single session without having to use a server flow to grab the refresh token or requiring further user interactions after initially authorizing with the popup to confirm permissions. It appears you were working on a solution for this and were going to update this thread when it became available? Thanks you.

> @cgilboy you're right, this is not currently possible to refresh a specific token (but you're idea of calling `authorize` with `prompt: 'none'` is correct). We're already working on a solution to be able to do so, I will update this thread when it's deployed.

Again the original request was to: "authorize multiple accounts (for example, a user's home account and work account) and make API calls for both accounts in one session" without requiring an outside workflow.
