### ISSUE TITLE
Does Advanced usage support exchange auto code for refresh code?

### ISSUE THREAD

**Issue by lizho-ling** [google/google-api-javascript-client#311]
Hi,

I'm using gapi.auth2.authorize(params, callback) on client side to get auth code, we have to use advanced usage because there are 2 client ids in our web. **Goal** is: pass auth code to web server to exchange for access token and refresh token from Google server.
The parameters I'm using are:
    {
        'client_id': CLIENT_ID,
        'scope': SCOPE,
        'response_type': 'code permission', 
        'prompt': 'select_account',
        'cookie_policy': 'none',
        'include_granted_scopes': false,
      }

**The issue I met is**: when server uses auth code to exchange for refresh token and access token, only access token is returned from google server. refresh token is null.

There are such text under prompt: 'none' definition:
_If code is requested as response type, the code returned will only be exchangeable for an access_token, not a refresh_token._

So:
1) Does advanced usage support using authcode to exchange for both refresh code and access code?
2) Does above text only for prompt:'none', all for all advanced usages?

Appreciate your help! Thanks.

**Comment by TMSCH** [comment]
@lizho-ling this is surprising. Can you try using `response_type: 'code'`, without the `permission`? (I assume you don't need the ID token)

**Comment by lizho-ling** [comment]
I've tried to remove 'permission', still the refresh_code returned is null. Could you help check if advanced way supports exchange for refresh_code?

Thanks!

**Comment by TMSCH** [comment]
@lizho-ling when you authorize an user, are you going through the consent flow that's opened in a popup?

**Comment by lizho-ling** [comment]
Yes, I've gone through. 

I tried grantOfflineAccess to test if my server works well, with below piece of code, the google server replies back refresh token. So I am wondering where is wrong with the advanced usage?

  GoogleAuth.grantOfflineAccess({
      'redirect_uri': 'postmessage',
      'prompt': 'select_account',
    }

**Comment by TMSCH** [comment]
@lizho-ling it seems that you uncovered a bug. We are going investigate and update this thread when we it is fixed!

**Comment by lizho-ling** [comment]
Thanks!! Do you have any ideal when it will be fixed? We are blocked by this, appreciate your help!

**Comment by TMSCH** [comment]
@lizho-ling the fix for `gapi.auth2.authorize` should be live now. Let me know if that works!

**Comment by TMSCH** [comment]
Closing the issue. Please reopened if you still observe the bug.

**Comment by Jasemalsadi** [comment]
Hi @TMSCH  
I have exactly the same  issue and situation  of  @lizho-ling  and it still **not** giving the refresh token when synced the authorization code in the server side using fetchAccessTokenWithAuthCode method.
