### ISSUE TITLE
Using gapi.auth2 in Chrome extension

### ISSUE THREAD

**Issue by kospl** [google/google-api-javascript-client#312]
I am trying to migrate Chrome extension from gapi.auth to gapi.auth2:

```
gapi.auth2.init({
	client_id: CLIENT_ID,
	scope: 'https://www.googleapis.com/auth/drive.readonly',
	fetch_basic_profile: false,
	cookie_policy: 'none'
})
```

Gives an error:

Not a valid origin for the client: `chrome-extension://zzzzzz` has not been whitelisted for client ID xxxxxx.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID.

But as I use credentials for Application type: Chrome App, there's no way to specify authorized origin for my client ID.

Request for possible fix - make auth library 'generate' correct authorized origin for Application type: Chrome App based on `Application ID` value: https://chrome.google.com/webstore/detail/zzzzzz -> set `chrome-extension://zzzzzz` as authorized origin.

**Comment by TMSCH** [comment]
@kospl `gapi.auth2` does not support Chrome extensions, and the whitelisting problem is not the only issue preventing the library to work in Chrome extensions.

For Chrome extension, I would recommend using [chrome.identity](https://developer.chrome.com/apps/identity).

As an alternative, you could consider using [Firebase Auth](https://firebase.google.com/docs/auth/web/start).

**Comment by Sticksword** [comment]
Does this mean
```
gapi.client.init({
      apiKey: API_KEY,
      clientId: CLIENT_ID,
      discoveryDocs: DISCOVERY_DOCS,
      scope: SCOPES
    })
```
also wouldn't work? Are `gapi` and Chrome extensions still incompatible?

**Comment by hmalaud** [comment]
Curious about this too.

**Comment by rendomnet** [comment]
still not working?
