### ISSUE TITLE
Autocomplete return weird/inaccurate data for a specific place in Dubai

### ISSUE THREAD

**Issue by akafaneh** [google/google-api-javascript-client#315]
I'm using google maps JS/JQ with autocomplete search bar, it was working fine but when I enter 
"Ice Hockey Tower, Falak Properties - Dubai - United Arab Emirates" 
and on the listener 
"google.maps.event.addListener(autocomplete, 'place_changed', function ()"
i call the function 
"autocomplete.getPlace();"
and from the returned object I always used "formatted_Address" and lat(), long() functions to get coordinations and it always return the expected data but in this place it returns only "Dubai - United Arab Emirates" in formatted_Address and inaccurate lat and lng.
PS: I'm a developer in a shipping company so inaccuracy in coordinations get noticed fast.
Thanks,

**Comment by HDaghash** [comment]
this is happening with me as well

**Comment by asalem** [comment]
i do have the same issue

**Comment by TMSCH** [comment]
@akafaneh this is an issue related to the Maps JS library, please head to the [Support](https://developers.google.com/maps/documentation/javascript/support) section of their doc to find guidance on how to resolve this issue.
