### ISSUE TITLE
Cannot run gapi.client.init multiple times 

### ISSUE THREAD

**Issue by YoannKy** [google/google-api-javascript-client#316]
Hi there,

I'm currently working on a  angularJs dashboard composed of various widget.

The trouble I am facing is that when I call multiple widgets that use the gapi object, I end up with the following error (ie when I have connected to my gmail widget and I want to sign in to my calendar widget):

_"gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() **instead of gapi.auth2.init()**."_

But the documentation states the following thing about this method:

https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiclientinitargs

"**The gapi.client.init function can be run multiple times** , such as to set up more APIs, to change API key, or initialize OAuth lazily."

Unless I misunderstood, this means that I should be able to run this method more than once.

Could you please help me ? How should I handle widgets that require to init the gapi client with specific client-id and discovery-doc ?  

Thanks in advance for your help.

Below is a sample of my code, this is part of the directive used my calendar widget, but **it the same code (except for the final request, upon requesting specific informations) that the gmail one** (maybe this is the reason my widgets cannot work together):

```
//this function is called upon my directive has been loaded up
function handleClientLoad() {
    var loadGapiClient = new Promise(function(resolve) {
        gapi.load('client:auth2', resolve);
   });

   loadGapiClient
        .then(() => {
            //once the cient has been loaded, I can display and link my sign in button to the function that will handle the auth
            $scope.handleAuthClick = handleAuthClick;
            $scope.handleSignoutClick = handleSignoutClick;
            $scope.hide = false;
        });
}

//this is the function called when the user wants to sign in
function handleAuthClick() {
    initClient();
}

//this is the function that call the gapi.client.init with the CLIENT_ID, SCOPES  and DISCOVERY_DOCS that my widget is asking for
function initClient() {
    const CLIENT_ID = 'my-client-id';
    const DISCOVERY_DOCS = ['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest'];
    const SCOPES = 'https://www.googleapis.com/auth/calendar.readonly';

    //this is where the gapi throws an error
    gapi
        .client
        .init({
            discoveryDocs: DISCOVERY_DOCS,
            clientId: CLIENT_ID,
            scope: SCOPES
        })
    .then(handleRequest, handleError);
}
```

**Comment by TMSCH** [comment]
Hi @YoannKy,

The documentation is indeed misleading. `gapi.client.init` can indeed be called multiple times, *unless `clientId` and `scope` are specified*. This is due to the fact that specifying these two parameters will initialize `gapi.auth2` under the hood, and it can only be initialized once.

One alternative is to initialize `gapi.client` and `gapi.auth2` independently:

```javascript
gapi.client.init({
  discoveryDocs: DISCOVERY_DOCS
}).then(() => {
  gapi.auth2.init({
    client_id: CLIENT_ID,
    scope: SCOPES
  }).then(callback);
});
```

(notice the different format of the parameters names).

This way you will be able to initialize `gapi.client` several times with different discovery doc.

If you wish to change the `client_id` used by `gapi.auth2`, you cannot use `gapi.auth2.init`. You should use [gapi.auth2.authorize](https://devsite.googleplex.com/identity/sign-in/web/reference#advanced) which allows a different `client_id` for each request. After each successful call to `gapi.auth2.authorize`, the subsequent requests performed through `gapi.client` will use the `access_token` of the lastly authorized account.

Let me know if that helps!

**Comment by YoannKy** [comment]
Hey @TMSCH,

Thank you for answering me.

It worked, but I had to handle the process a bit differently. This may be wrong though.
Indeed, as the doc said:

https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2authorizeparams-callback

I had to get rid off everyting that concerns gapi.auth2.init/signIn.


But I have another problem, I would like to bypass the sign in button if the access_token is still valid (as it  is stated below, I have stored the access_token in the localStorage, this is a way to check if the user is signed in).

So when it is the case, I'm calling the following property in the  gapi.auth2.authorize method:  
**PROMPT : 'none'.** 

 This worked for the calendar widget but the gmail one fails.

 I'm currently doing 2 calls to the gapi.client.gmail

 One to retrieve the user's mails, and another one that I use to get the details of each mail. 

 The first call that use  **gapi.client.gmail.users.messages.list** is working, 
 but the second one  that use **gapi.client.gmail.users.messages.get** **sometimes**  returns the following error **when I refresh my dashboard multiple times**:

```
 "{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}
"
```
the scope used is "**https://www.googleapis.com/auth/gmail.readonly**", but this should not be the problem since **my widget works without the prompt : 'none' property**

Do you have any idea where it could come from ? Maybe this comes from the way I'm handling the auth2.authorize, and I'm missing an important step

A sample of my code can be seen belowed:
```


// the initClient function now only init the gapi.client with the discoveryDocs
// and then set the client_id and the scopes in handleNewAuth2 function
function initClient() {
      gapi
        .client
        .init({
            discoveryDocs: DISCOVERY_DOCS,
        })
        .then(handleNewAuth2, handleError)
        .then(handleRequest, handleError);
}

//the function that handle the auth2 settings
// I have a flag that allows to check if the access_token is still valid 
// (I'm currently storing it in the localStorage each time the widget has been loaded, I'm checking if expires_at is still valid)
// So isAcessTokenValid is a flag that check expires_at.
function handleNewAuth2() {
    $scope.signIn = false;
    return new Promise((resolve,reject) => {
        let parameters = {
            client_id: CLIENT_ID,
            scope: SCOPES,
            prompt : CONSENT_PROMPT
        };
        if (isAcessTokenValid) {
            parameters.prompt = NO_PROMPT;
        }
        gapi
            .auth2
            .authorize(parameters, (response) => {
                if (response.error) {
                    reject("unexpected error from gapi, check the parameters");
                }
                $scope.signIn = true;
                resolve(response);
            });
    });
}
```

**Comment by TMSCH** [comment]
I would recommend calling `gapi.auth2.authorize` with `prompt: 'none'` instead of storing the `access_token` locally, as the library already takes care of storing it locally and will automatically fetch a new one if it expired, or use the cached one.

One thing: you cannot call call `gapi.auth2.authorize` **without** `prompt: 'none'` after a promise's resolution. Most browsers will block the popup. You need to display a button, and trigger the call after the user clicks it.

Are the two calls to GMail APi chained? Could you post the full snippet that I could use to reproduce the issue?

**Comment by YoannKy** [comment]
I wanted to do that but  the 'none' option states the following thing:

> The authorization server will not display any authentication or user consent screens; it will return an error if the user is not already authenticated and has not previously consented to the requested scopes.
This means that it will throw an error the first time, right ?



> One thing: you cannot call call gapi.auth2.authorize without prompt: 'none' after a promise's resolution. Most browsers will block the popup. You need to display a button, and trigger the call after the user clicks it.

Not sure if we are talking about the same thing but I have a sign in button that trigers my initClient() the first time (no access_token stored yet).
What  I want is a way to keep the user logged in without having to display the sign In button.

Well, once I have retrieved the list of mails, I'm looping through them and then I'm creating a promise for each of them. It is used with angularJS but I think it is possible to extract the business logic out of it.

```

  function getMessages() {
              let promises = [];
              $scope.messages = [];
              $scope.hide = true;
              gapi
                  .client
                  .gmail
                  .users
                  .messages
                  .list({
                      'userId': 'me',
                      'maxResults' : 15
                  })  
                  .then((response) => {
                      if (response.status === 200) {
                         for (var message of response.result.messages) {
                              promises.push(new Promise((resolve) => {
                                  resolve(getMessage(message));
                              }));
                         }
                      }
                      Promise
                          .all(promises)
                          .then(() => {
                              $scope.hide = false;
                          });
                  });
         }

          function getMessage(message) {
              gapi
                  .client
                  .gmail
                  .users
                  .messages
                  .get({
                      'userId': 'me',
                      'id' : message.id
                  })
                  .then((response) => {
                      if (response.status === 200) {
                          let messageObj = {
                              snippet : response.result.snippet,
                              id : response.result.id,
                              title : response.result.payload.headers.find(( obj ) => {
                                  return obj.name === "Subject";
                              }).value,
                              from : response.result.payload.headers.find(function( obj ) {
                                  return obj.name === "From";
                              }).value.replace(/<(.*?)>/, '').trim(),
                              dest : response.result.payload.headers.find(function( obj ) {
                                  return obj.name === "To";
                              }).value.replace(/<(.*?)>/, '').trim(),
                              date : response.result.payload.headers.find(function( obj ) {
                                  return obj.name === "Date";
                              }).value.substr(0,7)
                          };
                          $scope.messages.push(messageObj);
                      }
                  });
          }
```

**Comment by YoannKy** [comment]
One thing to mention, is that the 403 error code only occurs when both widgets use the prompt : 'none' property  upon loading my dashboard. So this is from my code, but I don't know where.

**Comment by YoannKy** [comment]
Just an update, I think that I found out the problem, it is because both my widgets are loaded asynchronously therefore, I can't control the flow of the gapi request, since there are two cases:

- The gmail widget  fetches and resolves the gapi data **before** the calendar one: in this case there is no problem, the same access_token is used for the gmail application

- the gmail widget doesn't fetch && resolve fast enought:  the first call is successfully resolved, but **before** the second call is made, **the calendar widget is loaded and triggers the auth2.authorize**.
Therefore **the current access_token used for the gmail application is erased by the calendar one**.
And as a result, when the second call is made, it returns me a 403 because the access_token does not hold the permission asked by the gmail api.

That's just a hypothesis, but since I have no problem when only one widget is automatically loaded with prompt : 'none proprety, that could explain it.

So I either need to find a way to load my widget one by one, or to tell one widget that uses the gapi object to wait for the other widget  that was the first one to use the gapi object  to resolves.

**Comment by YoannKy** [comment]
Alright, it's me again, I resolved the problem yesterday by  manually setting the accessToken, that I stored in the localStorage after a call at auth2.authorize, for my widget before doing the call to the api like so:


       ```
     Promise
                .resolve(gapi.client.setToken({
                    access_token : accessToken
                }))
               .then(() => {
                     //my api call
               })
```

It's quite dirty but it did the trick.

**Comment by TMSCH** [comment]
@YoannKy glad you resolved the issue. Are the two `gapi.auth2.authorize` calls using different scopes? By default, the call should return an `access_token` with all the already granted scopes (unless `include_granted_scopes: false` is given), so the second call in your case should hold the permission for the gmail api. If it doesn't, it sounds like a bug.

**Comment by YoannKy** [comment]
@TMSCH , yes the 2 calls are querying diffrent scopes, the drive one uses: _https://www.googleapis.com/auth/calendar.readonly_ 
whereas the gmail one uses: 
 _https://www.googleapis.com/auth/gmail.readonly_  . 

Well I didn't set the` include_granted_scope ` parameter so it should be true by default. 

 But I don't think it is the problem here since my 2 apps (drive and gmail) are using **differents client_id** . 
If I understand ` include_granted_scopes` only keeps a track of the previous granted_scopes for a specific app.  

If my 2 apps were using the same client_id, in that case yes that would be a bug I guess.

**Comment by TMSCH** [comment]
Ah you're right I didn't realize the `client_id` was different. In that case, you should indeed manage the different `access_token`s yourself as `gapi.client` will only use the last one obtained otherwise.

**Comment by YoannKy** [comment]
Yeah, but thanks again for your help. it was really helpful. 👌

**Comment by TMSCH** [comment]
You're welcome!

**Comment by sudipstha08** [comment]
I am getting this error in next js. Am i doing sth wrong ?

```js
const loadClient = async () => {
    try {
      setLoading(true)
      await window["gapi"]?.client.setApiKey(API_KEY)
      await window["gapi"].client.load(
        "https://content.googleapis.com/discovery/v1/apis/calendar/v3/rest",
        "v3"
      )
      setLoading(false)
    } catch (err) {
      setLoading(false)
    }
  }
```

```js
const isSignedIn = window["gapi"]?.auth2?.getAuthInstance()?.isSignedIn?.get()

 useEffect(() => {
    window["gapi"]?.load("client:auth2", async () => {
      try {
        setLoading(true)
        if (!isSignedIn) {
          await window["gapi"]?.auth2.init({
            client_id: CLIENT_ID,
            scope: scope,
          })
          await loadClient()
        }
        setLoading(false)
      } catch (err) {
        setLoading(false)
      }
    })
  }, [])
```
