### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by o0alexela0o** [google/google-api-javascript-client#317]
Hello, sorry to write here, but I cannot find any doc on this
Is there an error callback for gapi?
for 404 browser errors?

Thanks in advance!

**Comment by o0alexela0o** [comment]
example:
gapi.loaded
"API discovery response missing required fields."

**Comment by TMSCH** [comment]
Could you be more specific? What call raises the error?

**Comment by o0alexela0o** [comment]
If i have wrong settings i'm getting this error:

(backbone code)

        this.settings = {
            client_id: "1052423475-mcp4khpg5h01tvo3a58cbv2pu044obai.apps.googleusercontent.com",
            redirect_uris: ["http://localhost:8000"],
            discovery_docs: ['https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'],
            scope: 'https://www.googleapis.com/auth/drive.readonly',
        };
        this.gapi.load('client:auth2', function(){
            var self = this;
            this.gapi.client.init({
                discoveryDocs: this.settings.discovery_docs,
                clientId: this.settings.client_id,
                scope: this.settings.scope
            }).then(function(){
                gapi.client.drive.files.list({
                    'q'         :"'0B3vR4cBcxn4odVNTa0VjSmNab3M' in parents", 
                    'pageSize'  : 80,
                    'fields'    : "nextPageToken, files(id, name, imageMediaMetadata, webContentLink, mimeType, folderColorRgb, modifiedTime)"
                }).then(function(respo){
                    var files = respo.result.files;
                    // var files = respo;
                    console.log(files);
                }, function(error){
                    switch(error.status){
                        case 403:
                            console.log('this was error 403');
                            self.gapi.auth2.getAuthInstance().signIn();
                        break;
                        case 404:
                            console.log('this is error 404');
                        break;
                        default:
                            console.log('errror ' + error.result.error.code + '. ' + error.result.error.message);
                        // location.reload();
                    }
                })
            });
            })

i cannot get errors of gapi.loaded
other errors of  init i managet to handle

**Comment by TMSCH** [comment]
Try replacing:

```javascript
this.gapi.load('client:auth2', function(){
        var self = this;
        this.gapi.client.init({
            discoveryDocs: this.settings.discovery_docs,
            clientId: this.settings.client_id,
            scope: this.settings.scope
        })
```

by

```javascript
var self = this;
this.gapi.load('client:auth2', function(){
        self.gapi.client.init({
            discoveryDocs: self.settings.discovery_docs,
            clientId: self.settings.client_id,
            scope: self.settings.scope
        })
```

And are you saying that you can't capture errors for `gapi.load`? I don't know what gapi.loaded.

**Comment by o0alexela0o** [comment]
No, this is not a problem.
Errors from requests i can get by:

```
, function(error){
                switch(error.status){
                    case 403:
                        console.log('this was error 403');
                        self.gapi.auth2.getAuthInstance().signIn();
                    break;
                    case 404:
                        console.log('this is error 404');
                    break;
                    default:
                        console.log('errror ' + error.result.error.code + '. ' + error.result.error.message);
                    // location.reload();
                }
            })
```

what i cannot get is errors in init itself.
for example - if one of the setting values is wrong, i'm getting an error:

![screen shot 2017-07-11 at 22 50 29](https://user-images.githubusercontent.com/4036612/28160946-652e0312-67ca-11e7-9b1b-4e4a8023c14b.png)

**Comment by bochunz** [comment]
Did you get a non-200 response for the request to `https://content.googleapis.com/discovery/v1/apis/drive/v3/rest` ?

**Comment by o0alexela0o** [comment]
Yes, 404 to be precise

**Comment by bochunz** [comment]
This is probably an internet connectivity problem. Please direct your question to Google Drive API's support at https://developers.google.com/drive/v3/web/support

**Comment by o0alexela0o** [comment]
its not, it's wrong address of another setting which gapi.init uses.
but ill try. thanks

**Comment by o0alexela0o** [comment]
found solution for this:
error handeling is pretty good:

for example:
