### ISSUE TITLE
Library maintenance?

### ISSUE THREAD

**Issue by bootstraponline** [google/google-api-javascript-client#320]
Is this client in `Library maintenance` mode as well? It looks like most of the `google-api-*-client` projects have been marked as such.

- https://github.com/google/google-api-ruby-client/pull/597

**Comment by bsittler** [comment]
No. https://cloud.google.com/apis/docs/cloud-client-libraries does not list a browser-targeted JavaScript client library (though there is one for Node.js https://github.com/GoogleCloudPlatform/google-cloud-node / https://googlecloudplatform.github.io/google-cloud-node/ ) and so for this platform the Google API Client Library (this one) is used instead; see https://developers.google.com/api-client-library/ and specifically https://developers.google.com/api-client-library/javascript/
