### ISSUE TITLE
gapi.load() documentation

### ISSUE THREAD

**Issue by shermanyin** [google/google-api-javascript-client#321]
I'm new to javascript / gapi.  While looking at samples, gapi.load() is used in many examples, but doesn't seem to have proper documentation (unlike gapi.client.load() here https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiclientloadurlorobject, for example).  It would be nice if that was added.

**Comment by TMSCH** [comment]
@shermanyin that's a very good point. I think mentioning in it in gapi.client and gapi.auth2 documentation would help. We will address this.

**Comment by TMSCH** [comment]
@shermanyin we added documentation: https://developers.google.com/api-client-library/javascript/reference/referencedocs?hl=en#gapiloadlibraries-callbackorconfig

**Comment by shermanyin** [comment]
@TMSCH I see the docs, thanks!.
