### ISSUE TITLE
GoogleAuth.grantOfflineAccess doesn't work

### ISSUE THREAD

**Issue by atsuya** [google/google-api-javascript-client#322]
Hi team,

Description:
GoogleAuth.grantOfflineAccess doesn't work. The popup shows up and the flow goes normal until I click on "Allow" button. After clicking on the "Allow" button, it doesn't close its window nor go back to the original page that triggered the popup to show.

It won't get into the same issue when I do authentication without  GoogleAuth.grantOfflineAccess  (I just render the sign in button).

Note that the browser consumes 100% CPU after the click (probably stuck in infinite loop). I observe the same behavior with Chrome and Firefox on Linux.

Environment:
Arch Linux: Linux 4.9.37-1-lts SMP x86_64 GNU/Linux
Chrome Version 59.0.3071.115 (Official Build) (64-bit) 
Firefox 54.0.1 (64-bit)

Let me know if you need any other info.

Thanks!

**Comment by atsuya** [comment]
I should clarify that it was working before, and it stopped working a couple of days ago.

**Comment by TMSCH** [comment]
@atsuya I am not able to reproduce the issue. Could you post the snippet of code that reproduces it, with the configuration given?

**Comment by atsuya** [comment]
@TMSCH Thanks for taking a look at this case. I just tried it myself today again and it seems like it's working. I haven't changed my code so I suppose it's fixed on Google end. Anyhow, thanks!

**Comment by TMSCH** [comment]
Glad it's working now!

**Comment by atsuya** [comment]
FYI, it was my code that was causing the issue. I did have an infinite loop 😢

**Comment by TMSCH** [comment]
Ah great, that makes sense. We hadn't made any change to Google Sign-In library so I was puzzled by this temporary issue ;)

**Comment by saasforge** [comment]
I experience the same problem. It works in FF but not in Chrome. In Chrome the popup is showing "Success" screen but never closed and never calls the callback. The code is:

```javascript
        this.googleAuth.grantOfflineAccess().then(function(data){
              // Handle data.code
        });
```

Chrome:
Version 79.0.3945.117 (Official Build) (64-bit)
