### ISSUE TITLE
Sign in from Google Drive mobile

### ISSUE THREAD

**Issue by ivmartel** [google/google-api-javascript-client#324]
Hi, I'm trying to use this API and the Google Drive API to log in and display information contained in DICOM (*.dcm) files stored on Google Drive. The sign in works fine from a desktop browser but fails from the mobile app (v2.7.252.04.33 from 28 Jun 2017) complaining that `sessionStorage is not available in the current the environment` (error: `idpiframe_initialization_failed`). 

How would you advise to sign in for that environment?

Just in case, the code is in the [dwvgapi](https://github.com/ivmartel/dwvgapi) github repo and its associated chrome extension is [dwvgapi](https://chrome.google.com/webstore/detail/dwvgapi/ojifemdgjdehgnaakiohfjcgjjajlama).

**Comment by TMSCH** [comment]
HI @ivmartel, please provide more information on the device used, OS version, and browser used.

**Comment by ivmartel** [comment]
It's an Android 6.0 device. It has Google Chrome 59.0.3071.125 installed but I do not know if this is what the Google Drive app uses.

I forgot to mention that the error is triggered when calling the `gapi.client.init` in [dwvgapi google.js#L71](https://github.com/ivmartel/dwvgapi/blob/master/src/google.js#L71).

**Comment by TMSCH** [comment]
This error can be raised when web storage are disabled. We observed that to happen on iOS devices with Chrome in Incognito mode, or Chrome with third party data blocked (on any device). Would you have set any specific configuration such as incognito mode or third part data blocked in Chrome?

**Comment by bsittler** [comment]
This is in the Android Google Drive App, correct? If so, it's probably using a WebView and that is not a supported environment for this client library

**Comment by ivmartel** [comment]
Yes, it is the Android Google Drive App. I did not set any specific configuration, just the basic install. 

Ok for the not supported, would you know of another solution?

**Comment by bsittler** [comment]
That's a question about the Google Drive app, and I don't know what auth mechanisms are supported/recommended/possible for it, if any. I recommend finding the appropriate forum and asking there &mdash; unfortunately, I don't know which forum that would be

Closing this as the usage is not supported

**Comment by ivmartel** [comment]
Ok, I asked on stackoverflow: [sign-in-from-google-drive-android-app](https://stackoverflow.com/questions/45325007/sign-in-from-google-drive-android-app)
