### ISSUE TITLE
Is there a discoverydoc available for Youtube Content Id APIs to use in the Javascript

### ISSUE THREAD

**Issue by nagendrabhamidipati** [google/google-api-javascript-client#326]
Hi 

Is there a discovery doc available for YouTube Content Id API? I am trying to write a JavaScript client that calls the YouTube Content ID API to retrieve claims information. I tried different approaches for the discovery docs. But none of them worked and when I use https://www.googleapis.com/discovery/v1/apis/youtube/partner/v1/rest, I am getting error "API Discovery Response missing required fields".

Regards
Nagendra

**Comment by bsittler** [comment]
I'm not knowledgeable about that API, but I believe you may have a typo in that URL. Does it work if you spell it like this?

https://www.googleapis.com/discovery/v1/apis/youtubePartner/v1/rest

**Comment by bsittler** [comment]
Closing as this is not the right issue tracker for that API
