### ISSUE TITLE
Popup closed/blocked after grantOfflineAccess()

### ISSUE THREAD

**Issue by serkolch** [google/google-api-javascript-client#331]
I have GoogleSignIn in a React component. I'm trying to grant offlineAccess so that I can pull the auth_code out in the corresponding callback/promise. However, I inconsistently get either 'pop_upblocked_by_browser' or more usually 'popup_closed_by_user'.

I initialize as

```javascript
gapi.load('auth2', () => {
	service.auth2 = gapi.auth2.init({
		client_id: `${googleSignInID}.apps.googleusercontent.com`,
	});
});
```

In the React component, I attach the click handler in componentDidMount

```javascript
componentDidMount () {
	service.auth2.attachClickHandler(
		this.button, // ref
		{}, // options
		service.googleSignUp, // success
		this.setProcessingToFalse // failure
	);
}
```

In my service, the success function is:

```javascript
static googleSingup (googleUser) {
	gapi.auth2
		.getAuthInstance()
		.grantOfflineAccess()
		.then(data => {
			console.log(data)
		})
}
```

No matter any changes I've tried (passing in an object to grantOfflineAccess, using the googleUser response instead of gapi.auth2, etc) I'm unable to get the 'pop-up' to work correctly. 

The flow seems correct based on documentation and other threads and the UI seems intuitive (user clicks button on site, another tab opens with the google accounts, choose an account, the tab closes and user is directed back to site). The pop-up closes on it's own, so it's weird that the error says 'popup_closed_by_user. The one time it seemed to work, after choosing an account, it re-opened the popup, I chose the same account, and the console.log printed the data.

**Comment by TMSCH** [comment]
Hi @serkolch, the current implementation has issues. `auth2.attachClickHandler` already handles the logic of starting the sign in flow. What happens here is this:

1. User clicks button.
2. `attachClickHandler` internals calls `GoogleAuth.signIn`. This opens a popup to the consent flow.
3. User signs in successfully.
4. The callback `service.googleSignUp` is called.
5. This triggers the `grantOfflineAccess` method, which opens a new popup to the consent flow: however, as it is triggered asynchronously and not synchronously after a user interaction, this will most of the time be blocked by the user. Hence the `popup_blocked_by_browser` issue.

You should manually attach a `'click'` event listener to your button and call the `googleSignUp` method from it. The `attachClickHandler` is meant to get `id_token` and `access_token`, not `code` as in `grantOfflineAccess`.

**Comment by serkolch** [comment]
@TMSCH 
Thanks for letting me know! That frankenstein flow I created is what happens when you just desperately stackOverflow to get answers.

So if I do grantOfflineAccess() to get the code, can I get profile information with it? I tried passing `{ scope: 'profile email' }` into grantOfflineAccess(), but it still only returned the code. And I suppose I can't combine both grantOfflineAccess() and signIn().

**Comment by TMSCH** [comment]
@serkolch you cannot get the profile information from the client if you use `grantOfflineAccess`. You would have to pass the code back to the backend, exchange it, and then call Google APIs to get the user's information.

However you could use [`gapi.auth2.authorize`](https://developers.google.com/identity/sign-in/web/reference#advanced) and pass `response_type: 'id_token code'` as well as `scope: 'email profile openid'`. You can then unpack the `id_token` returned, it's a [JWT](https://jwt.io/) that will contain the user's basic profile information.

Would that work?

**Comment by serkolch** [comment]
@TMSCH Hmmm, I did have that before, but it didn't seem to work as intended with an existing BE implementation for an Android app (which is able to get a serverAuthCode and profile information in one call, unless it's just abstracted and it appears to be one call to me).

Seems to me that I just can't integrate with the BE as is - to me it seems that it should only ask for the authorization code and then it can exchange the code and generate profile information. Guess we just need to overhaul the BE to handle web and Android authentication.

Unless you have anything you want to add, you can close this thread. Thanks again!

**Comment by TMSCH** [comment]
@serkolch An OAuth 2.0 flow will not return the profile information as part of the first step of the *Authorization Code flow*. It may return it once you exchange the code for an access_token. Otherwise your backend most certainly was performing another call, using the `access_token`, to get the profile information.

**Comment by billinghamj** [comment]
This seems like a bit of an oversight. You can do this on the iOS and Android clients:

- https://developers.google.com/identity/sign-in/ios/offline-access
- https://developers.google.com/identity/sign-in/android/offline-access

Where the client-side authentication is achieved via a standard implicit OAuth authorisation, but additionally an authorisation code is provided for use server-side.

I'd really like to achieve this with the JS client too. Is this actually possible?

**Comment by TMSCH** [comment]
@billinghamj could you explain what you want to achieve? In the Android and iOS examples, the profile information is only retrieved after the code is exchanged for tokens. There is also a sign in step, then the code is fetched, and finally it is exchanged for tokens.

**Comment by billinghamj** [comment]
@TMSCH I don't think that's true. It gives you this object: https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_google_user

Which contains _both_ a direct access token for immediate client-side use (without doing a server-side exchange), **and** an authorization code for server-side use. You set two client IDs - one for the client, one for the server.

```objc
[GIDSignIn sharedInstance].clientID = @"APP_CLIENT_ID";
[GIDSignIn sharedInstance].serverClientID = @"SERVER_CLIENT_ID";

- (void)signIn:(GIDSignIn *)signIn didSignInForUser:(GIDGoogleUser *)user withError:(NSError *)error
{
  NSLog("%@", user.authentication.accessToken); // access token for direct use with APIs
  NSLog("%@", user.authentication.idToken); // OpenID Connect token
  NSLog("%@", user.serverAuthCode); // authorization code for server-side exchange
}
```

I recognise that there may be something additional going on internally (can't tell, as the code is all closed source), but this is what I'm looking to achieve with the JS client.

**Comment by TMSCH** [comment]
You can use [`gapi.auth2.authorize`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams-callback) requesting `id_token code` as `response_type`. The `id_token` is a [JWT](https://jwt.io/) containing the user's profile information. If you're using the `code` in the backend, you shouldn't need to fetch an `access_token` in the client, that'd be redundant.

**Comment by billinghamj** [comment]
The access token is for making client-side requests, etc. - as the server provide an access token back and doesn’t make requests on behalf of the client.

That being said, the profile data in the JWT will probably be sufficient for the specific use-case

**Comment by TMSCH** [comment]
My point is that you should not need both a client-side access token and an offline code. If you're making client side API requests only, use the `gapi.auth2` library to get fresh access tokens. If you're doing server side API requests only, use an offline code. If you're doing both, be careful, and use an offline code that once exchanged for a refresh_token can be used to fetch fresh access token and sent to the client. But doing API requests both from the client and the server isn't recommended.

**Comment by billinghamj** [comment]
To be honest, I don’t think there is any legitimate reason that that isn’t recommended - particularly as it is directly supported on the iOS and Android clients. In the age of single page apps, where largely the client is a full application of its own, and the server-side API is client-independent, this is a very common use-case.

**Comment by TMSCH** [comment]
That's exactly my point: if you consider your server-side API client-independent, then you should not store refresh_token in your backend, it's contrary to the client-independence. Native apps are different, they exchange the code from within the client directly.

**Comment by billinghamj** [comment]
Okay, for anyone else who sees this, wondering how you can actually make it happen, it's pretty simple:

```js
gapi.auth2.authorize({
	client_id: 'CLIENT_ID_HERE.apps.googleusercontent.com',
	scope: 'email profile openid',
	response_type: 'id_token token code',
}, response => {
	if (response.error) {
		console.warn(response);

		return;
	}

	console.log(response);
});
```

Within `response_type`:

- `code` provides a OAuth 2 authorization code (for server-side token exchange)
- `id_token` provides an OpenID Connect JWT (can be used client-side or server-side)
- `token` provides an OAuth 2 access token (for calling APIs directly on the client-side)

**Comment by OdifYltsaeb** [comment]
I suddenly started getting this error from out of the blue:
My code is really simple and I did not change anything there in couple of days and it worked couple of days ago:

```
    const signUp = e => {
        if (e) {
            e.preventDefault();
        }
        if (!disabled) {
            const GAuth = window.gapi.auth2.getAuthInstance();
            const options = {
                prompt: '',
            };
            GAuth.grantOfflineAccess(options).then(
                res => {
                    const data = {
                        provider: 'google-oauth2',
                        code: res.code,
                        redirect_uri: 'http://localhost:8000',
                    };
                    getJWT(data, next);
                },
                err => {
                    console.log('SIGN IN ERROR', err);
                },
            );
        }
    };
```
