### ISSUE TITLE
gapi.client.init() promise fails silently, No Error, No warning  

### ISSUE THREAD

**Issue by sbsusant** [google/google-api-javascript-client#334]
I am using this for Google drive upload for a Cordova project and successful on browser platform. But it does not work in Cordova android web view. I am using Genymotion for Emulation and my code is below:
        

var CLIENT_ID = 'xxxxxxxxxxxx.apps.googleusercontent.com';
	var DISCOVERY_DOCS = ["https://www.googleapis.com/discovery/v1/apis/drive/v3/rest"];
	var SCOPES = 'https://www.googleapis.com/auth/drive';
	
	var GoogleAuth, GoogleAuthResp;
	var isAuthorized = false;
	var currentApiRequest;
	
	var scriptEl = document.createElement('script')
	document.body.appendChild(scriptEl);
	scriptEl.setAttribute("type","text/javascript");
	scriptEl.setAttribute("async","");
	scriptEl.setAttribute("defer","");
	scriptEl.setAttribute("src", "https://apis.google.com/js/api.js");
	scriptEl.onload = handleClientLoad;
	scriptEl.onreadystatechange = function () {
		if (this.readyState == 'complete' || this.readyState == 'loaded') {
			this.onload();
		}
	};
	
	
	var authorizeButton = document.getElementById('authorize-button');
	var signoutButton = document.getElementById('signout-button');	
	
	function handleClientLoad(){
		gapi.load('client:auth2', initClient);
	}
	
	function initClient(){
		gapi.client.init({			
			'discoveryDocs': DISCOVERY_DOCS,
			'clientId': CLIENT_ID,
			'scope': SCOPES
		}).then(function(){			
			GoogleAuth = gapi.auth2.getAuthInstance();
			GoogleAuth.isSignedIn.listen(updateSigninStatus);
		
			console.log(GoogleAuth.currentUser.get().hasGrantedScopes(SCOPES));
			
			updateSigninStatus(gapi.auth2.getAuthInstance().isSignedIn.get());			
			//=============
			authorizeButton.onclick = handleSignIn;
			signoutButton.onclick = handleSignout;
		},function(error){
			console.log(error);
		});
	}
	
	function sendAuthorizedApiRequest(requestDetails) {
		currentApiRequest = requestDetails;
		if (isAuthorized) {
			//gapi.client.request(requestDetails)
			// Reset currentApiRequest variable.
			currentApiRequest = {};
		} else {
			GoogleAuth.signIn();
		}
	}
	
	function updateSigninStatus(isSignedIn) {
		if (isSignedIn) {
			isAuthorized = true;
			if (currentApiRequest) {
				sendAuthorizedApiRequest(currentApiRequest);
			}
			authorizeButton.style.display = 'none';
			signoutButton.style.display = 'block';
			
		} else {
			isAuthorized = false;
			
			authorizeButton.style.display = 'block';
			signoutButton.style.display = 'none';
		}
	}
	
	function handleSignIn(e) {
		GoogleAuth.signIn();
	}
	function handleSignout(e) {
		GoogleAuth.signOut();
	}
	function uploadFile(imgUri){
		var file = util.dataURItoBlob(imgUri);
		
		----------
	}

Also i noticed in the network console "Caution: Provisional headers are shown"

**Comment by bsittler** [comment]
Cordova apps (and other webviews) are not supported by gapi.client.

From [https://developers.google.com/api-client-library/javascript/start/start-js#supported-environments](https://developers.google.com/api-client-library/javascript/start/start-js#supported-environments) :

>  It only works within HTML documents with a `<body>` element served using the `https` *(preferred)* and `http` protocols.

**Comment by sbsusant** [comment]
Thanks for your reply.

**Comment by Birowsky** [comment]
But cordova can serve sites through a localhost server. Also user can be authenticated to google through this plugin: 

https://github.com/EddyVerbruggen/cordova-plugin-googleplus

And obtain these credentials:

```
 obj.email          // 'eddyverbruggen@gmail.com'
 obj.userId         // user id
 obj.displayName    // 'Eddy Verbruggen'
 obj.familyName     // 'Verbruggen'
 obj.givenName      // 'Eddy'
 obj.imageUrl       // 'http://link-to-my-profilepic.google.com'
 obj.idToken        // idToken that can be exchanged to verify user identity.
 obj.serverAuthCode // Auth code that can be exchanged for an access token and refresh token for offline access
 obj.accessToken    // OAuth2 access token
```
