### ISSUE TITLE
Google Drive drive.files.create path

### ISSUE THREAD

**Issue by jamierytlewski** [google/google-api-javascript-client#336]
How come the path for google drive with drive.files.create won't change with the JavaScript API? 

If I look here: 

https://www.googleapis.com/discovery/v1/apis/drive/v3/rest

When you use create the path should switch. Is it mandatory that if you are using JavaScript/client-side that you must use CORS? 

I see [here](https://developers.google.com/api-client-library/javascript/start/start-js#option-3-use-cors) it says you should use CORS, but not that it's mandatory. 

I was really hoping to be able to pass in parameters similar to Node.js and have it work in the browser, but that doesn't seem to work. The reason I was hoping this way is that if I change the discovery API hopefully other things won't change much. 

Thanks!

**Comment by bochunz** [comment]
This JavaScript library for browser is written differently from the Node.js library. The two libraries don't have any relationship.
