### ISSUE TITLE
checkSessionState does not work when loading prototype.js 1.6.x

### ISSUE THREAD

**Issue by nahtemf** [google/google-api-javascript-client#337]
If you load prototype.js 1.6.x and execute gapi.auth.checkSessionState, the browser will become unresponsive.

It was working until last week, but it stopped working since yesterday.

The process of escaping the character "check_session_state" with the gsub function of prototype.js looped
> "\ \" \\\\\\ "\\\\\\\\\\\\\\" \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ \\\\\\\ "check_session_state \\\\\\\\\\\\\\\\\\\\\\\\\\\\" \\\\\\\\\\ "\ \ \ \ "\ \ \ \ \ \" \ \ "" "

Attaching the snippet below

```
<html><head>
<title>checkSessionState Example</title>
<script type="text/javascript" src="/js/prototype/v1.6.0.3/prototype.js"></script>
<script> 

(function() {
    var po = document.createElement('script');
    po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/client.js?onload=OnLoadCallback';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(po, s);
})();

function OnLoadCallback() {
    sessionParams = {
        "client_id": "CLIENT_ID",
        "session_state": null
    };
    gapi.auth.checkSessionState(sessionParams, function(stateMatched) { 
        if (stateMatched == true) { 
            document.getElementById("msg").textContent = "You be logged out"; 
        } else { 
            document.getElementById("msg").textContent = "You be logged in"; 
        }
    });
} 

</script>
</head>
<body>
    <div>gapi.auth.checkSessionState</div>
    <div id="msg"></div>
</body>
</html>
```

**Comment by TMSCH** [comment]
@nahtemf `gapi.auth` is no longer maintained. Furthermore `gapi.auth.checkSessionState` is not documented. If prototype.js 1.6.x breaks it, and you really want to use `gapi.auth.checkSessionState`, I would recommend downgrading it to 1.5.x.

However I would much rather recommend migrating to [GSI v2](https://developers.google.com/identity/sign-in/web/sign-in), it will take away the pain of managing the user's login state.

**Comment by bsittler** [comment]
@nahtemf prototype.js 1.6.x is quite old and has some serious problems around JSON handling. It supplies toJSON methods on some of the core JavaScript object prototypes that are broken. We recently changed our JSON serialization to use window.JSON which invokes those toJSON methods

**Comment by nahtemf** [comment]
@TMSCH @bsittler 
Thanks for your reply.

**Comment by sundaresan-venkatesan** [comment]
Hi,

  We were facing facing a similar issue last week, but we're not able to replicate it now. Although we didn't make any changes from our end. Is this issue resolved ?

**Comment by TMSCH** [comment]
@sundaresan-venkatesan yes the issue was resolved on our end.

**Comment by sundaresan-venkatesan** [comment]
Thank you so much @TMSCH

**Comment by bsittler** [comment]
@nahtemf thanks for your report. As @TMSCH says, gapi.auth is no longer recommended, but in any case the issue should now be resolved

**Comment by TMSCH** [comment]
Glad it's working!
