### ISSUE TITLE
 Google drive API subfolders list issue on other accounts 

### ISSUE THREAD

**Issue by o0alexela0o** [google/google-api-javascript-client#338]
Having some strange issue.I have public shared folder i'm working on within my app.with my user i can get folder and subfolders and all items inside.But once i login with test user and trying get get the same, wired thing is happening: i'm getting first children of main folderbut once i'm trying to get items from each child folder, result is empty and without any error.What should i do?my user working well, but not any other. i mean half working - only first children does but deeper are not.Please advice.Thanks

**Comment by bochunz** [comment]
This repo is for the general API JavaScript Library. For question specific to the Drive API, could you direct your question to https://developers.google.com/drive/v2/web/support?

**Comment by o0alexela0o** [comment]
please explain what does that mean general? my issue is not general?

**Comment by bochunz** [comment]
By general, I mean this library works for all Google's APIs, including Gmail, Google Drive, Google Calendar, etc. For questions specific to the Google Drive API, please direct your question to the Google Drive API's support.

**Comment by o0alexela0o** [comment]
Hey guys, i issued a bug more than a month, is there any way i could know if they will ever work on this? i'm stuck in my app because of this bug (and it is a bug, i proved that it's not my code makes this)  https://youtu.be/MZpHwvnX7Sw

**Comment by bsittler** [comment]
@o0alexela0o  Please ask your question on StackOverflow with the google-drive-sdk tag: https://stackoverflow.com/questions/tagged/google-drive-sdk
