### ISSUE TITLE
GoogleUser.grant fails with TypeError: Cannot read property '$k' of undefined

### ISSUE THREAD

**Issue by galtroarc** [google/google-api-javascript-client#339]
GoogleUser.grant was working perfectly fine before (for a year now) but has stopped working today in all our products that use Google Identify. Please see the screenshot below of the symptoms. Both the code and the error are captured in it.
Description:

* Call to GoogleUser.grant fails - we have made sure we are doing everything right by process, sequence etc. This call is for incrementally authorizing a signed in user. Again, it's previously working code
* The error reads "TypeError: Cannot read property '$k' of undefined". 

This has basically broken our production apps as our app is deeply integrated with Google Apps for education and Google sign in is critical. We are hoping for a speedy response. Much appreciated.

*Error stack:*
`TypeError: Cannot read property '$k' of undefined↵    at rl (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.SrFCg38vrHU.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNG24oLmPYHxuy-JDE9titXhq3dgQ/cb=gapi.loaded_1:60:100)↵    at pP (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.SrFCg38vrHU.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNG24oLmPYHxuy-JDE9titXhq3dgQ/cb=gapi.loaded_1:92:6)↵    at qY (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.SrFCg38vrHU.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNG24oLmPYHxuy-JDE9titXhq3dgQ/cb=gapi.loaded_1:88:362)↵    at WE.<anonymous> (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.SrFCg38vrHU.O/m=auth2/exm=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNG24oLmPYHxuy-JDE9titXhq3dgQ/cb=gapi.loaded_1:72:160)↵    at new _.C (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.SrFCg38vrHU.O/m=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCNG24oLmPYHxuy-JDE9ti`

![joezoo](https://user-images.githubusercontent.com/7293519/30506653-9751172c-9a4b-11e7-9a59-a52eee413c54.png)

**Comment by bsittler** [comment]
Thanks for the report, @galtroarc -- we are currently investigating and hope to resolve the issue soon

**Comment by galtroarc** [comment]
Thanks for very much for the update. Good to know.

**Comment by TMSCH** [comment]
@galtroarc we are rolling out a fix. It should be live by end of night. I will update this thread once it is. Apology for the breakage, and thanks for reporting!

**Comment by galtroarc** [comment]
Thank you Thomas. I appreciate the responsiveness after I report it.

**Comment by galtroarc** [comment]
This seems to be working in all scenarios for us. I'm closing this issue. Thank you for the quick fix.

**Comment by TMSCH** [comment]
Glad it was resolved!
