### ISSUE TITLE
First call of gapi.auth2.authorize fails in IE and Edge

### ISSUE THREAD

**Issue by smaiLee** [google/google-api-javascript-client#341]
First call of `gapi.auth2.authorize` after page load fails in IE (11) and Edge with the Exception
`SCRIPT5007: Unable to get property 'A7' of undefined or null reference` in `File: cb=gapi.loaded_0, Line: 2977, Column: 9`.
Any subsequent call works as expected and opens the authorization popup.

This does not happen in Chrome (on Windows or Android) and Firefox . I've found a condition which calls this failing part of code only for IE, Edge and Chrome for iOS.

I tried many different config options, none of them changed anything on the behavior.

You find my complete test page below (just replaced the client id). First click on the button throws the exception, second one works.
Did I do anything wrong or ist this a bug in gapi?
```
<!DOCTYPE html>
<html>
<head>
<script src="https://apis.google.com/js/api.js"></script>
<script type="text/javascript">
	window.onload = function() {
		gapi.load('auth2', function() {
			document.getElementById('auth_button').onclick = authorizeClicked;
		});
	}

	function authorizeClicked() {
		gapi.auth2.authorize(
			{
				client_id: '${myClientId}',
				scope: 'https://www.googleapis.com/auth/calendar.readonly',
				prompt: 'consent',
				response_type: 'code'
			},
			function(resp) {
				alert(JSON.stringify(resp));
			}
		);
	}
</script>
</head>
<body>
	<button id="auth_button">Authorize</button>
</body>
</html>
```

**Comment by TMSCH** [comment]
Thanks @smaiLee for reporting the issue. We are currently investigating.

**Comment by TMSCH** [comment]
@smaiLee the issue has been fixed. Let me know if that works for you!

**Comment by smaiLee** [comment]
Tested successfully.
Thank you for your very fast reaction and fix.

**Comment by TMSCH** [comment]
Glad it's fixed!

**Comment by sachinyadav1990** [comment]
what are the fix for this issue ... i have the same issue... Fast reply appreciated

**Comment by TMSCH** [comment]
It should already be fixed @sachinyadav1990. Is it the same issue?
