### ISSUE TITLE
authSample.html appears to work without apiKey set

### ISSUE THREAD

**Issue by kaihendry** [google/google-api-javascript-client#344]
I.e. just **clientId** to identify the app instead of [adding apiKey](https://github.com/google/google-api-javascript-client/blob/master/samples/authSample.html#L69):
```
gapi.client.init({
            discoveryDocs: discoveryDocs,
            clientId: clientId,
            scope: scopes
        })
```

Why is this? Why have an example with a key you don't need to disclose? 

In fact I can't see any mention of apiKey here: https://developers.google.com/identity/sign-in/web/reference#gapiauth2clientconfig

**Comment by bsittler** [comment]
Always using an API key ensures calls are reliably associated with the calling application, even when an OAuth token is not yet present or has already expired. The API key is included in this example to encourage safe development practices.

**Comment by bsittler** [comment]
(and you are correct that gapi.auth2 does not define this parameter -- it is specific to gapi.client)
