### ISSUE TITLE
grantOfflineAccess for additional scopes

### ISSUE THREAD

**Issue by timofloettmann** [google/google-api-javascript-client#350]
Hi there,

I have an application in which users should be able to grant certain permissions after login. It's built as a Single Page Application using React, the google-api-javascript-client is only loaded once and shared by different components.

The user flow should be like this:
1. Go to /login and login using google (at this point we only need the basic info - scope: profile)
2. Get redirected to /welcome. There the user has the possibility to grant permission for our application to read emails (gmail.readonly). This would be required as offline access, as it's done on the server.

It seems however, that whatever I try, I'm unable to request additional permissions on /welcome. The request for permissions happens, but it only includes the profile scope with which the init method was called and is therefore instantly resolved.
It only works once I reload the page and call init() with all the additional scopes included.

I've used https://developers.google.com/identity/sign-in/web/server-side-flow as a guideline to implement the login, but wasn't able to find any information about requesting additional permissions later on.

This brings the question: Is there a way to reset or overwrite the configuration? What would be the suggested way of implementing this kind of logic?

Thanks.

**Comment by TMSCH** [comment]
Hi @timofloettmann, could you provide a minimal snippet of code that reproduces the issue? You should be able to call [`GoogleUser.grantOfflineAccess`](https://developers.google.com/identity/sign-in/web/reference#googleusergrantofflineaccessscopes) to get an authorization code for the scopes passed to its call, like this:

```javascript
gapi.auth2.getAuthInstance().currentUser.get().grantOfflineAccess({scope: '<scope>'})
```

I realize that the documentation mentions the method takes the scopes directly. That is a mistake I will address.

**Comment by timofloettmann** [comment]
Hi @TMSCH,

Thank you very much, that solves it.

The Documentation currently mentions two ways of calling `grantOfflineAccess`: 

1) `GoogleAuth.grantOfflineAccess(options)` where options is `A gapi.auth2.OfflineAccessOptions object containing key-value pairs of parameters.`. Though `gapi.auth2.OfflineAccessOptions` didn't exist for me.

2) `GoogleUser.grantOfflineAccess(scopes)`, which you already mentioned seems to be a mistake.

**Comment by TMSCH** [comment]
You're right @timofloettmann, it mentions these 2, and the second option has the wrong signature. It actually takes an `options` object. We're updating the doc very soon.

**Comment by TMSCH** [comment]
The doc has been updated: https://developers.google.com/identity/sign-in/web/reference#googleusergrantofflineaccessoptions
