### ISSUE TITLE
"state" parameter not documented in the 'Google Sign-In JavaScript client reference' docs

### ISSUE THREAD

**Issue by joeltucci** [google/google-api-javascript-client#354]
As documented in Google's oauth2 REST API documentation there is an recommended 'state' parameter that can be used by the requesting server to track an individual request.  The Javascript library(in particular at least the gapi.auth2.authorize function) supports this parameter and it works as expected, but it is not documented in any of Google's documentation.  The Javascript parameter should match those of the REST API.

**Comment by TMSCH** [comment]
It is only recommended in Server-side OAuth 2.0 redirect flows. In such scenario, the JS library is of very limited interest (it basically would create the Authorization URL and redirect to it) so I wouldn't recommend using the JS library for server side flow.
