### ISSUE TITLE
oauth2 not working with last version of google chrome

### ISSUE THREAD

**Issue by makas2** [google/google-api-javascript-client#357]
Try sample from documentation
https://developers.google.com/identity/protocols/OAuth2UserAgent#example
We could select an account from popup dialog,
 but
SignIn don't autorize in Google Chrome version 62.0.3202.94

In my example bilding by this documentation I got the error message with code "popup_closed_by_user"

**Comment by makas2** [comment]
In Google Chrome version 62.0.3202.94
method 
gapi.auth2.getAuthInstance().signIn(options).then(function(resp) {
            var auth_code = resp.code;
        },
            function(resp) {
                var auth_code = resp.code; 
            });

got error response "popup_closed_by_user" and don't autorize user 
the same code works fine in oldest chrome version and in other browsers

**Comment by TMSCH** [comment]
@makas2 are you calling `signIn` right after a user click? Do you see the popup opening?

If yes, do you have enabled the setting to block third-party data?

**Comment by makas2** [comment]
@TMSCH Yes. I'm calling signIn after user click.
Could you clarify where can I find that seeting block third-party data?

**Comment by TMSCH** [comment]
Go to [chrome://settings/content/cookies](chrome://settings/content/cookies), the "Block third-party cookies" setting. `gapi.auth2` works fine with my version of Chrome that is also Version 62.0.3202.94 (Official Build) (64-bit).

**Comment by makas2** [comment]
@TMSCH Thank you.
It's helped

**Comment by kongguibin** [comment]
This bug should be fixed. More deatil at https://github.com/google/google-api-javascript-client/issues/405.
