### ISSUE TITLE
Session management based on JWT issued by Google

### ISSUE THREAD

**Issue by marekciupak** [google/google-api-javascript-client#359]
Hello!

I'm using [Google Sign-in](https://developers.google.com/identity/sign-in/web/reference) in my React app to authenticate & authorize users in my backend.

I'm considering the following flow:
1. User signs in using Google Sign-in button,
2. Save `id_token` from [`gapi.auth2.AuthResponse`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authresponse) into browser's local storage
3. Send `id_token` with **each subsequent** request to the backed (`Authorization: Bearer <id_token>`)

It looks simple. This way my backend app won't have to issue any credentials, because the whole session management would be based on tokens issued by Google. Of course, I would have to properly verify the `id_token` on the backend with every request (but that's fine).

The reason I'm wondering if this is a good solution is that a newly issued `id_token` is valid only for about 1 hour. It means I would need to refresh it periodically (I guess using [`GoogleUser.reloadAuthResponse()`](https://developers.google.com/identity/sign-in/web/reference#googleuserreloadauthresponse)).

Does this idea make sense to you?

Perhaps it would be better to use Google's `id_token` to exchange for a token issued by my app and use that one in subsequent requests.

Does one of the solutions is clearly better than the other (security, good practices) or maybe both are ok and the answer to "which one is better" question is "it depends" ?

Thanks,
Marek

**Comment by TMSCH** [comment]
Hi @marekciupak,
Either solution is fine.
Using the Google `id_token` for authentication is a good technique, so you don't have to manage tokens yourself. `id_token` is automatically refreshed by `gapi.auth2` (when using `gapi.auth2.init/signIn`), so you shouldn't have to reload manually.
Make sure you perform all the required checks in the backend, explained [here](https://developers.google.com/identity/sign-in/web/backend-auth).
However you'd need to include the JS library everywhere, which would add extra payload on all pages. Some frameworks handle session management for you, and are probably well suited to your use case, and would allow not to include `gapi.auth2` in every page of your app.

**Comment by marekciupak** [comment]
Hi @TMSCH,

> Either solution is fine.

Thank you for your answer!

> `id_token` is automatically refreshed by `gapi.auth2` (when using `gapi.auth2.init/signIn`), so you shouldn't have to reload manually.

The thing is that I'm building SPA, so I trigger `gapi.auth2.init` only once. A user can sign in and use the page for >1 hour and his `id_token` will expire. Then, instead of going through sign in process again (`gapi.auth2.signIn`), I'm simply refreshing the token with `GoogleUser.reloadAuthResponse()`.

> However you'd need to include the JS library everywhere, which would add extra payload on all pages. Some frameworks handle session management for you, and are probably well suited to your use case, and would allow not to include gapi.auth2 in every page of your app.

I understand you mean the second solution I proposed (using Google's id_token to authenticate a user, but exchanging it for the other credential managed by me/library/framework for future requests).
I think I will go in this direction.

Thanks,
Marek

**Comment by TMSCH** [comment]
If it's a SPA then relying on `gapi.auth2` to automatically refresh token every hour (no need to call `reloadAuthResponse`) works too.
