### ISSUE TITLE
setToken issue

### ISSUE THREAD

**Issue by iWedmak** [google/google-api-javascript-client#360]
my users can have multiple google accounts, i need to auth them, remember and store refresh_token.
Refresh token i use on server and in user browser (access_token)
People can be from different browsers, not always authorized on accounts that they give me refresh tokens.
So i need to dynamically set access_token in browser for different accounts, and query them (analytics), collect data and so on.
As i understand i can simply use setToken (if im right even in incognito)
like this 
`gapi.client.setToken(source.token)`
but it does not trigger auth, token is valid (still works on server side)

my flow:
1. 
```
gapi.client.init({
                discoveryDocs: ["https://analyticsreporting.googleapis.com/$discovery/rest"],
                clientId: "",
                scope: 'https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.edit'
            }).then(
            function () 
            {
                gapi.auth2.getAuthInstance().isSignedIn.listen(self.updateSigninStatus);
                self.updateSigninStatus(gapi.auth2.getAuthInstance().isSignedIn.get());
             });
```
2. first time auth
gapi.auth2.getAuthInstance().grantOfflineAccess().then(function(data){ send code to server}

3. in some time in future, may be from different browser
`gapi.client.setToken(source.token)`

**Comment by TMSCH** [comment]
@iWedmak you cannot trigger auth by setting its token. The only way to trigger auth is to have the user sign in.
How do you know which user is using your app, before setting sending the access token to the client?

**Comment by iWedmak** [comment]
Users have account auth on my site, and they add google accounts with which they can work
Soo basicaly i need to check if user on this broswer already give me permissions to work with this google account
Any right way to do this?
I build extra reports on google analitics, so people do need to work with different google accounts

**Comment by TMSCH** [comment]
Yes, you can use [`gapi.auth2.authorize`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams-callback) passing `prompt: 'none'` to silently authenticate the user.

**Comment by iWedmak** [comment]
soooo
i do this
```
gaSetToken(token);
gapi.client.analytics.management.goals.list(list_query).then(function(goals)
```
and got 403
token is from db

hire how i init and set token
```
var gapiPromise = new Promise(function(resolve, reject){
    window.onload = function()
    {
        gapi.load('auth2:analytics:client', function() {
            gapi.auth2.authorize(extend(gaConfig, {prompt: 'select_account'}), function()
            {
                resolve();
            });
        });
        
    };
});
var gaSetToken= function(token)
{
    gapiPromise.then(function () 
    {
        gapi.client.setToken(token);
        gapi.auth2.authorize(extend(gaConfig, {prompt: 'none'}), function()
        {
            gPResolve();
        });
        
    });
    
}
```
what now im doing wrong?)

**Comment by TMSCH** [comment]
You cannot use an access token to select an account. For that, use [`login_hint`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeconfig) passing the account's email address or [ID](https://developers.google.com/identity/sign-in/web/reference#googleusergetid).

**Comment by vdiaza** [comment]
Any luck with this? I have been trying to do the same thing. Authorize the user at first and then use analytic data without prompt again from different browsers. Is it possible?
