### ISSUE TITLE
gapi.client.load(urlOrObject) should have an optional apiRoot parameter

### ISSUE THREAD

**Issue by nverwer** [google/google-api-javascript-client#363]
I am loading my client library using

> `gapi.client.load(apiName, apiVersion, apiLoadCallback, apiRoot)`

This uses an [undocumented](https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiclientloadname--------version--------callback) `apiRoot` parameter, which is needed when testing in my development environment (localhost).

Unfortunately, this way of calling `gapi.client.load` is deprecated. I would like to use `gapi.client.load(urlOrObject)` but there is no way to specify the apiRoot, so it does not work on localhost.
Please make it possible to use something like `gapi.client.load(urlOrObject, apiRoot)` and document it.

A related question is, if it is possible to use an apiRoot for `gapi.client.init(args)`? The documentation does not say so.

**Comment by bochunz** [comment]
Thanks for your comment. The recommended way is to use URLs for everything. In local testing, just use `gapi.client.load("http://localhost/...")`.

**Comment by nverwer** [comment]
@bochunz: Thank you for your help. The problem turned out to be, that I had omitted the protocol-part from the URI of my discovery document. That caused `gapi.client.load` to look for the discovery document on Google's servers. Of course that did not work.
Once I had fixed that, `gapi.client.load` did exactly what I wanted, and I have stopped using the deprecated version.
