### ISSUE TITLE
gapi.auth2.authorize auto refresh revoked access token.

### ISSUE THREAD

**Issue by p0kjin57** [google/google-api-javascript-client#364]
As described, I am trying to use gapi.auth2.authorize instead of the recommended signIn flow. Everything is fine with gapi.auth2.authorize until a user revokes the token / disconnects the app and tries to login again. Then gapi.auth2.authorize will return a new code but the old, revoked, access token. It seems like for every gapi.auth2.authorize the access token stays same until access token expires.

It will be best if the api will auto refresh the access token or return a different access token for every single call.

Don't know if it is the expected behavior, if so I would love to get some suggestion to solve the issue I currently have.

**Comment by TMSCH** [comment]
@p0kjin57 does it happen within the same window or in another session? In other words, do you reproduce the issue doing so:

1. Go to app, grants the app access to the scopes requests for the user using `gapi.auth2.authorize`
2. In the same (or another) window, go to myaccount.google.com, disconnect the app.
3. **In the same window than 1.**, go to the app, call `gapi.auth2.authorize`

Or in 3., you use a different window? The library performs some caching for better performance so it might be the reason.

**Comment by p0kjin57** [comment]
@TMSCH 3. Same window. I think caching might be the reason. I can tell it since the expires_in, expires_at, and first_issued_at stays the same.

**Comment by TMSCH** [comment]
@p0kjin57 It's a limited edge case that we are aware of. In practice, the conditions to reach such state for a user in a normal usage of an app is very rare. To fix this issue, it would require a call to the backend to detect such state, which would render the cache useless. We think the benefits in performance for most users are higher than the drawbacks of such behavior for very limited scenarios.
