### ISSUE TITLE
api closing navigator with the browser safari mobile after the update of IOS.

### ISSUE THREAD

**Issue by marcosstefani** [google/google-api-javascript-client#368]
Dear Google,

After the IOS upgrade we have problems with authentication via gapi (using auth2). The browser simply closes the browser window. From what I've noticed, this may be related to the opening of a new tab in the browser when the login is performed. Is there any guidance for solving this problem? Is there any other way to authenticate without needing to open the new tab so that I limit the hosted_domain? Here's my JS code:

`gapi.load('auth2', function() {
    gapi.auth2.init({
        client_id: my_id,
        hosted_domain: 'wine.com.br'
    }).then(function () {
        auth2 = gapi.auth2.getAuthInstance();
        auth2.attachClickHandler('signin-button', {}, onSuccess, onFailure);
        if (auth2.isSignedIn.get()) {
            window.location.replace('menu.html');
        }
    });
});`

Awaiting return.

**Comment by TMSCH** [comment]
@marcosstefani, I'd recommend using `'redirect'` [UX mode](https://developers.google.com/identity/sign-in/web/reference#gapiauth2clientconfig) in mobile. Let me know if that fixes the issue!

**Comment by marcosstefani** [comment]
Good Morning @TMSCH 
Thanks for the feedback. As soon as I can do the tests, I'll give you the return here. I have seen that this configuration requires OAuth client authorization. I'll get back to you as soon as I can test.

**Comment by marcosstefani** [comment]
Thank you. I had feedback today from our systems approval industry that the problem was corrected with the suggested solution. Thank you very much and sorry for the delay in reply.
