### ISSUE TITLE
Passing access_tokens between client and server

### ISSUE THREAD

**Issue by drupdateio** [google/google-api-javascript-client#369]
Hi,

I have a client/server application (client is using angular, server is using nodejs). On the client side, I'm using the google picker to allow my users to select a spreadsheet in which I'm writing values. What I'd like to do is to send the user's credentials server-side and then keep these values in sync without further intervention of the user.

I've successfully passed the access_token retrieved on the client to the server, but now I need to find a way to get a refresh_token, so that the server can refresh the token regularly and keep the data in sync. Is there a possibility to:

* either request a refresh_token directly from the client application (which I can then send to the server)
* or, server-side, use the access_token passed by the client to get a refresh_token ?

Thank you for your help with this.

**Comment by bsittler** [comment]
No, you need to use an authorization code for that step. The web server application will then combine the authorization code and either a client certificate or a client secret to prove its identity and fetch a refresh token. You will need to request the "offline" access_type and the "code" response_type. I believe this should work using [auth2.grantOfflineAccess()](https://developers.google.com/identity/sign-in/web/reference#googleauthgrantofflineaccessoptions) or using [gapi.auth2.authorize()](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams-callback)

**Comment by drupdateio** [comment]
Yes, I came to the same conclusion and, after quite a bit of hair pulling, it now works :-) But thank you for your message !
