### ISSUE TITLE
Multiple bugs in gapi.client.Batch.execute and gapi.client.Batch.then

### ISSUE THREAD

**Issue by johannburkard** [google/google-api-javascript-client#376]
There are two bugs in `gapi.client.Batch.execute` and `gapi.client.Batch.then`.

- `gapi.client.Batch.execute` does not call callback upon failure.
- `gapi.client.Batch.then` does not call the callback functions of individual requests

Examples:

```javascript
const batchContainers = gapi.client.newBatch()
_.each(accounts, function(account) {
    batchContainers.add(gapi.client.request({ path: toURL(account) }), {
        callback: function(data) {
            // Never called if using batchContainers.then
        }
    })
})
// Using execute
batchContainers.execute(function() {
    // Request callbacks called
    // This callback not called if batchContainers fails
})
// Using then
batchContainers.then(function() {
    // Request callbacks not called
})
```

This can be seen in action at https://gtm.tools by trying to edit a container that the current user has no editing rights to. The `fn` function at line 1097 is not called.

**Comment by aofzazsex5aofzazGithub** [comment]
แก้ไขปัญหา

**Comment by bochunz** [comment]
batchContainers.then suppresses per-request callback. But the object passed to the then function will contain all the requests.

callback not called if batchContainers fails is a known issue similar to #168
