### ISSUE TITLE
Allow auth onload param to be non-global

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#38]
_From [Pw.Rob...@gmail.com](https://code.google.com/u/110703866327219559793/) on July 10, 2012 04:44:26_

It would clean up the global namespace if I could load auth callback with something like:

<script src=" https://apis.google.com/js/auth.js?onload=mynamespace.handleLoad"></script> which doesn't seem to work at the moment.
The other load method:

gapi.load('auth', mynamespace.handleLoad);

does seem to work.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=38_

**Comment by edencore** [comment]
Can't find a method `gapi.load`.
