### ISSUE TITLE
Google Sign-In for server-side apps scenario fails after request of additional permissions: refresh token never returned back by Google API.

### ISSUE THREAD

**Issue by voiceactivity** [google/google-api-javascript-client#383]
Scenario: Google Sign-In for server-side apps (docs -
 https://developers.google.com/identity/sign-in/web/server-side-flow).

1. Auth2 successfully initialized during client sign-in:
  var auth2 = gapi.auth2.init({
  client_id: apiClientId,
  scope: 'profile'
  });
auth2.signIn().then( /** id_token successfully extracted and passed to the server for authentication */)

2. Allow a user to integrate his calendar & tasks into app by requesting additional scopes. User already logged in (docs - https://developers.google.com/identity/sign-in/web/incremental-auth ):
                            
  var options = new gapi.auth2.SigninOptionsBuilder({'scope': 'https://www.googleapis.com/auth/tasks https://www.googleapis.com/auth/calendar'});
  
  var googleUser = gapi.auth2.getAuthInstance().currentUser.get();
  googleUser.grant(options).then(
    function (result) {
      callback(gapi.auth2.getAuthInstance()); // -> we have a success here call the callback
      }, function (fail) {...}

3. After extra permissions were granted request offline access. Google sign-in screen shown -> user signed-in. User Consent screen shown for access the app to the Calendar and Tasks -> user granted consent. Consent screen closed.
 
The code:
    auth2.grantOfflineAccess().then(function (authResult) {
                        if (authResult['code']) {
                            var data = authResult['code'];
                            //successfully received the one-time code that the server can exchange for its own access token and refresh token (e.g. 4/yU4cQZTMnnMtetyFcIWNItG32eKxxxgXXX-Z4yyJJJo.4qHskT-UtugceFc0ZRONyF4z7U4UmAI).

                          //passing the code to the server ...
                         }... 
                            
4. Server receives the one-time code and calls the Google Auth endpoint (via client lib or directly, doesn't matter):
 https://www.googleapis.com/oauth2/v4/token?code=one_time_auth_code&client_id=my_client_id&client_secret=my_secret&redirect_uri=redirect_url&grant_type=authorization_code

5. Google Auth endpoint return successful in JSON but the refresh token always MISSING!!!
{
  "access_token": "...",
  "expires_in": 3599,
  "id_token": "...",
  "token_type": "Bearer"
}
That makes the offline usage of the Google API completely useless.
Spent a few day figuring out the cause. Initially thought that I hit the limit (https://developers.google.com/identity/protocols/OAuth2#expiration).
Nop. I created a brand new API user. Same story. Refresh token never comes back from Google.

Could you please help!

**Comment by TMSCH** [comment]
@voiceactivity this is indeed a bug, thanks for raising the issue. We are investigating.

**Comment by TMSCH** [comment]
@voiceactivity the `refresh_token` is only returned with the code generated the first time the user consents to the scopes. You can use `prompt: 'consent'` option in the `grantOfflineAccess` call to force the user to consent again. The code generated will then be exchangeable for a refresh token.

**Comment by voiceactivity** [comment]
OK, thank you. Would be great to update the guidance docs accordingly.

**Comment by TMSCH** [comment]
@voiceactivity we are going to release a new version soon which automatically sets `prompt: 'consent'` if not set to avoid the issue you encountered.

**Comment by voiceactivity** [comment]
Great, do you want me to close the issue. Or we would rather wait till the change go live and test it again?

**Comment by TMSCH** [comment]
I'll update the thread when it's live.

**Comment by voiceactivity** [comment]
Sounds good. Thank you.

**Comment by TMSCH** [comment]
It's live.
