### ISSUE TITLE
gapi.client.plus.people.search return nothing

### ISSUE THREAD

**Issue by cabri89** [google/google-api-javascript-client#384]
Hello everyone,

i have a problem since one month. The function gapi.client.plus.people.search return an empty array items  with no error. With the git example the array items is empty. With the online console (https://developers.google.com/+/web/api/rest/latest/people/search) I have the same problem.

I need help ...

Regards.

**Comment by bochunz** [comment]
@cabri89 This repo is for the JavaScript library that works for all Google APIs (including G+, Google Calendar, Gmail, etc.). If you have a particular question to the G+ API, please use support here: https://developers.google.com/+/web/support
