### ISSUE TITLE
how to show a consent pop up followed by a select account pop up

### ISSUE THREAD

**Issue by taxiahou** [google/google-api-javascript-client#386]
Hi, team,

I am using gapi.auth2.authorize to sign in. We have a broken scenario needing suggestion from you. 
When user clicks sign in button, we will use below sign in config. 
    this.signInConfig = {
      client_id: getClientId(),
      scope: OAUTH_SCOPE,
      response_type: 'code permission', // 'permission' is required to get back user email address
      prompt: 'select_account',
      cookie_policy: 'none',
    };

And then send the authorisation code to server side. Recently we updated oauth client id and secret, so there are cases that server side could not generate refresh token. In that case, we need to show user consent pop up to fix this. 

I tried to call gapi.auth2.authorize again after getting the error info from server side, but got error popup_blocked_by_browser. It seemed that pop up is not allowed if it is not user activity. 

Can you please give me some suggestions on this case? How can i handle this elegantly? One fix i can think of is that when getting the error from server side, we have to show a confirm window to user and if user clicks ok, we show sign in window with consent prompt. If possible, we want to have a more smooth sign in process without clicking button twice.

**Comment by TMSCH** [comment]
@taxiahou the `popup_blocked_by_browser` is expected, a popup can only be opened synchronously after a user interaction. There's no way around it, you'd have to put a button.

The other way is to trigger a redirect flow:

```
gapi.auth2.getAuthInstance().signIn({ux_mode: 'redirect'});
```

This won't require a user interaction.
