### ISSUE TITLE
People API personFields

### ISSUE THREAD

**Issue by megapat** [google/google-api-javascript-client#388]
Unable to find out which is the proper way to use People API. According to the docs the following code should works fine:

var contact = google.people({ version: 'v1', auth: auth });
  contact.people.get({
      resourceName: 'people/me',
      personFields: 'names'
    }, 
    (err, connections) =>
    {
      if (err) {
        throw err;
      }
    });

but the response is:
Error: personFields mask is required. Please specify one or more valid paths. Valid paths are documented at https://developers.google.com/people/api/rest/v1/people/get

**Comment by TMSCH** [comment]
Hi @megapat, this issue tracker is for the general `gapi.client` library and auth2. For the People API, please ask your question on [SO](https://stackoverflow.com/questions/tagged/google-people) with the `google-people` tag.
