### ISSUE TITLE
error: popup_closed_by_user

### ISSUE THREAD

**Issue by 13125381** [google/google-api-javascript-client#390]
SDK throws 'error: popup_closed_by_user' when trying to authenticate. 

Steps to reproduce:
Click the 'Sign in with Google' button. 
A dialog opens up, asking for my credentials.
After entering in my credentials, the dialog closes and the auth2.attachClickHandler error callback returns 'error: popup_closed_by_user'.
 The correct origin and redirect URLs have added to the cloud console. Double checked the client config and its using the correct google client ID.

Has anyone else ran in to this issue?

**Comment by TMSCH** [comment]
@13125381 what browser are you using? Have you blocked third party cookies? Are you using Incognito/Private mode?

**Comment by 13125381** [comment]
@TMSCH Chrome Version 64.0.3282.140 (Official Build) (64-bit). All plugins have been disabled and I'm not using incognito/private mode.

**Comment by TMSCH** [comment]
@13125381 could you post the snippet of code you're using to reproduce the issue?

**Comment by 13125381** [comment]
@TMSCH Figured it out. The disconnect() function was being called on the sign up page, revoking the scopes granted. When you clicked the Google sign in button, the disconnect() function hadn't finished executing, therefore throwing an error, however when chrome inspector was open the error 'popup_closed_by_user' was displayed instead an error about scopes. Calling signOut() instead of disconnect() resolved this issue.

**Comment by TMSCH** [comment]
Ah good catch. `disconnect` should be used in very rare conditions (when the user deletes their account for instance).
