### ISSUE TITLE
gapi.auth2.init({ ... }).then(... sometimes doesn't resolve when Chrome DevTools are open

### ISSUE THREAD

**Issue by rsolomon** [google/google-api-javascript-client#392]
I almost couldn't believe it when I figured it out, but starting a few days ago I noticed that many attempts to initialize the oauth2 would simply hang-- no error nor success callback. It was particularly confusing because it was only happening on my system.

Later on, a co-worker mentioned that he saw this issue a few weeks back on Chrome Canary. His solution? Close DevTools. So sure enough, I checked in on a hung tab that had been open be on a page where the response was hanging for more then an hour. I clicked that taunting little "X" in devtools, and sure enough the promise resolved immediately.

I want to emphasize that there was no breakpoint set, and the JS thread was not paused in any way.

Chrome
v64.0.3282.140

GAPI @ latest
https://apis.google.com/js/api.js

**Comment by bsittler** [comment]
Thanks for the issue report! That sounds like it could possibly be a bug in Chrome's DevTools. Would you be able to report it at https://crbug.com and link to your report from here so we can track progress on the issue?

**Comment by rsolomon** [comment]
Done and done! https://bugs.chromium.org/p/chromium/issues/detail?id=813160

**Comment by bsittler** [comment]
Thanks for filing!

**Comment by bsittler** [comment]
@TMSCH this looks like it might be an infinite-.then(...)-recursion issue. Can this be fixed in the library? See also https://bugs.chromium.org/p/chromium/issues/detail?id=813160#c5

**Comment by bsittler** [comment]
[pasting here to simplify the discussion since I'm not convinced yet that Chromium is doing anything wrong]

This may be a bug in GAPI rather than DevTools - it looks like gapi.auth.init's .then(...) resolves to a GoogleAuth object which has a self-resolving .then(...) causing a promise resolution loop.

As a workaround you can set an undefined 'then' own-property before using the object with promises:

Navigate to https://oauth.googleusercontent.com/robots.txt and open the JS console. Paste this into it and execute:

```js

const client_id = '359269480423-chvhi5jr4a5379f4id4cta0sd1gueqg2.apps.googleusercontent.com';

await new Promise(api_ready => document.head.append(Object.assign(document.createElement('script'), {src: 'https://apis.google.com/js/api.js', onload: api_ready})));

await new Promise(auth2_ready => gapi.load('auth2', auth2_ready));

const googleAuth = await new Promise(init_done => gapi.auth2.init({client_id: client_id, scope: 'openid'}).then(googleAuthWithThen => init_done(Object.assign(googleAuthWithThen, {then: undefined}))));

console.log('googleAuth =', googleAuth);

```

Does this resolve the issue for you?

**Comment by bsittler** [comment]
(The dangerous API surface is also mentioned in https://developers.google.com/identity/sign-in/web/reference#googleauththenoninit-onerror but I wouldn't expect a generic implementation of thenable-following to be able to avoid the loop.)

**Comment by TMSCH** [comment]
@bsittler The method you mention would make the `then` method `undefined` in the original object, making it unusable in other parts of the code. I did try to avoid this infinite recursion problem, but the `GoogleAuth` object having so much internal state, it led to a non trivial error.

**Comment by bsittler** [comment]
@TMSCH understood, a slightly more subtle wrapper is needed I think to avoid that breakage. We'll discuss offline

**Comment by TMSCH** [comment]
@rsolomon we deployed a fix to this issue. Feel free to reopen if it still doesn't work for you.

**Comment by jcanaan88** [comment]
I'm getting a very similar issue with 67.0.3396.79.  It just stops after the request is made, no success to error handling.  When you click on the network request, it says the user is forbidden.  However, I know that's not true because it works fine in Firefox.  Any updates on this?
