### ISSUE TITLE
Keeping a google calendar linked to a firebase account.

### ISSUE THREAD

**Issue by mesqueeb** [google/google-api-javascript-client#393]
I have a firebase web app with users able to login through firebase auth (email, google, facebook, etc.).

I want my users to be able to "connect their google calendar" to their account on my app, so when they login with firebase they will automatically also be able to manage their google calendars.

I followed [this guide](https://developers.google.com/google-apps/calendar/quickstart/js) and was able to get the example running in my app to have a user show their google calendar, but **I'm not sure what and how to save** to have the firebase user _keep_ this consent to their google calendar, so they don't need to give the consent every login to firebase or on every device.

If firebase authentication won't slack it, I might be prepared to completely change the firebase auth with other methods of google authentication, but I'm not sure how to talk to my Firestore etc. in that case. (throwing away the possibility for facebook login i can think about if required.)

**Comment by TMSCH** [comment]
Please ask your question on StackOverflow, this repo is for issues with `gapi.client` and `gapi.auth2` specifically.
