### ISSUE TITLE
Does/how/when signs the gapi auth js client users in upon revisit?

### ISSUE THREAD

**Issue by mesqueeb** [google/google-api-javascript-client#395]
After reading a lot on the gapi client for google authentication, I'm confused how gapi is handling my access/refresh tokens.

After implementing GAPI auth, it logs me in automatically every time I revisit.
I cannot find any documentation [here](https://developers.google.com/identity/protocols/OAuth2UserAgent) about this behaviour...

I have three questions:

1. Is there any way to disable this?
2. Where does GAPI keep the access tokens?
3. When does GAPI check if there already was a user logged into the browser? (at `gapi.load()`?)

**Comment by TMSCH** [comment]
1. No. You can use [`gapi.auth2.authorize`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams-callback) if you don't want such behavior.

2. In memory in the client app. It also caches the tokens issued in the IFrame opened.

3. At `gapi.auth2.init()`.

**Comment by mesqueeb** [comment]
Thank you for your explanation!
