### ISSUE TITLE
Weird "idpiframe_initialization_failed" only on chrome.

### ISSUE THREAD

**Issue by mesqueeb** [google/google-api-javascript-client#398]
Chrome: 64.0.3282.167（Official Build） （64 bit）

I have a very strange `idpiframe_initialization_failed` issue **only on Google Chrome**. This happens after the GAPI load but before / during the GAPI init.

> error: "idpiframe_initialization_failed"
> details: "Not a valid origin for the client: https://listo-dev.firebaseapp.com has not been whitelisted for client ID myid.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."

I have double checked:
- There is no adblock for the domain
- The domain has definitely been whitelisted
- Have tried hard reload with clearing cache

When I try to login I will always get the error: `popup_closed_by_user`
I think these problems might be related.

### Here is where it gets weirder:

1. I set the browser to "offline".
2. I reload the page.
3. I receive the console.log that GAPI was loaded. (I don't receive the log that it's initiated, but also not the error).
4. I disable "offline".
5. I click the login button and it will log me in correctly.
HOWEVER, I will still see in the console the error: `popup_closed_by_user` only this time it _does_ log me in correctly even though the console logs that error...

**Comment by mesqueeb** [comment]
After waiting a few hours & restarting google chrome the problem went away. I have no idea what that was...

**Comment by TMSCH** [comment]
@mesqueeb it probably was HTTP caching issues. If you add the new origin to the authorized origins of the Client ID, it can take up to an hour before the browser sees the change (unless you clear the cache)

**Comment by Sentero-esp12** [comment]
How to add an authorized origin if it's a Chrome Extension?
