### ISSUE TITLE
OAuth flow asking for permissions every time

### ISSUE THREAD

**Issue by rajlenin** [google/google-api-javascript-client#400]
Our application uses grantOfflineAccess to trigger the OAuth flow on the client side. Nothing has changed in the application including the scope, but since the last couple of weeks, we notice users are prompted to grant permissions every time when they log in.

`auth2.grantOfflineAccess({'redirect_uri': 'postmessage', 'scope': scope})
          .then(signInCallback);`

Any ideas?

**Comment by TMSCH** [comment]
@rajlenin this is the expected behavior, to obtain an Offline Authorization Code, the user has to give explicit consent. However, you should only ask for it once. The code should be used by your server to obtain a refresh token that you store in your database for future use.

**Comment by rajlenin** [comment]
This is use to log in the user as well. Not sure how you would ask only once.  The application asks for offline access to sync emails on the server side. This was not the behavior before.  Here is a similar issue reported https://stackoverflow.com/questions/48338147/google-auth2-asks-for-permission-every-time-when-asking-for-access-to-the-app.
Weird though, adding "prompt : 'select_account'" fixes the issue. Obviously something changed with the OAuth flow recently.

**Comment by TMSCH** [comment]
`grantOfflineAccess` should not be used to sign in the user. [`signIn`](https://developers.google.com/identity/sign-in/web/reference#googleauthsignin) should be used.

As I explained, the offline code should be exchanged once for a `refresh_token` and you should be responsible for storing it. The behavior changed because of a bug, `grantOfflineAccess` used to return an Authorization Code that would not be exchangeable for a Refresh Token.

If you need something to "sign in" the user, use the ID Token returned by the `signIn` call.

Otherwise, you can pass `prompt: null` to the `grantOfflineAccess` call if you're OK getting an Authorization Code that you cannot exchange for a refresh token.

**Comment by rajlenin** [comment]
Thought grantOfflineAccess is used to get scope permissions and to have them for offline access as well in the same login flow.  Not sure how that can be done with just signIn. It seems like a complex logic for the application to handle them differently. Wonder how using "prompt : 'select_account' handles it in grantOfflineAccess  correctly.

**Comment by TMSCH** [comment]
"Offline" access means accessing user's data while the user is not signed in to your app. For such access, you need a Refresh Token. You seem to want "Online" access, which means accessing user's data *while the user is signed in to your app*. For this, you only need an Access Token that you can get with the `signIn` call.

`prompt: 'select_account'` will not force the user to consent again, so the Authorization Code generated will be "Online" i.e. not exchangeable for a Refresh Token. This will only be exchangeable for an Access Token, so it would also fit your requirements.

Does it make more sense?

**Comment by rajlenin** [comment]
Earlier that was the behavior observed and worked without even setting prompt: 'select_account'. This is the flow.

First time user login - user grants permissions. The application captures the offline access token and stores in DB which would be used to get a refresh token
Subsequent logins - Users just login. This is mainly used to authenticate and log in users. The application does not expect to get a offline token here.

It seems like the default behavior is changed to prompt users to grant permissions every time. I don't understand the use case for this behavior as the application using offline access needs to store the access token somewhere. So what is the need for the application to prompt the user and get this offline token every time? Wouldn't the online access token work in that case.

Anyways, it would be nice to document these behaviors which would be very useful for anyone using Google OAuth flow.

**Comment by TMSCH** [comment]
@rajlenin the previous flow was wrong, `grantOfflineAccess` is not meant to authenticate users and should only be called once. You should use `signIn` if you just want to sign in the user. Basically, the proper flow is to sign in the user with minimal scopes requested, and then call `grantOfflineAccess` to get an Offline Code for the Calendar scope.

We'll work on clarifying the documentation.

Thanks!

**Comment by rajlenin** [comment]
For our use case, we would want to get all permissions including offline access as they are required by the application in a single step. Based on what you are saying that should not be done. I get it as it allows for graduated access. But I believe the other single step use case should also be supported where offline access is absolutely required. Thanks for staying on top of it and responding to my questions.

**Comment by TMSCH** [comment]
Another option that could suit your use case is to use [`gapi.auth2.authorize`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams-callback). If you call it with `{response_type: 'code'}` it will have the same effect than `grantOfflineAccess` without forcing the consent at every time; the first time, the user will have to consent and an Offline Code will be generated. The second time, the user won't have to consent and an Online Code will be returned.

You can also use `{response_type: 'code', prompt: 'none'}` to avoid showing any popup if the user has previously consented in the same browser.

**Comment by rajlenin** [comment]
Thanks, will check it out. From the documentation, I wouldn't have known authorize could potentially grant offline access.

**Comment by TMSCH** [comment]
The `authorize` method is lower level than the other APIs of this library (hence is marked as "advanced") and it is recommended to be more familiar with OAuth 2.0 to use it. Most use cases should fit `gapi.auth2.init/GoogleAuth.signIn` behavior.
