### ISSUE TITLE
How to revoke access through gapi.auth2.authorize

### ISSUE THREAD

**Issue by mesqueeb** [google/google-api-javascript-client#402]
Hello community.

Is it currently possible to **revoke consent** through [`GoogleUser.disconnect()`](https://developers.google.com/api-client-library/javascript/reference/referencedocs#googleuserdisconnect) or get the granted scopes through [`GoogleUser.getGrantedScopes()`](https://developers.google.com/api-client-library/javascript/reference/referencedocs#googleusergetgrantedscopes) with just the `gapi.auth2.authorize` option?

I'm having trouble finding out how to access the `GoogleUser` in this case.

**Comment by TMSCH** [comment]
You can revoke the access making an HTTP request to `https://accounts.google.com/o/oauth2/revoke?token={TOKEN}`. See [doc](https://developers.google.com/identity/protocols/OAuth2WebServer#tokenrevoke). Using the client library to revoke token is currently not possible if the tokens were obtained through the authorize method.

You will get the granted scopes in the response to `gapi.auth2.authorize` when requesting an Access Token (`response_type: 'permission'`).
