### ISSUE TITLE
Error: "popup_closed_by_user" on chrome browser

### ISSUE THREAD

**Issue by wjf444128852** [google/google-api-javascript-client#411]
Log in to my test app using google and it will work in any browser, it works on Firefox，IE10。But you will get an error on Google Chrome( Win 32  version:65.0.3325.146)

when clicking on Google sign in and Google sign out buttons will all going wrong!!

[Demo online](https://wjf444128852.github.io/demo01/login/)

**Comment by TMSCH** [comment]
@wjf444128852 I can't repro the issue using Linux / Chrome Version 65.0.3325.181. Could you look at the network tabs for requests to `https://accounts.google.com/...` and copy paste their request URL and responses?

**Comment by wjf444128852** [comment]
![error-google](https://user-images.githubusercontent.com/16033932/38078577-5b897d34-336f-11e8-85ef-8b901e3042f8.gif)
the network does not work on Chrome(win 32 version:65.0.3325.146)
@TMSCH

**Comment by wjf444128852** [comment]
![success-firefox](https://user-images.githubusercontent.com/16033932/38078730-c9172860-336f-11e8-81c1-7f5dd65ad4ef.gif)

it works on Firefox，and any other browser
@TMSCH

**Comment by TMSCH** [comment]
@wjf444128852 in the Chrome 32-bit version, it seems that you have disabled third-party cookies. Could you ensure this is not the case? gapi.auth2.authorize does not work with such config enabled.

**Comment by wjf444128852** [comment]
@TMSCH   I don't know why，but it works on Chrome(win 64  version65)。
Tanks a lot

**Comment by TMSCH** [comment]
@wjf444128852 Go to `chrome://settings/content/cookies` of the Chrome 32-bit on ensure that "Block third-party cookies" option is not enabled. Then try again.

**Comment by wjf444128852** [comment]
@TMSCH  
Ok，i will testing tomorrow！ 
TKS

**Comment by wjf444128852** [comment]
@TMSCH 
Thanks a lot.. Because the setting is disabled！！

**Comment by kienbui2204** [comment]
@TMSCH Thank you very much!
