### ISSUE TITLE
isSignedIn.get() return false after a day signed in on Safari browser

### ISSUE THREAD

**Issue by sirichaij** [google/google-api-javascript-client#415]
I used redirect mode for signIn on Safari browser. It worked fine for first time. About a day I tried to sign in again, isSignedIn.get() always return false.

If I go to google website, and sign out. Then I get back to my website, I will be able to signIn again.

I tried to signOut before calling signIn, but it didn't help.

It only happened on Safari, but not Google Chrome.

**Comment by TMSCH** [comment]
What Safari version are you using? On Desktop or mobile?

Le dim. 1 avr. 2018 à 19:46, Sirichai Jansamak <notifications@github.com> a
écrit :

**Comment by kongguibin** [comment]
close the bug due to no response.
