### ISSUE TITLE
Logo is not in the correct position

### ISSUE THREAD

**Issue by horid121** [google/google-api-javascript-client#416]
[Steps to reproduce]
1. Logout all google accounts.
2. Visit "https://document.collavate.com/". This is our application.
3. Click "Sign in with Google" button on right side.
3. You can see the problem.
<img width="644" alt="2018-04-08 6 21 43" src="https://user-images.githubusercontent.com/3009060/38465669-ba762486-3b59-11e8-8968-6c37fd05bdff.png">

I'm using Mac OS and almost browsers are affected.

**Comment by TMSCH** [comment]
Thanks for the report, we're working on a fix.

**Comment by horid121** [comment]
@TMSCH It's fixed.
