### ISSUE TITLE
Gapi login doesn't work in Edge

### ISSUE THREAD

**Issue by ingridtartaglia** [google/google-api-javascript-client#417]
Hello,

I'm having some issues when I try to login using Google Signin custom button.
This issue could be reproduced in Microsoft Edge 40.15063.674.0.
I'm using a `https` protocol and I'm not blocking any cookies. 
This issue doesn't happen when I'm in inPrivate mode.

Here is my code:

1- I put the following code in my index.html, inside <head> tag:
```html
<script src="https://apis.google.com/js/api:client.js"></script>
```

2- I'm using AngularJS (v1.6.x) so I've decided to load and init Gapi on `app.run`:
```js
$window.gapi.load('auth2', function() {
     console.log('gapi loaded');
     $window.auth2 = $window.gapi.auth2.init({
          client_id: 'my_id_here'
     }).then(function(){
          console.log('gapi initialized');
     });
});
```
PS: the second `console.log` is not working in Edge, but it works in other browsers.

3- I created a custom button and set a login function in my controller:
```html
<md-button
     type="button"
     class="c-button--google"
     ng-click="vm.loginByGoogle()">
     <img class="c-button__image" src="img/icon-google.png">
     Google
</md-button>
```
```js
vm.loginByGoogle = function() {
     var googleAuth = $window.gapi.auth2.getAuthInstance();

     googleAuth.signIn().then(function(resp) {
          // ...
     });
}
```

Every time I load my application using Edge and try to click on the login button, a Google popup is opened, but when I login into Google and the popup closes, I've found this Gapi error in the browser's console:

![image](https://user-images.githubusercontent.com/12486985/38515094-909868ee-3c09-11e8-9479-c0dfabfeebb4.png)

It would be nice if someone can help me, please :)
Thanks!

**Comment by TMSCH** [comment]
@ingridtartaglia could you see what is the content of the error returned by gapi?

**Comment by ingridtartaglia** [comment]
@TMSCH 

The error occurs in line 1362, according to the console:

![image](https://user-images.githubusercontent.com/12486985/38575365-a206a906-3cd1-11e8-9912-7a5d3a3ef364.png)

**Comment by mamsori** [comment]
I'm having same issue.
@ingridtartaglia Did you find any solution for this issue?
