### ISSUE TITLE
gapi.auth2.authorize throws "popup_closed_by_user", when only single google ID is logged in.

### ISSUE THREAD

**Issue by rajatsingla** [google/google-api-javascript-client#421]
```js
  window.gapi.auth2.authorize({
    'client_id': '...<client_id>',
    'scope': 'email profile openid',
    'response_type': 'id_token permission'
  }, (response) => {
    successCallback(response);
  });
```
Using above code to intialize gapi.auth2.authorize

**Scenarios**
- When multiple accounts are logged in, it opens window for choosing account and all works well.
- **When only one account is logged in, It opens window and immediately closes and throws error "popup_closed_by_user"**
- Trying again without refresh, it works.
- Using `prompt: consent`, all works fine in first try even with single logged account.

Laptop- mac air
OS- macOS sierra
browser- Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by kongguibin** [comment]
Can you remove the 'permission' in the response_type and try again?

**Comment by rajatsingla** [comment]
**No**, Removing 'permission' in the response_type didn't made any difference.

**Comment by kongguibin** [comment]
Deployed your code to https://gapi-idp.appspot.com/gapi.html, and tested it with one account logged in.
Cannot reproduce the bug.

As mentioned in https://github.com/google/google-api-javascript-client/issues/431, can you please check whether popup-blocker installed in your browser. Otherwise, please provide detailed platform information and steps to reproduce the bug.

**Comment by rajatsingla** [comment]
Your demo seems to be working fine.

But in my demo(https://rajatsingla.github.io/scroll_demos/gapi_demo.html) **without** 'prompt: consent' option, window is closed automatically and on random occasions it throws error 'popup_closed_by_user'

Code is almost same, except i am using $.getScript to load 'platform.js'

I have checked for popup-blocker installed and found none.

**Comment by rajatsingla** [comment]
https://rajatsingla.github.io/scroll_demos/gapi_demo_2.html 

Used <script> tag, but same issue.

**Comment by kongguibin** [comment]
Compared to your latest demo, my demo doesn't have the 'permission' in the response_type. That's the only difference.

**Comment by rajatsingla** [comment]
Is this(https://rajatsingla.github.io/scroll_demos/gapi_demo_2.html) working fine in your browser

For (GSI) button

**Comment by kongguibin** [comment]
you demo works fine in my browser, except one small issue in your code; for the immediate mode, you should put 'prompt: none'.
