### ISSUE TITLE
Longer authorization period with `gapi.auth2.authorize`?

### ISSUE THREAD

**Issue by mesqueeb** [google/google-api-javascript-client#424]
Dear community,

I currently do a manual `gapi.auth2.authorize` for each of my user's accounts that they linked.
I save each accessToken on the user object per account they have linked.
Before every API call I do `gapi.client.setToken` to make sure the API call is authenticated and set to the correct account.

Whenever an API fails because of invalid credentials, my app tries to `authorize` again and retrieve a new accessToken and automatically tries the same api call again.

**Questions:**
1. I think the accessToken is only usable for an hour? Is there any way to make this longer? (e.g. 24 hours) (is this safe?)
2. I save the accessToken to my firestore (firebase database) as well. Is this dangerous?
(however, I can't really use it when retrieving from the firestore anyway, because it's always already expired...)

**Comment by kongguibin** [comment]
for question 1: No due to security reasons, you cannot set the lifetime of an access token.
for question 2: Can you try the OAuth server flow, and store a refresh token to firestore?https://developers.google.com/identity/protocols/OAuth2WebServer

**Comment by mesqueeb** [comment]
@kongguibin The problem is, I have no serverside logic. Because I use firebase, so everything is written front end. So how can I try the "OAuth server flow" you mention?

The URL you gave me just points to the Google API Javascript client, which I'm already using. I'm using gapi to manually authorise api calls from my users with `gapi.auth2.authorize`.

**Comment by kongguibin** [comment]
can you try the SignIn API (instead of the authorize() API)? The access token will be automatically refreshed.
https://developers.google.com/identity/sign-in/web/sign-in.

**Comment by mesqueeb** [comment]
@kongguibin Thanks for your suggestion. However, my users have multiple google accounts authorised in my calendar app. With events from every google account on 1 page. Therefor the only possibility is to use the `gapi.auth2.authorize` method.
