### ISSUE TITLE
gapi.auth2.init stops DeviceMode from working when refreshing page

### ISSUE THREAD

**Issue by orizens** [google/google-api-javascript-client#430]
## Steps to reproduce the problem:
1. open https://oauth.googleusercontent.com/robots.txt
2. open devtools 
3. switch Device Mode On ( command + shift + M) 
4. choose a desktop resolution (1200x800, 1440x900 or any custom desktop resolution) - if not exist in dropdown - create one
5. paste this code (from the github issue https://github.com/google/google-api-javascript-client/issues/392#issuecomment-366363420)  
6. press enter key to execute the code

## What is the expected behavior?
the emulated device mode still shows the same resolution. 
my inspection shows that gapi.auth2.init use "document.head.insertBefore" to inject scripts - which in turn, causes the issue.

## What went wrong?
the emulate device mode is disregarded and chrome treats the emulated screen area as a small screen without the emulated resolution .  

## demos
> available at https://bugs.chromium.org/p/chromium/issues/detail?id=837652

google-content-example demonstrates the above issue.
echoes-player-example demonstrates the same issue with my open source project - http://echoesplayer.com (no need to execute any code) - open devtools, pick a resolution and refresh the app to see the bug. 

Chrome version: 66.0.3359.117  Channel: stable
OS Version: OS X 10.13.4

**Comment by StevenEWright** [comment]
Hey @orizens,

Sorry for possibly repeating questions, but could you help me get up to speed on the problem you're refering to so that I can make sure I'm fully understanding your issue?

It looks like the issue you've referred to suggests this may be a Chrome dev tools issue. Could you comment on your thoughts about this?

Thanks!

**Comment by orizens** [comment]
hi @StevenEWright 

the issue is described well in this comment https://bugs.chromium.org/p/chromium/issues/detail?id=837652#c11
It could be easily reproduced with http://echoesplayer.com as well. 
a screencast is attached to it. 
It is fixed with Chrome Version 67.0.3396.99 (that's the version i'm running at the moment). 

Thanks for reviewing.
