### ISSUE TITLE
Error popup_closed_by_user from gapi.auth2.authorize   

### ISSUE THREAD

**Issue by clokviantinc** [google/google-api-javascript-client#431]
Hi,

We have been getting popup_closed_by_user error from gapi.auth2.authorize.

Steps to reproduce popup_closed_by_user error, in the rate of about 30-60% of the time:
1.	Open chrome
2.	Go to gmail.com and log into gmail with an account (the purpose is to log into Google already with one account only).  Make sure that only one account is signed in.  If you have multiple accounts signed in, make sure that you signed out from all but one account.
3.	Go to login.jsp (code snippet below), click LOGIN button.  30-60% of the time, you will get popup_closed_by_user error. Sometimes, clearing file cache first from Chrome will help to better the chance of getting this error.
4.	After you got this error, if you click LOGIN button the second time, this error will be gone.
5.	To repeat the test, you need to hit the refresh button on the browser.

This is the code snippet from login.jsp:

```
<input onclick="doAuth();" value="LOGIN" type="button"/>
    <script>
	    function init() {
	        gapi.load('auth2', function() {});
	    }

        function doAuth() {
            config = {
				'client_id': '<client id>',
				'scope': 'email https://www.googleapis.com/auth/bigquery'
			};
	        gapi.auth2.authorize(config, function(info) {
	            if(info && info.error) {
	                alert(info.error);
	                return;
	            } else if(!info || !info.access_token) {
	                alert("no access token");
	                return;
	            } else {
	             alert("ok");
	            }
	        });
        }
    </script>
	<script src="https://apis.google.com/js/platform.js" async defer
		onload="this.onload=function(){};init()"
		onreadystatechange="if (this.readyState === 'complete') this.onload()">
    </script>

```
In order to see what is going on, I have a way to make this error occurs 100% of the time.  This is how.

-	Open up Developer Tool > Sources
-	Open this js file in pretty-print format:  apis.google.com > cb=gapi.loaded_0
-	Put two breakpoints at:

```
QD.prototype.open = function(a, c, f, g) {
        TD(this); <- PUT FIRST BREAK POINT HERE
        this.B$ ? (this.u1 && (this.u1(),
        this.u1 = null),
        FF(this)) : this.B$ = "authPopup" + Math.floor(1E6 * Math.random() + 1);
        a: {
            this.h8 = this.Jr.open(a, this.B$, c);
            try {
                if (this.h8.focus(),
                this.h8.closed || "undefined" == typeof this.h8.closed)
                    throw Error("pa");
            } catch (h) {
                g && (0,
                window.setTimeout)(g, 0);
                this.h8 = null;
                break a
            }
            f && (this.u1 = f,
            PF(this)) <- PUT SECOND BREAKPOINT HERE
        }
    }
```

-	Put the third breakpoint at:

```
Tz = function(a, c) {
        a.ija && window.clearTimeout(a.ija);
        a.ija = window.setTimeout(function() {  <- PUT THIRD BREAKPOINT HERE
            a.X4 == c && (a.ija = null,
            a.X4 = void 0,
            a.k8({
                authResult: {
                    error: "popup_closed_by_user"
                }
            }))
        }, 1E3)
    }
```

Now, with the 3 breakpoints, repeat the test (you have to refresh after each test).  Now you see the error 100% of the time.

Would you please advise?

Thank you.

**Comment by kongguibin** [comment]
1). I copied your code to https://gapi-idp.appspot.com. I cannot reproduce the issue.

2). I set the three breakpoint as you mentioned, still failed to reproduce the issue. The popup will be displayed after the first breakpoint.

Based on your description, I think you should have an ad blocker installed on your Chrome browser. Please disable it, or use another machine/browser to test.

**Comment by clokviantinc** [comment]
Hi kongguibin,

During the test, the popup should not appeared if you have already signed into Google with just one account.  In this case, the popup will not show because you are already signed in, and with only one account.  

Could you please confirm if this is what you have tested?

Thank you.

**Comment by kongguibin** [comment]
short answer: Actually, for your code, the popup will be displayed again. You need to set 'prompt=none' to try to get an access token in the immediate way/mode.

long answer: 1. gapi.auth2.authorize() method can work in two modes: immediate and non-immediate. For immediate mode, you need call it with 'prompt=none' : gapi.auth2.authorize({prompt: 'none', .... }, callback), which will try to load an access token without any user actions.
For non-immediate mode, the popup will always open.

2. GSI library cannot try non-immediate firstly, then try immediate if failed, due to below reason:
Browsers (note: not ad-blocker plugins) will block a popup if it's not triggered by user direct actions. An async callback of a user direct clicking (which is the case for GSI immediate mode, since it needs to load a hidden iframe) cannot open an new tap/window any more.  More details: https://javascript.info/popup-windows

3. Thus, it's developers responsible to decide whether immediate mode or non-immediate mode should be used. Normally, you can try the immediate mode on page loading. If succeed, you can try to login automatically; Otherwise, you display the "Sign in with Google" button, which will trigger the non-immediate flow when clicked.

Back to your issue:
1. for your code, the popup will be displayed again.
2. after a flashing popup, I always get the access token.
3. Thus, i guess your Chrome has an ad/popup blocker/plugins.
Please check.

**Comment by clokviantinc** [comment]
Hi kongguibin,

I am applying your suggestion from #3, that is first to set prompt=none.  If fails, retry with prompt=undefined.

During the retry with prompt=undefined, I am getting the error popup_closed_by_browser.  Could you please suggest a way to do retry to prevent this second error?

Here is the code:

```
<input onclick="doAuth(true);" value="LOGIN" type="button"/>
    <script>
	    function init() {
	        gapi.load('auth2', function() {});
	    }
        function doAuth(noPrompt) {
            var config = {
				'client_id': '<client id>',
				'scope': 'email https://www.googleapis.com/auth/bigquery https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/cloud-platform'
			};

			if(noPrompt === true){
                config.prompt = 'none';
            }
	        gapi.auth2.authorize(config, function(info) {

	            if(info && info.error) {
	                alert("err1" + info.error);
	                if(info.error == 'immediate_failed'){
	                    doAuth(false);
	                }
	                return;
	            } else if(!info || !info.access_token) {
	                alert("err2 no access token");
	                return;
	            } else {
	             alert("ok=" + info.access_token);
	            }
	        });
        }
    </script>
	<script src="https://apis.google.com/js/platform.js" async defer
		onload="this.onload=function(){};init()"
		onreadystatechange="if (this.readyState === 'complete') this.onload()">
    </script>
```

Thank you.

**Comment by kongguibin** [comment]
Deploying your new code to http://gapi-idp.appspot.com/. It works as expected. Can you try that URL from your browser?

As mentioned before, I think your Chrome has an ad/popup blocker/plugins installed. Please use another device/browser to test.

**Comment by clokviantinc** [comment]
Hi kongguibin,

I have confirmed that my chrome does not have ad/popup blocker/plugins installed.

When I sent you the latest code on 5/4, my chrome version was 65.0.3325.181 (Official Build) (64-bit).  
And with that, I was still having issue as described.

But since then, I have restarted chrome and now my chrome version has been updated to 66.0.3359.139 (Official Build) (64-bit).  With this new version of chrome, I tested again the latest code, and now it is working fine without issue.  Confirming that the fix with "immediate mode/then non-immediate mode" is working.

Would you please confirm if indeed the new chrome version fixes this bug, as I have no way of confirming this because I cannot rollback my chrome to the older version?

Thank you.

**Comment by kongguibin** [comment]
Good to know the bug is fixed.
I don't think that all Chrome 65 users cannot use GSI. Or maybe your running Chrome instance had some problems?

**Comment by clokviantinc** [comment]
Hi kongguibin,

I have a question about the fix.  The fix is to first set config.prompt='none', then when we encounter 'immediate_failed' error, call gapi.auth2.authorize again with config.prompt=undefined.

This fix works when only one account has logged into Google.

But we have the following use case and this fix will not work for us.  The use case is, when more than one accounts have logged into Google.

In this case, we want the user to be able to select which account to authorize.  However per this fix, we set config.prompt='none', so the user will not have a chance to select which account.  

Would you please advise how we can address this use case?

Thank you.

**Comment by kongguibin** [comment]
You can put a "Switch Account" link somewhere(, maybe after the username of current user in your page).
Once clicked, you can call  gapi.auth2.authorize with prompt=select_account. More details at: https://developers.google.com/identity/sign-in/web/reference#gapiauth2signinoptions
