### ISSUE TITLE
I copy and pasted the below code in my login page of my web app but i dont get the sign in button can anyone help ? Thanks in advance

### ISSUE THREAD

**Issue by sk2111** [google/google-api-javascript-client#433]
<html lang="en">
  <head>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="MYclientid.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
  </head>
  <body>
    <div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
    <script>
      function onSignIn(googleUser) {
        // Useful data for your client-side scripts:
        var profile = googleUser.getBasicProfile();
        console.log("ID: " + profile.getId()); // Don't send this directly to your server!
        console.log('Full Name: ' + profile.getName());
        console.log('Given Name: ' + profile.getGivenName());
        console.log('Family Name: ' + profile.getFamilyName());
        console.log("Image URL: " + profile.getImageUrl());
        console.log("Email: " + profile.getEmail());

        // The ID token you need to pass to your backend:
        var id_token = googleUser.getAuthResponse().id_token;
        console.log("ID Token: " + id_token);
      };
    </script>
  </body>
</html>

**Comment by kongguibin** [comment]
You only copied the JS code. You need to create a button in your HTML code.

https://developers.google.com/identity/sign-in/web/sign-in
https://developers.google.com/identity/sign-in/web/build-button

**Comment by sk2111** [comment]
Thankyou very much
