### ISSUE TITLE
exit beta

### ISSUE THREAD

**Issue by Offirmo** [google/google-api-javascript-client#435]
This lib reached beta in 2012.

Maybe it's time to reach stable?

**Comment by bochunz** [comment]
This lib has reached stable in 2016.

**Comment by grant** [comment]
I think this issue references the "This library is in Beta" notice in the README and would like that notice to be updated.

**Comment by Offirmo** [comment]
@bochunz yes, @grant got it right. The README has a huge mention of being in beta, that's what I was referring to.

**Comment by bochunz** [comment]
Oh you are right @grant and @Offirmo. We forgot to update the README when we declared stable. I've just removed it.
