### ISSUE TITLE
Can not call gapi.auth.authorize with immediate: false followed by immediate: true (if 1st auth fails)

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#44]
_From [benjamin...@gmail.com](https://code.google.com/u/112679240283582629849/) on July 31, 2012 23:16:05_

Hi all,
i'm trying to build a function, called when a button needing a google api feature is clicked. The function :
1) check the oauth token state using gapi.auth.authorize with immediate: false
2) if auth fails (because user is disconnected from google) call gapi.auth.authorize with immediate: false to display the login dialog.

I'm testing using Chrome.
gapi.auth.init is called correctly.

Result:

if the function do only 2) it works perfectly. No popup blocker stops the popup. But if the user is connected and the app is authorized a popup is always displayed and closes automatically (it flickers). On iPhone this opens a new safari window which diseappar quickly.

if the function do 1) and the user is already connected and the app authorized it works perfectly. No popup is displayed.

if the function do 1) and auth fails, then do 2), the popup blocker is always blocking the auth popup.

There is no problem with the facebook api which does the same (method:  FB.getLoginStatus with second parameter set to true).

Any idea ?

Code:

```
        gapi.auth.authorize({ client_id: GaHelper.clientId, scope: scopes, immediate: false }, 
            function(authResult) {
                if(authResult && !authResult.error) {
                    //auth ok
                } 
                else {
                    gapi.auth.authorize({ client_id: GaHelper.clientId, scope: scopes, immediate: false },
                        function(authResult2) {
                            if(authResult2 && !authResult2.error)
                                //auth ok
                        }
                    );
                }
            }
        );
```

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=44_

**Comment by TMSCH** [comment]
`gapi.auth` has been deprecated, and `gapi.auth2` will now automatically sign in the user on initialization, if they were previously signed in. It also detects sign in/sign out from other tabs. As the issue has been resolved in the v2, closing this.
