### ISSUE TITLE
gapi.auth2.authorize  authorization code  doesn't return refresh token 

### ISSUE THREAD

**Issue by Jasemalsadi** [google/google-api-javascript-client#443]
Hi, 
I have a website that require multiple client id to get offline access to youtube Analytics API. I front Side I am using: 
 gapi.auth2.authorize 
As it covers the use case of multiple client id.   I an **response_type**, I am passing **code** and the **token** .  Example of the parameters : 

{
 client_id: "the client id",
'scope': " the sope",
 'prompt': 'select_account',
'response_type': 'code token',
 }

 I use  authorization code  that return it to exchange it in the server side to get the access token and refresh token . 
However, It doesn't contain a refresh token, I used the PHP  method  **fetchAccessTokenWithAuthCode**

**Comment by kongguibin** [comment]
To get a refresh token, you should put 'access_type': 'offline' in your options.

**Comment by Quintenps** [comment]
I'm having the same issue, I've set "setAccessType('offline');". Am I missing something?
