### ISSUE TITLE
Cannot read property 'postMessage' of null with server render.

### ISSUE THREAD

**Issue by truonglocbinh** [google/google-api-javascript-client#444]
I create a login page and add button sign in . When I click sign in button I will authorize and send data to server , if data is good I redirect user to my home page. When I sign out I redirect to sign in page. But when I click sign in button again , it doesn't working and show a error 'Uncaught TypeError: Cannot read property 'postMessage' of null'. I must reload sign in to continue use function.

**Comment by StevenEWright** [comment]
Hey @truonglocbinh,

I have a few follow up questions for you...

Just to be sure I understand the symptoms; is the error occurring on the same page on which you've placed the sign in button? (I.e. it's not occurring within the popup, right?)

May I know which browser you are using?

Are you requesting offline access?

Also, are you using any overrides for `redirect_uri`?

Thanks!

**Comment by kongguibin** [comment]
Closed due to no response.
