### ISSUE TITLE
Sign in with multiple accounts and redirect not working as expected

### ISSUE THREAD

**Issue by klevismino** [google/google-api-javascript-client#446]
Hello

I am currently having an issue authenticating users with 
```
gapi.auth2.getAuthInstance().signIn({
  app_package_name: 'package.name.com',
  prompt: 'select_account',
  scope: 'profile email',
  ux_mode: 'redirect'
}).
```
The first time I can sign in without any issue (let's say using user1@gmail.com). For instance `gapi.auth2.getAuthInstance().isSignedIn.get()` has the value of true.
After that, the users signs out. I call 'https://accounts.google.com/logout' on a new tab because I want to completely logout from Google. I don't use `gapi.auth2.getAuthInstance().signOut()` because it only signs out of the current application.

When starting the sign in process over, this time with another user (user2@gmail.com) `gapi.auth2.getAuthInstance().isSignedIn.get()` has the value false. I don't understand why.

If I try again with the first user (user1@gmail.com) then the user is signed in properly.
As a conclusion **only the first user can be signed in.**

If I change the sign in  options with ux_mode: 'popup', this issue does not happen.
As a conclusion **redirecting causes the issue**

Additional information:
After signing in with ux_mode: 'redirect' and signing out with  `gapi.auth2.getAuthInstance().signOut()`, I cannot login with any user.

@TMSCH I hope you have time to check this out.

**Comment by StevenEWright** [comment]
Hey @klevismino, 

I'm having trouble replicating this problem. The only thing different from my test and the flow you're reporting is your inclusion of the `app_package_name` in the sign in options. Do you think you could possibly test without that temporarily just to confirm that it is not the source of any issues?

If the behavior is the same, perhaps you could create a minimal sample in a repo and link to it here?  

The flow I used to try and repro is:

0.) Start with no users signed in on google.com

1.) Initiate a Sign In via my sample app with:

```
      gapi.auth2.getAuthInstance().signIn({
        prompt: 'select_account',
        scope: 'profile email',
        ux_mode: 'redirect'
      });
```

2.) Check value of `gapi.auth2.getAuthInstance().isSignedIn.get()` (it returns `True`, as expected).

3.) Sign out user via `window.open('https://accounts.google.com/logout')`

4.) Refresh sample app and confirm no one is signed in.

5.) Initiate Sign In as in step 1, but sign in with a different user.

6.) Check value of `gapi.auth2.getAuthInstance().isSignedIn.get()` (it still returns `True`, as expected).

Please let me know if I misunderstood your case.

Thanks!

**Comment by klevismino** [comment]
Hello @StevenEWright

Thanks for replying. You perfectly understand the scenario. I created a new project, implemented the gapi authentication, but could not replicate the issue. It seems that something else has influence in this matter. I will further investigate and let you know of my findings.

Cheers!

**Comment by klevismino** [comment]
Hello @StevenEWright 

I found out that the problem occurs only when I use the AngularJS  [ui router](https://ui-router.github.io/ng1/). I haven't found a solution yet. I noticed that after logging in, a parameter id_token is automatically added to the URL. If you could share with me any information on how the GAPI redirect works, that would be helpful.
