### ISSUE TITLE
Feeds for Tasks

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#45]
_From [ishaan.puniani@gmail.com](https://code.google.com/u/ishaan.puniani@gmail.com/) on August 07, 2012 08:27:40_

hi 
As i see there are many applications provide feeds to get the data from server but there is no such option available for the Task api . if possible please provide such option for Task api.
also there is no elobrated samples available for using task api in javascript you can also introduce such things 

Thanks

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=45_

**Comment by grant** [comment]
Specific to Tasks API.
