### ISSUE TITLE
iOS PWAs cannot use Google Javascript login client

### ISSUE THREAD

**Issue by LukeWood** [google/google-api-javascript-client#458]
Hey all,

Apparently this is disabled due to some security concerns - are there any known workarounds to this?

I dug through the docs to see if there was a redirect option but didn't see anything.

Apologies if this is a well documented issue with a solution - I looked around a bit but didn't find anything regarding this.

**Comment by kongguibin** [comment]
See https://github.com/google/google-api-javascript-client/issues/473.
GSI should work on both iOS and Android PWA apps .
