### ISSUE TITLE
Use floating DIV instead of new window popup?

### ISSUE THREAD

**Issue by knoxcard** [google/google-api-javascript-client#459]
Can a floating DIV be used instead of a popup for the account chooser window?
Popups reminds everyone of malware and ads.

Here is an example, go here:  https://developers.google.com/identity/sign-in/web/sign-in
Click on the "Configure Project" button.

So this hover layer would instead show..."Which gmail account would you like to use to login?"

**Comment by knoxcard** [comment]
So the included google_platform.js file would just append to the body tag...position: fixed...
fade out the background with an opacity layer ...

**Comment by knoxcard** [comment]
Here is an exampe, click on "Configure Project"
https://developers.google.com/identity/sign-in/web/sign-in

So this popup would show...which gmail account would you like to use to login?

**Comment by knoxcard** [comment]
Even better yet, being able to target an iframe so one can load the user account logins on the same page.

**Comment by bochunz** [comment]
I think the login window need to be hosted on google.com and we require custom JS should not be able to temper with the content in the window. At best, maybe this is doable with a visible iframe. Floating DIV is certainly not going to be secure, IIUC.

**Comment by knoxcard** [comment]
how about a iframe inside of a floating div? BINGO!

**Comment by knoxcard** [comment]
Nevermind, today I finally got the `redirect_uri` deal working!  So no more popup, it's great
