### ISSUE TITLE
Google Search API - Result limit of 100 Results

### ISSUE THREAD

**Issue by viertel** [google/google-api-javascript-client#460]
Hello together,

I am using the Google Search API with PHP. 
Is it possible to use the google search without an result limit? I get 4000 results for my search but I am only able to look into 100 of it via changing "start"-parameter. The payed version has still the result limit - right?
So what I can do to receive all results of my search?

Greetings,

**Comment by grant** [comment]
Hi @viertel, this is the JavaScript client library. I would suggest filing an issue with a PHP repo that is more relevant to the Search API.
