### ISSUE TITLE
CORS request fail while trying to download file using exportUrl - Drive API

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#47]
_From [karthik....@gmail.com](https://code.google.com/u/113205496777284472241/) on August 19, 2012 05:58:47_

What steps will reproduce the problem? If possible, provide a live demo of the issue. 1.Go to http://makkarlabs.in/badgeit and click on start(authentication happens).
On the next page, I am able to select an image from my drive and load into the doc (here I use the "downloadUrl" returned by the object).
Whereas when I try to do the same with the "exportUrl" returned by the gapi request method I am getting cross origin error. What is the expected output? What do you see instead? I expect the file to be downloaded since Google APIs support CORS.
Instead I see 
XMLHttpRequest cannot load https://docs.google.com/feeds/download/spreadsheets/Export?key=file-key&exportFormat=csv&access_token=my_access_token . Origin http://makkarlabs.in is not allowed by Access-Control-Allow-Origin. What version of the product are you using? On what operating system? Am on latest version of Chrome.
Windows 7 OS Please provide any additional information below.

**Attachment:** [errorscreenshot.png](http://code.google.com/p/google-api-javascript-client/issues/detail?id=47)

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=47_

**Comment by johannesjo** [comment]
Is there any other way to make downloading files work?
