### ISSUE TITLE
Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation'

### ISSUE THREAD

**Issue by knoxcard** [google/google-api-javascript-client#470]
`Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.`

**Comment by agroupp** [comment]
Have this issue too starting from today.

**Comment by aljaxus** [comment]
Also having this issue :/

**Comment by aljaxus** [comment]
Could be a new 'build' of the JS library?
*shrug*

**Comment by wasyyyy** [comment]
It seems this attribute is required for Safari's Storage Access API.
https://webkit.org/blog/8124/introducing-storage-access-api/

By the way this issue has been fixed and I don't see this error any more.

**Comment by knoxcard** [comment]
Closing ticket...
