### ISSUE TITLE
Google Sheets Api 

### ISSUE THREAD

**Issue by yasmine2410** [google/google-api-javascript-client#471]
google.html:82 Uncaught TypeError: Cannot read property 'signIn' of null
    at handleSignInClick (google.html:82)
    at HTMLButtonElement.onclick (google.html:4)

**Comment by llccrr** [comment]
Having the same issue.
I copy/past the sample, replace credentials and having the same issue.

**Comment by grant** [comment]
Which sample is this?

**Comment by grant** [comment]
Closed due to inactivity.
See this link for working samples:
https://github.com/gsuitedevs/browser-samples
