### ISSUE TITLE
Batch request returns 401

### ISSUE THREAD

**Issue by Viatorus** [google/google-api-javascript-client#481]
Doing two or more requests in one batch at once leads to a 401 for each request.

```
const batch = gapi.client.newBatch();
batch.add(gapi.client.drive.files.list());
batch.add(gapi.client.drive.files.list());
batch.then((e) => {
  console.log(e);
});
```

The error is:
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
```

Removing one _batch.add_ works perfectly fine.

Why? What do I do wrong?

**Comment by grant** [comment]
It looks like you have invalid credentials. Be sure you are passing the access token.

See this example for Drive:
https://developers.google.com/drive/api/v3/quickstart/js

This issue tracker isn't for asking about specific issues. Thus, I'm closing.
