### ISSUE TITLE
OAuth 2.0 Scopes for Google Maps APIs

### ISSUE THREAD

**Issue by kevalshah90** [google/google-api-javascript-client#484]
We are a 3rd Party site looking to access data collected by google maps application. It appears that OAuth 2.0 Scope documentation / support exists for Drive, Docs and other Google Products, however, not for Maps. 

With Google Web Sign In how can users share their data collected by google maps application with 3rd party sites looking to offer them valuable services.

**Comment by grant** [comment]
Which Google Map API?
I believe most of the APIs do not support OAuth. Use Client IDs and API Keys instead.

https://developers.google.com/maps/premium/previous-licenses/clientside/auth
