### ISSUE TITLE
An error such as indexOf not supported appears.

### ISSUE THREAD

**Issue by nahtemf** [google/google-api-javascript-client#486]
If the document mode of IE 11 is 5, you will receive an error stating that indexOf is not supported in the file "3747252869 - v2 - idpiframe.js".
(Because we are using the API on the regacy system, we are operating document mode 5)
Please let me know the causes and measures of this error.

![2018-12-06 18 48 14](https://user-images.githubusercontent.com/13199503/49576389-6a5abc80-f988-11e8-8d46-73fc0f54cbe2.png)

**Comment by sergentj** [comment]
Sorry for not responding to this in a timely fashion. I think you're saying that you are using IE11 compatibility modes to emulate older browsers. We don't test with or support these older compatibility modes in IE.
Sorry I don't have another solution for this.
