### ISSUE TITLE
Error popup_closed_by_user in private mode of Chrome on iOS

### ISSUE THREAD

**Issue by chaupvtadi** [google/google-api-javascript-client#493]
I'm trying to implement "Sign in with Google Account" feature by using gapi.

When I test my app in private (incognito) mode of Chrome v71.0.3578.89 on iOS 12.1, it always returns "popup_closed_by_user" for me.

Everything worked well If I run the app in the normal mode of Chrome on iOS.

**Comment by alicescfernandes** [comment]
According to the google documentation on the sign in, the "Google Sign-in is currently not supported in incognito mode on Chrome on iOS."

**Comment by chaupvtadi** [comment]
@alicescfernandes Thank you for your reply.
