### ISSUE TITLE
CSP causes the sign in popup to close with error

### ISSUE THREAD

**Issue by alicescfernandes** [google/google-api-javascript-client#494]
Hi there.
I'm having this issue with some browsers, including firefox 64 and chrome Version 71.0.3578.98 (Official Build) (64-bit). I'm using one of the exampes given in the quickstart for the google sign in, and for both browsres, i have the option to allow third party cookies active.

Now, time to time i get that same error, and one thing that i've noticed is this CSP header from the iframe 
![screen shot 2018-12-27 at 17 47 48](https://user-images.githubusercontent.com/15971182/50489732-2c8a0a80-0a01-11e9-85d0-0c70370e6d96.png)

Every time this shows up, i get the error:

![screen shot 2018-12-27 at 17 48 07](https://user-images.githubusercontent.com/15971182/50489746-47f51580-0a01-11e9-9029-89a4bdab0ac9.png)

The iframe so happens to be the url of the iframe, that in an instant opens and closes

Any tips on how to fix this?

**Comment by grant** [comment]
Not sure, it may be a config with your browser or operating system.

**Comment by grant** [comment]
Yes. Using a server-side client fixes many of the problems experienced with this library.

**Comment by sergentj** [comment]
Sorry for the extremely tardy reply, but I don't think this is reproducible any more.
Please note that in some cases you may see CSP warnings from report-only mode that are merely warnings instead of actual blocking errors.
Please feel free to reopen if this is still a reproducible bug.
