### ISSUE TITLE
JS Client does not work in Gadget setting

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#5]
_From [obr...@google.com](https://code.google.com/u/113534154213782223567/) on December 20, 2011 11:19:40_

What steps will reproduce the problem? 1. Include the JS Client in a Gadget
2. Load the Gadget (iGoogle, Calendar, etc.). What is the expected output? What do you see instead? Expected: Calls using the JS Client work as usual.
Actual: JS error in the console, and the JS Client calls (gapi.client._, gapi.auth._) do not work.

Sample JS Error (IE9):

SCRIPT5009: 'GP_D' is undefined 
d=1, line 171 character 466 
SCRIPT5007: Unable to get value of the property 'authorize': object is null 
or undefined 
www.google.com&libs=core:core.io:core.iglegacy:auth-refresh&is_signed..., 
line 156 character 3

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=3_

**Comment by grant** [comment]
Gadgets are deprecated.
