### ISSUE TITLE
Building google add-ons for doc files

### ISSUE THREAD

**Issue by dharamgoyallsn** [google/google-api-javascript-client#500]
Hi,
i am trying to develop google add-ons almost it's already done, when i getting access token using
```js
gapi.load("client:auth2", function() {
      gapi.auth2.init({client_id: '<client_id>'});
 });
```
and passing that token in header to export google drive file using  gapi.client.drive.files.export method it's working as expected but if i share my doc to other and do same thing using who's account then getting origin issue
i set javascript origin in console 
```
origin: https://n-7x3isqjjteft3mjfvl2mimyt2jybyz72pefibra-1lu-script.googleusercontent.com
```
it's working for my account but not other please let me know how can i resolved this issue?

**Comment by grant** [comment]
I don't think this is a supported feature with Google Docs Add-ons.

The fact that the origin is a different URL when shared with a different user is a part of the Google Doc add-on.

I think you'll need to re-login or use a different gapi client if you use a different Google Account.
