### ISSUE TITLE
Get ID Token from Access Token within a Chrome Extension

### ISSUE THREAD

**Issue by jonluca** [google/google-api-javascript-client#508]
I'm attempting to get an `id_token` from the `access_token` in a chrome extension context. 

I'm using both the standalone Google Javascript Library and the `chrome.identity` Chrome Extension API. This is due to the fact that the Google JavaScript library cannot be included on internal chrome extension HTML pages due to an Invalid Cookie Policy (explained further down below).

My current flow is as follows:

My `manifest.json` has the following keys:

```js
"oauth2": {
  "client_id": "<clientid>.apps.googleusercontent.com",
    "scopes": [
    "openid",
    "profile",
    "email"
  ]
},
"key": "<key from installed version>"
```

Then in my `signin.html` page I have the following script:

```js
chrome.identity.getAuthToken({
  interactive: true
}, // Interactive popup, call back below called upon success
(token) => {
  if (!token) {
    return;
  }
  const tokenObj = {
    access_token: token
  };
  gapi.client.setToken(tokenObj);
  gapi.auth.setToken(tokenObj);
  gapi.client.request({
    path: 'https://www.googleapis.com/oauth2/v1/userinfo?alt=json',
    client_id: GAPI_CLIENT_ID
  }).then((response) => { // this works and returns a valid profile
    const profile = response.result;
    populateProfile(profile);
  });
});
```

I am able to successfully get `token` from the `chrome.identity` API. I can manually set the token within GAPI to the one retrieved, and then use to perform valid requests.

Unfortunately I cannot call the `init` functions for `gapi.client` or `gapi.auth` - this is due to Chrome Extension html pages having an `"Invalid cookiePolicy"`, see screenshot below. 

<img width="1671" alt="screen shot 2019-02-12 at 11 43 26 am" src="https://user-images.githubusercontent.com/13029040/52663402-6cc32080-2ebb-11e9-8231-943414e74491.png">

I am still able to somewhat use the APIs, though, by manually setting the token using `google.client.setToken({access_token:"<token>"})`.

Theoretically you should be able to get the ID token using `gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse().id_token` - however, `getAuthInstance()` returns undefined because we did not instantiate `gapi.auth2` with `init`. 

There's a bit of discussion online about this, including [this StackOverflow question](https://stackoverflow.com/questions/31159206/get-id-token-with-chrome-identity-api).

I've also tried the following code, which does not use the JavaScript library, but also fails:

```js
// Using chrome.identity
var manifest = chrome.runtime.getManifest();

var clientId = encodeURIComponent(manifest.oauth2.client_id);
var scopes = encodeURIComponent(manifest.oauth2.scopes.join(' '));
var redirectUri = encodeURIComponent('https://' + chrome.runtime.id + '.chromiumapp.org');

var url = 'https://accounts.google.com/o/oauth2/auth' + 
          '?client_id=' + clientId + 
          '&response_type=id_token' + 
          '&access_type=offline' + 
          '&redirect_uri=' + redirectUri + 
          '&scope=' + scopes;

chrome.identity.launchWebAuthFlow(
    {
        'url': url, 
        'interactive':true
    }, 
    function(redirectedTo) {
        if (chrome.runtime.lastError) {
            // Example: Authorization page could not be loaded.
            console.log(chrome.runtime.lastError.message);
        }
        else {
            var response = redirectedTo.split('#', 2)[1];

            // Example: id_token=<YOUR_BELOVED_ID_TOKEN>&authuser=0&hd=<SOME.DOMAIN.PL>&session_state=<SESSION_SATE>&prompt=<PROMPT>
            console.log(response);
        }
    }
);
```
It fails with the following error:

```
Authorization page could not be loaded.
```

My goal is to get an ID token that I can use to verify their identity and pass on to my back end. Is there a way to get it from the access token using the JavaScript API? Since I've already done an interactive sign in flow with the chrome extension it would also be ideal to *not* have another popup. 

1) Is an access token not more permissive than an ID token? Should I not just be able to directly request/create an ID token from this access token? 

2) Is there functionality within the `gapi` context to retrieve an id token? Specifically I'd like to call `gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse().id_token`  *without* going through `gapi.auth2.init`, due to the inability to do so on a chrome extension. 

3) Is there a flaw in my current reasoning or architecture? I might be misunderstanding best practices or usages with oauth2.

3) Ancillary question, but is there a way to circumvent the `Invalid Cookie Policy` and get full access to the `gapi` context from within a Chrome Extension?

**Comment by ddykhoff** [comment]
You're getting the `Authorization page could not be loaded.` error due to 1) New endpoint base is `https://accounts.google.com/o/oauth2/v2/auth` 2) `nonce` is a required URL parameter for the authentication URL, so add something like `&nonce=<your nonce value>`. 

I've been fighting this exact same issue recently, except that I am able to generate id_tokens, but my API still rejects them as it is behind Google Identity Aware Proxy which provides no reason for the rejection, so I'm not sure the tokens are generated correctly.

**Comment by jonluca** [comment]
Thanks! I've updated the code as it is below but am still getting the same error.

```js
// Using chrome.identity
var manifest = chrome.runtime.getManifest();

var clientId = encodeURIComponent(manifest.oauth2.client_id);
var scopes = encodeURIComponent(manifest.oauth2.scopes.join(' '));
var redirectUri = encodeURIComponent(chrome.identity.getRedirectURL('oauth2'));

var url = 'https://accounts.google.com/o/oauth2/v2/auth' + 
          '?client_id=' + clientId + 
          '&response_type=id_token' + 
          '&access_type=offline' + 
          '&nonce=testnonce' + 
          '&redirect_uri=' + redirectUri + 
          '&scope=' + scopes;

chrome.identity.launchWebAuthFlow(
    {
        'url': url, 
        'interactive':true
    }, 
    function(redirectedTo) {
        if (chrome.runtime.lastError) {
            // Example: Authorization page could not be loaded.
            console.log(chrome.runtime.lastError.message);
        }
        else {
            var response = redirectedTo.split('#', 2)[1];

            // Example: id_token=<YOUR_BELOVED_ID_TOKEN>&authuser=0&hd=<SOME.DOMAIN.PL>&session_state=<SESSION_SATE>&prompt=<PROMPT>
            console.log(response);
        }
    }
);
```

The client ID I'm passing along is a "Chrome Extension" one. Would that make a difference (that is, it's Chrome Extension rather than Web Client).

**Comment by ddykhoff** [comment]
Yes, this method requires the OAuth2 client to be 'Web application'. Chrome App is used for the Identity API

**Comment by jonluca** [comment]
Ah that's my issue, thanks!

Unfortunately I need the Chrome App token for the built in `identity` API. I don't think it's a good user flow to have two different authorization popups so I'm going to need to find an alternate method of verification. 

Thanks!

**Comment by BirskiySergey** [comment]
Hi, I did not quite understand. You can get id token?

**Comment by BirskiySergey** [comment]
Hi, I did not quite understand. You can get id token?
I have the same problem, and i can't fix it.

**Comment by chasdevs** [comment]
I am having the same issue. Basically, I need to register a user with my own backend after they have signed-in via the `identity` API in my extension. The recommended procedure for this seems to be outlined [here](https://developers.google.com/identity/sign-in/web/backend-auth), which says to use the JWT returned in `id_token` for secure communication with the backend. I cannot for the life of me get ahold of `id_token`. I am starting to not think it's possible.

**Comment by neaumusic** [comment]
The google docs could definitely use an update regarding auth privileges and procedures.

It seems getting an auth token for `scopes: ["profile identity email"]` cannot provide a JWT id_token, and that we'd need to 'Sign In' via a completely different flow (not a redirect_uri platform flow)

It's all confusing, and there are way too many articles on these pages:

https://developers.google.com/identity/protocols/OAuth2
https://developers.google.com/identity/sign-in/web/sign-in
https://developer.chrome.com/extensions/app_identity
https://developer.chrome.com/apps/app_identity

**Comment by PabiGamito** [comment]
I am having the same problem. I want to be able to authenticate my users with the chrome identify API. Has anyone managed to figure out how to make this work?

**Comment by neaumusic** [comment]
@PabiGamito wouldn't including the key in url be dangerous because other extensions listening for tabs would know the private key? or is it just assumed that you're the first to use it and doesnt matter after that?

**Comment by PabiGamito** [comment]
@neaumusic What are you referring to exactly by 'private key'? The `client_id`? Because if so, I am pretty sure that is fine to be public. 

See https://developers.google.com/identity/sign-in/web/sign-in where the `client_id` is displayed publicly.

**Comment by neaumusic** [comment]
@PabiGamito not the request, but that method works due to a redirect happening where google's signed id_token of the user is in the querystring params `tab.title.split`

**Comment by PabiGamito** [comment]
@neaumusic Yeah, you are right that if a malicious agent were to be able to access the URL string of that tab then they would effectively have access to the user's details. So this might not be the best solution after all...

**Comment by warex03** [comment]
hi @jonluca were you able to find an alternative auth solution? in our case, we want to authenticate with a backend server using the id token so i'm also trying to make this work

**Comment by joshdance** [comment]
Hit this same issue. Trying to log a user in via a Chrome Extension. 

When I do the OAuth flow via googleapis using the standard OAuth popup method, I get back the following

```
access_token
expiry_date
id_token
refresh_token
scope
token_type
```

This works great, and I use the id_token to verify the user. 

However, you can't use the above method in a Chrome Extension because it blocks popups etc. 

The recommended method is to use `chrome.identity.getAuthToken` to get the `access_token`.

This works fine, but I ONLY get the access_token. 

When I found this issue I was excited because it is exactly what I was trying to do. But seems like no one has figured it out? 😕

**Comment by Ananym** [comment]
For the next hapless googler, I did mostly figure this out.

It is impossible to use getAuthToken for openId.  Don't ask me why.  Instead, you need to use the generic launchWebAuthFlow, which the api reference explicitly states is for non-google providers.  I've seen this solution before, but I assumed it was not the ideal way to go about it.  Turns out it's the only way afaict.

Use this in conjunction with a "web application" oauth client rather than the "chrome app" oauth client described in the extension documentation.  The web app client needs to be configured with https://<your extension id>.[chromiumapp.org](http://chromiumapp.org/) as the authorised origin and  https://<your extension id>.[chromiumapp.org/whatever](http://chromiumapp.org/whatever) as the authorised redirect. You use the google oauth2 endpoint and include url params: client_id, response_type ("id_token"), the aforementioned redirect_uri, a scope of "openid", and both 'state' and 'nonce' as random strings.  Once the user logs in (irritatingly this flow means they have to enter their details manually) the response arrives in the form of the redirect url with an id_token param.

**Comment by foodaka** [comment]
is there a sample anywhere to do this with reactjs?

**Comment by Ananym** [comment]
oh. It ate my angle brackets.
http://yourExtensionID.chromiumapp.org in both cases.

> is there a sample anywhere to do this with reactjs?
As far as the extension's concerned it's still a single call to the chrome.identity.launchWebAuthFlow api method, so it doesn't touch anything frontend.

**Comment by martinmain93** [comment]
Here's an example of how to set it up, similar to @Ananym 's answer: https://stackoverflow.com/a/56304540

My modifications:
 - Change response_type to "id_token"
 - Added scopes https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile so I can get email to validate from the JWT data

**Comment by abegehr** [comment]
Weird, that `chrome.identity.getAuthToken` wouldn't also return an id-token..
