### ISSUE TITLE
Function named delete fails to load in IE 8

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#51]
_From [djr...@gmail.com](https://code.google.com/u/114152883716887425467/) on October 01, 2012 07:54:56_

What steps will reproduce the problem? If possible, provide a live demo of the issue. 1. Create a page that has javascript that calls gapi.client.calendar.events.delete , for example:
var req = gapi.client.calendar.events.delete({
                calendarId: gCals[event.calName].id,
                eventId: entry.id
            });
2.  Load the page in IE 8 What is the expected output? What do you see instead? The expected output is for the javascript to load correctly.  In IE 8, there is an error on the "delete" function line saying there is an "expected identifier." What version of the product are you using? On what operating system? Google Calendar javascript api, windows 7, IE 8 Please provide any additional information below. "delete" is a reserved keyword in javascript and shouldn't be used for function names.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=51_

**Comment by TMSCH** [comment]
Calling `gapi.client.calendar.events["delete"]` is indeed a workaround for IE8 that reserves this keyword. Closing the issue.
