### ISSUE TITLE
Contributing to gapi

### ISSUE THREAD

**Issue by jiachen247** [google/google-api-javascript-client#515]
Hi, sorry I was wondering where is the code for this repo? Is this project open source? I would like to extend the functionality for some of the drive apis. Would that be possible?

**Comment by grant** [comment]
Hi @jiachen247,
The issue of where is the code is being tracked here:
https://github.com/google/google-api-javascript-client/issues/432

With Javascript, you can simply extend the object to however you like.

I think answers the questions, and so I'll close this issue. If you'd like it open, ping me with more questions here and I'll re-open it.
