### ISSUE TITLE
Then() function not executing on AngularJS

### ISSUE THREAD

**Issue by ghost** [google/google-api-javascript-client#526]
I was following these instructions to start using google api on an angularjs application:

https://developers.google.com/calendar/quickstart/js

And here's my attempt:

lib/init.js

```
function initClient() {
    console.log('-- initClient');
    var resp = gapi.client.init({
        apiKey: '',
        clientId: '',
        discoveryDocs: [
            "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest"
        ],
        scope: [
            'profile',
            'https://www.googleapis.com/auth/calendar.readonly'
        ]
    }).then(function() {
        console.log('-- then') // never executes
       // api loaded
    }, function(error) {
        console.log('ERROR: ' + error);
    });
}

function handleClientLoad() {
    console.log('-- handleClientLoad');
    gapi.load('client:auth2', {
        callback: function() {
            initClient();
        },
        onerror: function() {
            console.log('gapi failed to load!');
        },
        timeout: 5000, // 5 seconds.
        ontimeout: function() {
            // Handle timeout.
            console.log('gapi.client could not load in a timely manner!');
        }
    });
}
```
index.html

```
<!doctype html>

<html>
  <head>
    <link rel="stylesheet" href="lib/style.css">
  </head>

  <body ng-app="my-app">
    <div ng-controller="MainCtrl">
        <h3>Testing Google JS API Lib</h3>
    </div>


    <script type="text/javascript" src="lib/init.js"></script>
    <script id="gapiscript" src="https://apis.google.com/js/platform.js?onload=handleClientLoad">
    </script>
    <script src="lib/script.js"></script>
  </body>
</html>
```

`gapi.client.load().then() {...}` is not executing and the `console.log('-- then')` debug line never shows. Doing `document.getElementsbyId('gapiscript')` I get:

`<script id="gapiscript" src="https://apis.google.com/…?onload=handleClientLoad" gapi_processed="true">`

`console.log('-- handleClientLoad');` and  `console.log('-- initClient'); ` are being executed and show in the console. I get no error message from the onerror callback.

Another console message I'm getting is `CSI/start cb=gapi.loaded_0:613:127`

How can I get the then() function to execute to start using the api?

**Comment by jmliz** [comment]
Ok I've been doing some tests and if I remove the clientId option from gapi.client.init the then function executes. I don't understand why this happens. In this guide https://developers.google.com/calendar/quickstart/js it clearly says I should set up a client ID and use it as parameter.

**Comment by depsimon** [comment]
I have the same issue, no exception no response the then is simply ignored.
When removing the clientId, I do get a response but it doesn't recognize the auth2
