### ISSUE TITLE
gapi.load requests doesn't work with angular promises 

### ISSUE THREAD

**Issue by sgajula** [google/google-api-javascript-client#541]
I am trying to handle errors gracefully in the client side when one or more libraries fails to load. Currently, it is in the stuck state, and the promise requests are fulfilled but the libraries doesn't load. 

I tried to workaround with timeout to see if the libraries work but this doesn't help me in all situations. 

```js
var loadPromises = [];
    loadPromises.push(gapi.client.load('myApp', 'v1', null, apiRoot));
    loadPromises.push(gapi.client.load(apiRoot + '/discovery/v1/apis/myApp/v1/rest'));
    loadPromises.push(gapi.load('client:auth2'));
 loadPromises.push(gapi.client.load('https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'));

            $q.all(loadPromises).then(function() {
                this.$q.defer().resolve(true);
            }).catch(function(err){
              console.error(err);
              this.$q.defer().reject(err);
            });`
```

No error in the console, the UI doesn't show because of the libraries failed to load correctly. Your help is greatly appreciated, thanks in advance!

**Comment by dvanderb** [comment]
Sorry that we did not answer this question in a timely fashion. I am closing this for now, but if you still need help with this question, please reopen.
