### ISSUE TITLE
Google Sign In Button Language

### ISSUE THREAD

**Issue by russo177x** [google/google-api-javascript-client#543]
How to translate the Sign in with Google inside the button??  I want to use this text in pt_BR

**Comment by grant** [comment]
Hi @russo177x,
You can learn more about how to use the Google Sign-in with your own translated text here:

https://developers.google.com/identity/branding-guidelines#g+signin-social-scopes

Basically, you can create your own button's text. Or you can do something like this:

---
Sign in with:  
![](https://developers.google.com/identity/images/btn_google_signin_light_normal_web_short.png)

**Comment by LAMASE** [comment]
Why, in the italian file, the short version is correct and the long one is in english?
![image](https://user-images.githubusercontent.com/19807439/105346085-61b7b580-5be5-11eb-947b-04f4bcd2e215.png)

This is the source file:
https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.it.PEsbfaTdrM4.O/m=signin2/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCPXGA_pTZEJDJXJNjx80GQ37vEYTA/cb=gapi.loaded_0

**Comment by Bodrie** [comment]
This is still a problem in my opinion, I tried to set the locale property of the button to every possible thing but it just gets the browser default...

**Comment by kamsamita** [comment]
Has this issue been resolved yet?

**Comment by Bodrie** [comment]
Not sure, i was not able to find solution then...
