### ISSUE TITLE
Some documentation links are invaild

### ISSUE THREAD

**Issue by evan-coygo** [google/google-api-javascript-client#547]
Sometime recently it seems this URL has started redirecting to this repo https://developers.google.com/api-client-library/javascript

Some links in the docs are still pointing to their old locations on developers.google.com, which just redirects to the README home page for this repo.

For example, the [auth docs](https://github.com/google/google-api-javascript-client/blob/master/docs/auth.md) in this repo has this link, which redirects back to this repo's README
```
For detailed instructions for this process, see the [Getting started](https://developers.google.com/api-client-library/javascript/start/start-js) page.
```

**Comment by grant** [comment]
Hey @evan-coygo, thanks for the report.

I fixed the links for the auth docs. If you see more broken links, please report them or send a pull request!

**Comment by francisbrito** [comment]
Hello @grant,

I found some broken links in batch requests documentation. I opened a PR (#583) for fixing them. Please let me know if you'd like me to make any adjustments to it.

Thanks,

P.S: I think there might be some broken links in `reference.md` and `promises.md` files too. If you'd like so, I could expand the PR to also include fixes for those.

**Comment by grant** [comment]
> Hello @grant,
> 
> I found some broken links in batch requests documentation. I opened a PR (#583) for fixing them. Please let me know if you'd like me to make any adjustments to it.
> 
> Thanks,
> 
> P.S: I think there might be some broken links in `reference.md` and `promises.md` files too. If you'd like so, I could expand the PR to also include fixes for those.

PRs for these docs are extremely welcome 🤗! Thanks for the ping.

**Comment by swanprincess386** [comment]
> Sometime recently it seems this URL has started redirecting to this repo https://developers.google.com/api-client-library/javascript
> 
> Some links in the docs are still pointing to their old locations on developers.google.com, which just redirects to the README home page for this repo.
> 
> For example, the [auth docs](https://github.com/google/google-api-javascript-client/blob/master/docs/auth.md) in this repo has this link, which redirects back to this repo's README
> 
> ```
> For detailed instructions for this process, see the [Getting started](https://developers.google.com/api-client-library/javascript/start/start-js) page.
> ```
