### ISSUE TITLE
Property 'auth2' does not exist on type 'typeof gapi'.

### ISSUE THREAD

**Issue by lucasriondel** [google/google-api-javascript-client#573]
![image](https://user-images.githubusercontent.com/7773454/69407815-bf145600-0d05-11ea-9c04-007da3b6813b.png)

**Comment by lucasriondel** [comment]
For those who might have the same problem as me, make sure you add `@types/gapi.auth2` to your devDependencies. This should be in the doc though.

**Comment by ardation** [comment]
I also had to add in this to my tsconfig.json

```JSON
{
  "compilerOptions": {
    "types": ["gapi", "gapi.auth2"]
  }
}
```

**Comment by Sergio1C** [comment]
Seems like, until now it not being on docs?

**Comment by jacob-shieh** [comment]
As of now it still isn't on the docs. Adding this on the Readme would help lots with people working in Typescript
