### ISSUE TITLE
Property 'gmail' does not exist on type 'typeof client'.

### ISSUE THREAD

**Issue by lucasriondel** [google/google-api-javascript-client#574]
![image](https://user-images.githubusercontent.com/7773454/69475994-4cbe7700-0dd4-11ea-8850-85acb6934adf.png)

I can use `gapi.auth2` and `gapi.client` but not `gapi.client.gmail`.

I have followed instructions in [this](https://stackoverflow.com/questions/48372348/drive-does-not-exist-on-type-typeof-client) and [this](https://stackoverflow.com/questions/52521349/property-calendar-does-not-exist-on-type-typeof-client) issue, but it did not correct my issue.

My package.json: 
`"devDependencies": {
    "@types/gapi": "^0.0.39",
    "@types/gapi.auth2": "^0.0.50",
    "@types/gapi.client.gmail": "^1.0.1",
    ...
}`

My tsconfig.json:
`{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "types": ["gapi", "gapi.auth2", "gapi.client", "gapi.client.gmail"]
  },
  "include": ["src"]
}`

My node_modules: 
![image](https://user-images.githubusercontent.com/7773454/69476072-5ac0c780-0dd5-11ea-9b7b-39c72d0aab86.png)

And i'm using Typescript 3.6.2.

**Comment by grant** [comment]
It looks like you are using the TypeScript, which has limited support. It only handles some auth autocompletion.

I'm not familiar with `types/gapi.client.gmail`, but that source code would be in a different GitHub repo. It isn't officially supported.

See:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gapi.client.gmail/index.d.ts#L3

Here's a sample that may help:
https://github.com/gsuitedevs/browser-samples/blob/master/gmail/quickstart/index.html

You'll probably have to use something like `// @ts-ignore`.

**Comment by cashewnuts** [comment]
Hello @lucasriondel 
You may needs to add this lines to your tsconfig.json.
```
{
  ...
  "compilerOptions": {
    ...
    // Add this lines
    "typeRoots": ["node_modules/@types"],
    "types": ["gapi", "gapi.auth2", "gapi.client.gmail"],
    ...
  }
}
```
I hope this will work.

**Comment by ccdunder** [comment]
Thanks for reaching out. This bug tracker is intended to report bugs in the Google API JavaScript Client.

https://github.com/google/google-api-javascript-client/issues/574#issuecomment-564632936 is correct: For support with typescript type information, please see https://github.com/DefinitelyTyped/DefinitelyTyped.

Closing for now as this doesn't seem like an issue with GAPI js client.
