### ISSUE TITLE
When will be Google Ads API JavaScript available

### ISSUE THREAD

**Issue by konradstrek** [google/google-api-javascript-client#578]
I was looking through all files but I couldn't find JavaScript example for new Google Ads API. If it exists, let me know.

**Comment by grant** [comment]
Hi @konradstrek, there is no example for using the Google Ads API for client-side Javascript. It should be possible though by using this discovery doc:

`https://www.googleapis.com/discovery/v1/apis/googleads/v1/rest`

If you wanted to create a Node client for the API, you'd do something like this:

```
clone git@github.com:googleapis/google-api-nodejs-client.git
npm i
npm run pregenerate 
npm run generate --discovery-url https://www.googleapis.com/discovery/v1/apis/googleads/v1/rest
```

Hope this helps!
