### ISSUE TITLE
signOut() or disconnect()

### ISSUE THREAD

**Issue by FernanddoSalas** [google/google-api-javascript-client#581]
What's the difference between:
* `GoogleAuth.signOut()`
* `GoogleAuth.disconnect()`
* `GoogleUser.disconnect()`

**Comment by zacharynanfelt** [comment]
https://developers.google.com/identity/sign-in/web/reference#googleauthsignout

https://developers.google.com/identity/sign-in/web/reference#googleauthdisconnect
https://developers.google.com/identity/sign-in/web/disconnect
