### ISSUE TITLE
Google sign-in fails starting Feb 4th, 2020

### ISSUE THREAD

**Issue by apeace** [google/google-api-javascript-client#592]
# Summary

`gapi.auth2.init().then()` never calls its callbacks, starting with Chrome 80 Stable on Feb 4th, 2020 (just over three weeks from creation of this ticket).

The result is that the Google sign-in features of this library do not work.

The reason is that Google services do not set `SameSite=None` on their cookies, resulting in the cookies being blocked.

# Steps to reproduce this issue

```html
<!doctype html>
<html>
<body>

<div id="google-signin-button"></div>

<!-- See: https://developers.google.com/identity/sign-in/web/reference -->
<script src="https://apis.google.com/js/platform.js?onload=init" async defer></script>

<script>
function init() {
    console.log("Loading auth2")
    gapi.load("auth2", function () {
        console.log("auth2.init")
        gapi.auth2.init({client_id: "<YOUR CLIENT ID>"}).then(
            function () {
                gapi.signin2.render("google-signin-button", {
                    onsuccess: function(user) {
                        window.alert("Success")
                    },
                    onfailure: function() {
                        window.alert("Failure")
                    }
                })
            },
            function (err) {
                console.error(err)
                window.alert("Failed to init.")
            }
        )
    })
}
</script>

</body>
</html>

```

Running this on Chrome 79 stable produces "Success".

But if you enable the following two features in chrome://flags, it will fail. **These flags are being enabled on Feb 4th, 2020 when Chrome 80 Stable goes live.**

<img width="764" alt="Screen Shot 2020-01-13 at 1 08 31 PM" src="https://user-images.githubusercontent.com/78548/72280258-f1f01180-3605-11ea-80ac-41d4514c741c.png">

# Expected Behavior

This code should produce a "Success" alert, on Chrome with the above two flags enabled.

# Actual Behavior

The code produces no alerts. In the console, we see warning messages:

```
A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

The message is repeated for `https://google.com` and `https://accounts.google.com`.

# Root Cause

Google services need to set `SameSite=None` and `Secure` on the cookies being set for sign-in services.

More information: https://web.dev/samesite-cookies-explained/

# This library

There is no problem with this library itself, rather there is a problem with the services it is interacting with.

Are this library's maintainers able to contact the Google employees responsible for the backend services and ask them to update their cookies?

Is there a better place where this bug could be logged more directly to the backend team?

Thanks so much!

**Comment by chlily1** [comment]
This is the same issue as https://github.com/google/google-api-javascript-client/issues/561.

Google services will be updated by the time SameSite-by-default rolls out to Chrome Stable.

**Comment by apeace** [comment]
I can confirm that the above code now produces "Success". Closing this issue.

Funny enough, I'm still getting warnings that cookies have been blocked due to the SameSite policy. But if it works I'm not complaining!
