### ISSUE TITLE
Think the documentation is wrong

### ISSUE THREAD

**Issue by t5unamie** [google/google-api-javascript-client#596]
Can you update the documentation concerning calendar listed types?

https://googleapis.dev/nodejs/googleapis/latest/calendar/interfaces/Params$Resource$Calendarlist$Watch.html#syncToken

The following suggests I can parse a sync token. However, my understanding is that sync tokens are used to diff from the last request I made. In the case of the CalendarList Watch or event the Event watch. I am simply posting to you a requirement of being notified about push notifications for specific assets.

I ask this question in case I miss understood how this interface works.

**Comment by ccdunder** [comment]
Thanks for reaching out. This bug tracker is intended to report bugs in the Google API JavaScript Client.
For support with the nodejs client, please see https://github.com/googleapis/google-api-nodejs-client#questionsproblems.
