### ISSUE TITLE
How to use offline token?

### ISSUE THREAD

**Issue by ysz** [google/google-api-javascript-client#603]
I prompt user to grant offline token and I save it to database.

Later, I want to use that offline token in the browser when original user will not be logged in and in fact another user will use the browser 

I am trying to write equivalent of server side

```
      const auth = new google.auth.OAuth2(process.env.CLIENT_ID, globalAny.s.CLIENT_SECRET)
      auth.setCredentials(account) // account from database
      const drive = google.drive({version: 'v3', auth})
      const result = await drive.files.get(...)
      // success 
```

In the browser I initialize library like this

```
      gapi.load('client', () => {
        gapi.client
          .init({})
          .then(() => {
            gapi.load('client:auth2', () => {
              gapi.client.load('drive', 'v3', () => {
                console.log('Ready. Make a call to API ')
              })
            })
          })
      })
```

Then in the browser in my app I get access_token from server from database and try to set it like this: (mind you, at this point no user is logged in to google)

```
    gapi.auth2.authorize(
      {
        client_id: `${CLIENT_ID}.apps.googleusercontent.com`,
        scope: SCOPE,
        prompt: 'none',
      },
      async (response: any) => {
        gapi.client.setToken({access_token: tokens.access_token})
        try {
          const result = await gapi.client.drive.files.get(...)
```

Even though `tokens.access_token` is same as used on server side I get error in the browser:

```
resposne.error: "user_logged_out"
```

and drive.files.get fails with 

```
Invalid Credentials
```

and status 401 

How can I use offline token in the browser?

**Comment by aalimovs** [comment]
@ysz did you solve this?

**Comment by MagomedLorsanov** [comment]
@aalimovs @ysz  guys didnt you solve this problem? pls answer

**Comment by aalimovs** [comment]
@MagomedLorsanov I solved this by realising you cannot use offline tokens in a browser unless the user is already logged in. 

I've spent ages trying to solve this and went through all the questions on StackOverflow.

From what I remember, setting the token in the browser was only meant to pre-select a correct account from many logged-in.
