### ISSUE TITLE
Uncaught TypeError: a is not a function

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [google/google-api-javascript-client#605]
After successful logging in, I see the error in the browser's console:

    cb=gapi.loaded_0:formatted:5483 Uncaught TypeError: a is not a function

    var Ow = function(a, b) {
        return function() {
            a(b)
        }
    };

Browser: Chrome
OS: OsX

**Comment by iAmeng** [comment]
me too.  like this problem.
`Uncaught TypeError: a is not a function
    at cb=gapi.loaded_0:279
    at run (VM99887 setImmediate.js:40)
    at runIfPresent (VM99887 setImmediate.js:69)
    at onGlobalMessage (VM99887 setImmediate.js:109)`

When I try    [QuickStart](https://developers.google.com/sheets/api/quickstart/js) , it worked success in single index.html.
But when move the functions to  Vue ,  the listener does not invoked
`
methods:{
...
initGapiClient() {
                let vm = this;
                gapi.client.init({
                    apiKey: googleAppData.API_KEY,
                    clientId: googleAppData.CLIENT_ID,
                    discoveryDocs: googleAppData.DISCOVERY_DOCS,
                    scope: googleAppData.SCOPES
                }).then(function () {
                    gapi.auth2.getAuthInstance().isSignedIn.listen(vm.updateSigninStatus());
                    vm.updateSigninStatus(gapi.auth2.getAuthInstance().isSignedIn.get());
                    vm.Logger.info('google apis init success!')
                }, function (error) {
                    vm.appendPre(JSON.stringify(error, null, 2));
                });
            }
...
`
Browser:Chrome
OS:OsX

**Comment by iAmeng** [comment]
When used a function() like this,  it worked, but How compose them to Vue?

`gapi.auth2.getAuthInstance().isSignedIn.listen(state => console.log(state));`

**Comment by iAmeng** [comment]
I used like this it worked 


    gapi.auth2.getAuthInstance().isSignedIn.listen(
                        function (state) {
                            vm.updateSigninStatus(state)
                        })

**Comment by KonstantinKolodnitsky** [comment]
> When used a function() like this, it worked, but How compose them to Vue component method?
> 
> ```
> gapi.auth2.getAuthInstance().isSignedIn.listen(state => console.log(state));
> ```

`state => console.log(state)` equals to 

    function (state) {
        return console.log(state);
    }

It's ES6 or ECMAScript 6 - ECMAScript 2015. You need to use `babel` to compile it into plain javascript.

**Comment by KonstantinKolodnitsky** [comment]
OK, it was my fault.
I didn't put a function inside `gapi.auth2.getAuthInstance().isSignedIn.listen();` for testing and forgot about it.
Closing.

**Comment by jcmelchorp** [comment]
I had the same problem on Angular, and fix it with an arrow function, like this:
``gapi.auth2.getAuthInstance().isSignedIn.listen( () => this.updateSigninStatus( gapi.auth2.getAuthInstance().currentUser.get() );``
