### ISSUE TITLE
gapi.client.calendar is undefined

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#61]
_From [simone.l...@gmail.com](https://code.google.com/u/112225173807100094382/) on November 07, 2012 23:56:07_

What steps will reproduce the problem? If possible, provide a live demo of the issue. When I execute the page attached at the issue, all OAuth 2 works fine, but when I load the calendar v3 apis nothing is loaded; in fact when I call gapi.client.calendar.events I have the error attached in the image (''gapi.client.calendar.events' is null or not an object').
I can't understand why... What version of the product are you using? On what operating system? V3 on windows server 2003

Please HELP!!!

**Attachment:** [Error.png Default.aspx](http://code.google.com/p/google-api-javascript-client/issues/detail?id=61)

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=61_

**Comment by sempr254** [comment]
[Pat Parmus.txt](https://github.com/google/google-api-javascript-client/files/1151466/Pat.Parmus.txt)
