### ISSUE TITLE
Not a valid origin for the client: <snip> has not been whitelisted for client ID 

### ISSUE THREAD

**Issue by witcradg** [google/google-api-javascript-client#624]
I'm trying to get this source working:
https://github.com/google/google-api-javascript-client/blob/master/samples/authSample.html

error message: Not a valid origin for the client: http://localhost:5500 has not been whitelisted for client ID

in my devtools console
window.location.origin : "http://localhost:5500"

I have set the whitelist through the API Key and entered it as suggested by @orichcasperkevin (issue #301) and I have cleared the cache, but I'm seeing this same issue.

One thing that confuses me is the message refers directly to the client ID, but whitelist input is done through the API Key. The Oauth consent form deals with Authorized Domains and not Whitelists. It will not allow localhost entries; it requires a top private domain.

Looking for suggestsions.

**Comment by witcradg** [comment]
I was able to get past this issue. I'm not certain how and I've been tinkering with several items, but it may have been a result of completing a field I had left empty in the "edit app" link on the oauth content screen. I have a new issue (403 error) but I think that is not a result of this problem. Closing.

**Comment by rupeshshubh2575** [comment]
.

**Comment by Muzyu** [comment]
I added that I encountered this problem problem caused by the top-level domain.
