### ISSUE TITLE
Use Service Account

### ISSUE THREAD

**Issue by PeterHindes** [google/google-api-javascript-client#632]
I am trying to use a service account from [google cloud](https://console.cloud.google.com/iam-admin/serviceaccounts) to submit new data to a Spreadsheet on Google Drive. I am having trouble understanding how to use the JavaScript client to sign in to the service account and access the spreadsheet that is shared with it.

**Comment by grant** [comment]
Hi, I believe this discussion may help:
https://github.com/google/google-api-javascript-client/issues/428

https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md#----gapiclientsettokentokenobject--
