### ISSUE TITLE
API Discovery Documents link not working

### ISSUE THREAD

**Issue by induratized** [google/google-api-javascript-client#637]
Hello,
The link to `API Discovery Documents` at [page](https://github.com/google/google-api-javascript-client/blob/master/docs/start.md) is https://developers.google.com/api-client-library/javascript/features/discovery , but it is redirecting me back to https://github.com/google/google-api-javascript-client

Similarly with `OAuth 2 authentication` at [page](https://github.com/google/google-api-javascript-client) (under Features section) is https://developers.google.com/api-client-library/javascript/features/authentication, but it redirects back to https://github.com/google/google-api-javascript-client

If this is intended than the target documents redirections are missing

**Comment by grant** [comment]
Those GitHub Markdown pages should use these links instead:
https://github.com/google/google-api-javascript-client/blob/master/docs/discovery.md
https://github.com/google/google-api-javascript-client/blob/master/docs/auth.md

Want to create a PR?

**Comment by induratized** [comment]
@grant  pull requests created for the same

**Comment by grant** [comment]
OK thanks, please link your PRs in the issue next time:
- https://github.com/google/google-api-javascript-client/pull/638
- https://github.com/google/google-api-javascript-client/pull/639

**Comment by induratized** [comment]
@grant Updated with relative links

Apologies for I made two separate PR's again (which i closed now). 
Made commits directly to the respective `patch` branches of the earlier PR's for correct flow

**Comment by grant** [comment]
No worries.
