### ISSUE TITLE
gapi.client.request() and REST args

### ISSUE THREAD

**Issue by Rustastra** [google/google-api-javascript-client#648]
Hello,

I was wondering where I could look up the correspondence between the terms used in Rest and the .request() args.

I am specifically interested in Cloud Storage & Downloading data: how to specify the save-to-location?

Thank you

**Comment by dvanderb** [comment]
There is no save to location since the GAPI client provides the response body to the caller(as opposed to curl which writes out to a file). I am closing this for now, but if you still need help with this question, please reopen.
