### ISSUE TITLE
404 error during gapi.client.init

### ISSUE THREAD

**Issue by lucasriondel** [google/google-api-javascript-client#652]
I'm trying to run the `gapi.client.init` method after calling `gapi.load("client:auth2", () => { ... })`. I'm sure my credentials are correct, my `clientId`, `discoveryDocs` and `scope` are ok. 

My html loads `<script src="https://apis.google.com/js/api.js"></script>`, and based on these issues ( https://github.com/google/google-api-javascript-client/issues/204 ) ( https://github.com/google/google-api-javascript-client/issues/206 ), it seems to be an issue related to caching the api.js file. I've tried private browsing, clearing cache, everything. Right after calling `gapi.client.init`, I have an 404 error while trying to call this URL: `https://www.google.com/static/proxy.html?usegapi=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.fr.r-hDPYXelT8.O%2Fam%3DwQc%2Fd%3D1%2Fct%3Dzgms%2Frs%3DAGLTcCMe7OgINlWwG9LD5-8LCk0q7Zu3ag%2Fm%3D__features__#parent=http%3A%2F%2Flocalhost%3A3000&rpctoken=1942944226`

I cannot think of any solution to fix it now. Do you guys have an idea ?

**Comment by nithesh247** [comment]
+1

**Comment by zcaceres** [comment]
+1

**Comment by dvanderb** [comment]
Sorry that we did not answer this question in a timely fashion. I am closing this for now, but if you still need help with this question, please reopen.
