### ISSUE TITLE
platform.js or api.js?

### ISSUE THREAD

**Issue by YoraiLevi** [google/google-api-javascript-client#658]
Trying to understand how I should go about referencing the google apis for a static page web app. I am confused.
1) I am unsure where the complete documentation is as I have stumbled upon a few broken links in this repository already
2) These tutorial reference 2 different urls yet seem to be related to this repository

https://developers.google.com/identity/sign-in/web/reference#gapiauth2initparams
```html
<script src="https://apis.google.com/js/platform.js?onload=init" async defer></script>
```

https://developers.google.com/sheets/api/quickstart/js
```html
<script async defer src="https://apis.google.com/js/api.js"
      onload="this.onload=function(){};handleClientLoad()"
      onreadystatechange="if (this.readyState === 'complete') this.onload()">
```
What are the differences? what url should one use? does it matter?
Should one rather use the node client rather than web and compile it?

**Comment by vicb** [comment]
That's a very good question.

Could someone at google answer ? The doc vs code samples are confusing.

**Comment by jrobinso** [comment]
There doesn't seem to be any reference documentation for the gapi library,  particularly gapi.client,  just some examples.   Is this true?  With no source code to browse  I'm left guessing a lot.   The lack of documentation is surprising, as is the lack of source code.

**Comment by jrobinso** [comment]
This has been open since July 22,  it should be fairly simple question to answer.  Are both platform.js and api.js supported?  I too had followed an example using platform.js then came across this repo later.

**Comment by sergentj** [comment]
The functionality in platform.js is a superset of the functionality in api.js.

The documentation for those APIs is correct. If you are using both the sheets APIs and the sign-in API, platform.js will suffice, you needn't load both.

You are correct that this is poorly documented, and we're aware that's a problem.

Closing this since it is not going to be useful to track work on improving documentation (which is a much larger issue) here.

**Comment by quanhx11** [comment]
<script src='https://google.com'>aa</script>
