### ISSUE TITLE
Error 400 on gapi.client.init for reseller api

### ISSUE THREAD

**Issue by lacodajeff** [google/google-api-javascript-client#665]
It appears the discovery service for https://www.googleapis.com/discovery/v1/apis/reseller/v1/rest is not working.
see https://github.com/google/google-api-javascript-client/issues/517

init makes the following call,
https://content.googleapis.com/discovery/v1/apis/reseller/v1/rest?pp=0&fields=kind%2Cname%2Cversion%2CrootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods%2CbatchPath%2Cid&key=<API_KEY>

and returns the following error,
```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "kind,name,version,rootUrl,servicePath,resources,parameters,methods,batchPath,id",
            "description": "Error expanding 'fields' parameter. Cannot find matching fields for path 'kind'."
          }
        ]
      }
    ]
  }
}
```

**Comment by lacodajeff** [comment]
note: following steps here, https://developers.google.com/admin-sdk/reseller/v1/quickstart/js produces the error.

**Comment by maroc-cloud** [comment]
I have the same issue with the reseller API.
My code worked for months and stopped a couple of weeks ago with the same error 400

**Comment by dvanderb** [comment]
This is being investigated.

**Comment by dvanderb** [comment]
This was fixed.
