### ISSUE TITLE
https://content-translation.googleapis.com/static/proxy.html returns 404 when doing gapi.client.language.translations.list

### ISSUE THREAD

**Issue by OhMG2020** [google/google-api-javascript-client#668]
Here is the issue we have when we are using google translate API, we have a key we bought, but when we accomplish the translation feature using  the same code as the sample in this repo shows, we got `https://content-translation.googleapis.com/static/proxy.html` returns 404. This request is sent when we call `gapi.client.language.translations.list`
The error shows in browser's console is:
![image](https://user-images.githubusercontent.com/70362285/91526442-3383c180-e936-11ea-809e-2603400a0d94.png)

We tried REST API using our key, it worked well. So the problem we had here might not be the key?
So why we had the issue using this google-api-javascript-client? We got stuck here .
Any help please? Thanks in advance!

 ```
<html>
  <head>
    <script src="https://apis.google.com/js/api.js"></script>
    <script>
      function start() {
        // Initializes the client with the API key and the Translate API.
        gapi.client.init({
          'apiKey': 'my key',
          'discoveryDocs': ['https://www.googleapis.com/discovery/v1/apis/translate/v2/rest'],
        }).then(function() {
          // Executes an API request, and returns a Promise.
          // The method name `language.translations.list` comes from the API discovery.
          return gapi.client.language.translations.list({
            q: 'hello world',
            source: 'en',
            target: 'de',
          });
        }).then(function(response) {
          console.log(response.result.data.translations[0].translatedText);
        }, function(reason) {
          console.log('Error: ' + reason.result.error.message);
        });
      };

      // Loads the JavaScript client library and invokes `start` afterwards.
      gapi.load('client', start);
    </script>
  </head>
  <body>
    <div id="results"></div>
  </body>
</html>
```

**Comment by dvanderb** [comment]
Thank you for the issue report.  We looked into it and it should be resolved in about 2 weeks.  Your code sample is correct and should start working at that point.

**Comment by OhMG2020** [comment]
@dvanderb  Thanks a lot! Really appreciate it. I will check it later then. ;)

**Comment by OhMG2020** [comment]
Hi @dvanderb  I just checked it on our website, it works well now! Thanks for this quick fix! Just want to confirm if this is a formal fix or just a test version? So I can inform our stakeholders formally. Thanks again! ;)

**Comment by dvanderb** [comment]
@OhMG2020 The fix will be fully rolled out by Friday.  Until then you might see inconsistent results.

**Comment by zcaceres** [comment]
Hello, just wondering if this was released? I didn't see a corresponding commit on master.

**Comment by dvanderb** [comment]
This has been released.  It was a fix on the service side and not in the javascript client.

**Comment by AlexanderKozhevin** [comment]
@dvanderb 
I just got an error I never had before. - 404

https://content-youtube.googleapis.com/static/proxy.html?usegapi=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.76xGL2Yny_o.O%2Fam%3DwQE%2Fd%3D1%2Fct%3Dzgms%2Frs%3DAGLTcCPLubAJPE__-DfP0tDIR1-cduAt3Q%2Fm%3D__features__#parent=https%3A%2F%2Fapp.youstreamer.com&rpctoken=306587562

**Comment by dvanderb** [comment]
@AlexanderKozhevin that is a separate issue and a fix is in pogress.

**Comment by nshimiye** [comment]
@dvanderb I got same 404 when calling `gapi.client.games.scores.submit`
```html
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/static/proxy.html</code> was not found on this server.  <ins>That’s all we know.</ins>

```

**Comment by datle2001** [comment]
![image](https://user-images.githubusercontent.com/73367400/154009840-5acabf55-eeff-458c-9ec1-30b2d6fca67f.png)
![image](https://user-images.githubusercontent.com/73367400/154009914-10e988a1-0a05-494c-863a-76a64e481c0d.png)
@dvanderb I got this issue where googleapis is not defined (as in 2nd image), so I tracked it down to proxy.html (1st image). Is this an error on Google side?

**Comment by dvanderb** [comment]
@datle2001 This is certainly a separate issue. Do you have more context you can provide about what the library is doing up to this point(eg: Does it load translate api via gapi.client.init.. or gapi.client.load? What is invoked before this error occurs?)
