### ISSUE TITLE
Where is the source code please?

### ISSUE THREAD

**Issue by tylerlong** [google/google-api-javascript-client#669]
This one is kind of too short: https://github.com/google/google-api-javascript-client/blob/master/javascripts/main.js

**Comment by Maxim-Mazurok** [comment]
> With the way the client is written, it's impossible to make the client public without a full rewrite. 

https://github.com/google/google-api-javascript-client/issues/432#issuecomment-435523106

**Comment by Maxim-Mazurok** [comment]
That said, you and @jbasinger are welcome to join me in the research of GAPI source code, you can find my code and findings here: https://github.com/Maxim-Mazurok/gapi

**Comment by tylerlong** [comment]
@Maxim-Mazurok Thanks. I turned to use https://github.com/googleapis/google-api-nodejs-client instead

**Comment by Maxim-Mazurok** [comment]
Cool, so you needed library for the backend, not for the front-end.

**Comment by tylerlong** [comment]
> Cool, so you needed library for the backend, not for the front-end.

I need it for frontend. And I created a proxy on server side.

And it is not just frontend vs backend. google-api-nodejs-client is way more powerful than this project. For example, I don't think this project supports [service account](https://developers.google.com/identity/protocols/oauth2/service-account).

**Comment by Maxim-Mazurok** [comment]
Interesting... Which API are you using?

As far as I know, NodeJS version of the lib is generated using the same Google API Discovery schema. So, there should not be any difference...

**Comment by tylerlong** [comment]
> Interesting... Which API are you using?
> 
> As far as I know, NodeJS version of the lib is generated using the same Google API Discovery schema. So, there should not be any difference...

I am using the [service account with domain-wide authority](https://developers.google.com/identity/protocols/oauth2/service-account).

**Comment by Maxim-Mazurok** [comment]
Ohh.. so, it's not like other APIs (such as Sheets or Drive), looks like you're interested in gapi.auth2, which is not covered by [Google API Discovery](https://www.googleapis.com/discovery/v1/apis). 
The closest to what you want will be here, eventually: https://github.com/Maxim-Mazurok/gapi/blob/master/client/unminified.js
But I barely started my research on this file.

**Comment by tylerlong** [comment]
> Ohh.. so, it's not like other APIs (such as Sheets or Drive), looks like you're interested in gapi.auth2, which is not covered by [Google API Discovery](https://www.googleapis.com/discovery/v1/apis).
> The closest to what you want will be here, eventually: https://github.com/Maxim-Mazurok/gapi/blob/master/client/unminified.js
> But I barely started my research on this file.

I am not an expert either. I just struggled to get what I want done.

I do need to invoke APIs like Sheets, Drive, Calendar...etc. But I need to invoke the API as the admin on behalf of other users. Let's say there are 1000 users in the company, I only need to authorize as the admin to update everybody's calendar.

**Comment by Maxim-Mazurok** [comment]
In this case, you definitely have to use NodeJS GAPI, not a client-side JS.

It says
> server-to-server interactions

on the page you shared.

As far as I understand, this is a very sensitive action, so Google doesn't allow this on the client. Also, all of their examples involve back-end languages, such as Java.

I may be wrong on this one, but I think that you can't use a service account on the front-end.

**Comment by tylerlong** [comment]
@Maxim-Mazurok  what you said are all correct.

My app's GUI is on frontend so I need to initiate the call from frontend. I created a proxy on server: https://github.com/tylerlong/express-proxy/blob/master/src/index.ts#L69-L79 so that I can invoke it from frontend.  May not be the best practice but it works for me.

**Comment by Maxim-Mazurok** [comment]
Got it... As long as you keep your website private - it should be fine :) Thanks for sharing!

**Comment by dvanderb** [comment]
The source code for GAPI is currently not published and is periodically updated by Google.  It is not suggested or supported to use downloaded versions of the code. I am closing this for now, but if you still need help with this question, please reopen.
