### ISSUE TITLE
404 response when calling gapi.client.youtube.search.list

### ISSUE THREAD

**Issue by pmmf85** [google/google-api-javascript-client#671]
I get 404 error on https://content-youtube.googleapis.com/static/proxy.html endpoint when trying to use search functionality **gapi.client.youtube.search.list** (https://developers.google.com/youtube/v3/docs/search/list). Few days ago it worked well.

![image](https://user-images.githubusercontent.com/2778920/93578077-24c08580-f99d-11ea-909f-f57f61ee5e26.png)

My test code looks like this:

```<html>
<head>
    <script src="https://apis.google.com/js/api.js"></script>
    <script>
        gapi.load('client', function () {
            gapi.client.setApiKey('my_key');
            gapi.client.load('https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest').then(function () {
                let result = gapi.client.youtube.search.list({
                    part: "snippet",
                    type: "video",
                    q: "test"
                }).execute();
            });
        });
    </script>
</head>
<body>
</body>
</html>
```

I made test with different API keys, from different locations (Europe / States), with changed code a bit ("then" instead of "execute"). Same results.
I am not sure if it is related but when I try to use "Try this API" from Reference I do get infinitive red spinner after pressing "Execute" button.

Any advice? Thank you for help!

**Comment by docwhite** [comment]
I filed the very same issue on https://issuetracker.google.com/issues/168810776

It's reproducible even on the Google APIs Explorer: https://developers.google.com/youtube/v3/docs/videos/list?apix=true

I cannot run the demos, I get the same 404. And even people who are not developers and that have no relation to the project can reproduce.

**Comment by dvanderb** [comment]
This should be fixed for Youtube now if you reload pages that are using the API.

@manishbit97 which specific API are you referring to?  Can you provide the discovery path.  Thanks.

**Comment by pmmf85** [comment]
Hello. I want to report that it was working fine for a while, but today problem returned and I get 404 again.

I also see new comment in thread posted by @docwhite where someone mentions that it is not working for him too.

Thanks in advance.

**Comment by manishbit97** [comment]
https://issuetracker.google.com/issues/170922340

A new issue has already been raised at issue tracker. How can we escalate this ?

**Comment by docwhite** [comment]
I can confirm it is happening again.

**Comment by manishbit97** [comment]
@dvanderb we are using this service in our production systems and we are facing lot of issues during its downtime. And it is taking almost 7-8 hours to fix each time it occurs. Is there any alternate workaround for this ?
