### ISSUE TITLE
Tasks API Batch requests returning 404

### ISSUE THREAD

**Issue by bbreslauer** [google/google-api-javascript-client#675]
Batch requests on the Tasks API seem to always return 404 errors:

```
404. That’s an error.

The requested URL /batch?key=<the key> was not found on this server. That’s all we know.
```

Example code that does this:

```
var batch = gapi.client.newBatch()
batch.add(gapi.client.tasks.tasklists.list({}))
batch.then((response) => {
	console.log(response);
})
```

I filed https://issuetracker.google.com/issues/168580260 against the Tasks service, but they closed it saying that the JS API client library is sending the request to the wrong endpoint, and they suggested opening an issue here.

**Comment by dvanderb** [comment]
We are following up on this issue and will update when I have more information.

**Comment by MathiasGilson** [comment]
I got the same issue, seems to be related to the new discovery doc on Google Tasks at least
Rolling back to the previous revision fixed the issue for me

For some reason the endpoint `https://content-tasks.googleapis.com/batch` instead of `https://content.googleapis.com/batch/tasks/v1`

**Comment by dvanderb** [comment]
This should have been corrected with no user action necessary.
