### ISSUE TITLE
dcm-trafficking api - js support

### ISSUE THREAD

**Issue by chahapra** [google/google-api-javascript-client#678]
Are there any sample javascript functions, to initiate and call dcm trafficking api libraries?

**Comment by ccdunder** [comment]
Calling those APIs using this library will involve making API requests (described [here](https://github.com/google/google-api-javascript-client/blob/master/docs/start.md)) using the discovery documents or REST endpoints listed provided by the service (listed [here](https://developers.google.com/doubleclick-advertisers/rest/)).

For further support with Campaign Manager, please see https://developers.google.com/doubleclick-advertisers; if you still need help, ask a question in the [forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-advertisers-api) listed on their Support page. You may also be able to find answers on stackoverflow. If you believe there's a bug with this library, feel free to open an issue.

**Comment by chahapra** [comment]
Thanks Chris. Totally forgot about this post. I posted this when I started exploring this. I can confirm I have used the CM API successfully in creating campaigns through an internal system.
