### ISSUE TITLE
proxy.html 404

### ISSUE THREAD

**Issue by AlexanderKozhevin** [google/google-api-javascript-client#682]
https://content-youtube.googleapis.com/static/proxy.html?usegapi=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.76xGL2Yny_o.O%2Fam%3DwQE%2Fd%3D1%2Fct%3Dzgms%2Frs%3DAGLTcCPLubAJPE__-DfP0tDIR1-cduAt3Q%2Fm%3D__features__#parent=https%3A%2F%2Fapp.youstreamer.com&rpctoken=434205495

**Comment by matt-hensley** [comment]
Seeing the same issue. User reports began a few hours ago.

**Comment by matt-hensley** [comment]
Have reproduced the 404 for "proxy.html" in the API test tool in the YouTube documentation.

For example, exercising the API call to list channels returns a 404 in the Chrome network tab:
https://developers.google.com/youtube/v3/docs/channels/list

**Comment by matt-hensley** [comment]
@dvanderb is there a rough ETA of when the fix will be deployed?

**Comment by matt-hensley** [comment]
Calls started succeeding for us about 10 minutes ago (~16:10 UTC)

**Comment by abdulsadkasim877-hue** [comment]
hi ma'am Ivana alawi ❤️
