### ISSUE TITLE
Android Publisher: proxy.html 404-error

### ISSUE THREAD

**Issue by bauermedia-linusmoser** [google/google-api-javascript-client#683]
There seems to be a major issue concerning 404-errors across multiple APIs when using the Google API JavaScript Client. I am having the same issue using the Android Publisher/Google Play Developer API.

![image](https://user-images.githubusercontent.com/64128000/96233749-c933e880-0f98-11eb-8342-12d741e91a3f.png)

This does happen with our custom integration, as well as on the official "Try this API" section on the Google Developers page (tested with [reviews.list](https://developers.google.com/android-publisher/api-ref/rest/v3/reviews/list) method).

Is this being worked on as well? Currently, I was only able to find bug reports for the YouTube API, but there seems to be a bigger underlying issue.

**Comment by dvanderb** [comment]
We are looking into this issue.  To clarify the issue report the 404 is actually for https://content-androidpublisher.googleapis.com/static/proxy.html
