### ISSUE TITLE
Google Drive Picker not opening in Incognito mode in Chrome

### ISSUE THREAD

**Issue by metahumantobe** [google/google-api-javascript-client#686]
I'm using Javascript code as mentioned in https://developers.google.com/picker/docs#example for opening the Google Picker. It is working fine in normal window of browser (in this case Google Chrome) but while opening it in incognito mode it is failed to get opened. While debugging more on it to find solution, it came as the cookies are getting blocked in incognito mode as the cookies which are coming are not having attributes as `SameSite='None', 'Secure'`. So is it possible to set the cookies as `SameSite as None and Secure` ? Following are the list of cookies which are getting blocked:

**Name**  **Domain**
SID		.google.com/
HSID	.google.com/
SSID    	.google.com/
APISID	.google.com/
SAPISID	.google.com/
SIDCC	.google.com/

**Comment by znarkd** [comment]
The Picker example no longer works for IOS Chrome either.  It does work for other IOS browsers.  With Chrome, instead of opening the Picker screen, a request to Google Play occurs.

**Comment by dvanderb** [comment]
Please refer to Chromium [documentation](https://www.chromium.org/updates/same-site/test-debug) regarding Same-Site cookies and incognito mode.

**Comment by gabycperezdias** [comment]
@dvanderb Hi :) 
I am having the exact same issue
I was looking at the documentation as you mentioned... but the picker is out of my control, there are tips to test on my env, but my users will not be able to do any work around...

Did I misunderstood? Am I missing something?

Can you help me? Thanks :)
