### ISSUE TITLE
gapi.auth2.init({}).signIn() error handlers?

### ISSUE THREAD

**Issue by coolaj86** [google/google-api-javascript-client#691]
# Edit

What's the listener / handler for `"popup_closed_by_user"`?

# Original

**Update**: I had one of those awful silent errors preventing me from seeing the success condition.

How do I know if `auth2.signIn()` has completed? And if it's successful? Or unsuccessful?

I'm following along with the example at <https://developers.google.com/identity/sign-in/web/listeners>.

The most relevant code in question looks like this:

```js
          // User clicks "Login with Google"

          function (changedUser) {
            console.log('changedUser', changedUser);

            var googleUser = auth2.currentUser.get();
            var token = googleUser.getAuthResponse().id_token;

            console.log('token', token);
          }

          auth2.isSignedIn.listen(changeUser);
          auth2.currentUser.listen(changeUser);
          auth2.signIn();
```

The login dialog opens, the login completes, ~~but none of the listeners actually fire any events~~.

I also can't find any sort of API reference for `gapi` and `auth2`, etc. There's a bunch of "quick starts"... but where's the actual documentation? 

# Nearly-Complete Example

I've got an app which dynamically renders login buttons for various providers (meaning the HTML doesn't exist on page load).

I get an instance of `auth2` through an overly convoluted process that looks like this:

```js
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="google-signin-client_id" content="XXXXX" />
  </head>
    <script>

      window.googlePromise = new Promise(function (resolve) {
        window.googleResolver = function () {
          console.log('google ready?');
          resolve(gapi);
        };
      });

      window.auth2Promise = new Promise(function (resolve) {
        window.googlePromise.then(function () {

          window.gapi.load('auth2', function () {
            window.auth2 = window.gapi.auth2.init({
              client_id: "XXXXXXX",
              cookiepolicy: 'single_host_origin'
              scope: 'profile email'
            });
            resolve(window.auth2)
          });

        });
      });

    </script>
    <script src="https://apis.google.com/js/platform.js?onload=googleResolver" async defer></script>
</html>
```

And then elsewhere I use the `auth2` object like this:

```js
// prevent clicking sign in button before google is loaded
function onRenderLoginButtons() {
  window.auth2Promise.then(function () {
    $(".google-signin").removeAttr("disabled");
  });
}

// handle the click of the signin button
function onLoginProviderClick(provider) {
      if (provider === 'google') {
          function changeUser(changedUser) {
            console.log('changedUser', changedUser);
            var googleUser = auth2.currentUser.get();
            var token = googleUser.getAuthResponse().id_token;
            console.log('token', token);
          }
          auth2.isSignedIn.listen(changeUser);
          auth2.currentUser.listen(changeUser);
          auth2.signIn();
      }
}
```

However, none of the listener handlers ever fire.

# P.S.

There are conflicting directions on which of the libraries are supposed to be loaded:
- `<script src="https://apis.google.com/js/platform.js?onload=googleResolver" async defer></script>`
- `<script src="https://apis.google.com/js/api:client.js"></script>`
- `<script src="https://apis.google.com/js/api.js"></script>`

I've tried different versions of the JavaScript in hopes that maybe I just had the wrong one, but they all seem to have the same silent behavior.

**Comment by dvanderb** [comment]
signIn returns a promise so it will resolve on success and reject on failure as indicated in the documentation for the signIn function: https://developers.google.com/identity/sign-in/web/reference#googleauthsignin

**Comment by coolaj86** [comment]
Thanks, that's exactly the type of document I was trying to find. :D
