### ISSUE TITLE
broken link for "discovery documents"

### ISSUE THREAD

**Issue by coolaj86** [google/google-api-javascript-client#692]
The API docs in this repo (<https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md>), which are completely different from everything at <https://developers.google.com/identity/>, seem to suggest that all of those examples are deprecated and that instead the "discovery documents" should be used.

But the link to said "discovery documents" is broken: 

https://github.com/google/google-api-javascript-client/blob/master/api-client-library/javascript/features/discovery

**Comment by dvanderb** [comment]
Thanks for bringing the broken link to our attention.  There are multiple ways to initialize gapi.client.  Providing a discovery document URL for the target API is one of them(used in the identity example), but it is not the only way.  The documentation on reference.md just serves as a base reference for gapi/gapi.client functions which can be used in multiple ways.
