### ISSUE TITLE
Where's the API documentation?

### ISSUE THREAD

**Issue by coolaj86** [google/google-api-javascript-client#693]
I see a whole bunch of "Quick Starts" and "Examples", but I can't find any concrete documentation for... anything.

Is there a document somewhere that contains a concrete list of inputs and return values?

In the repo here there's a bunch of "meta" documentation, but no _actual_ documentation:

- https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md
- https://github.com/google/google-api-javascript-client/blob/master/docs/auth.md

On the website there's a bunch of quick starts:

- https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow
- https://developers.google.com/identity/sign-in/web/listeners
- https://developers.google.com/identity/sign-in/web/sign-in
- https://developers.google.com/identity/one-tap/web/guides/load-one-tap-client-library

But again, no _actual_ documentation for function signatures, return values, child properties, etc.

**Comment by dvanderb** [comment]
In your example(eg: auth) you are looking for their reference: https://developers.google.com/identity/sign-in/web/reference

For individual client APIs you have to look at the API explorer.  This library generates functions at runtime based on the client APIs: https://developers.google.com/apis-explorer

**Comment by coolaj86** [comment]
Thanks. This <https://developers.google.com/identity/sign-in/web/reference> is gold and I never noticed that there was a third layer of menu system through which to access it.

Note: it does not appear to be listed in the APIs Explorer you linked to. Perhaps it should be added there as well?

Thanks.
