### ISSUE TITLE
Third Party Cookies Unblocked for accounts.google.com, and still doesn't work

### ISSUE THREAD

**Issue by AnoNyMousUserz** [google/google-api-javascript-client#701]
I click on sign in with google on messages.textfree.us and it says One moment, please. Then it disappears without even redirecting me to the site I need to be, please help.

**Comment by AnoNyMousUserz** [comment]
@google-admin @googlebot

**Comment by ccdunder** [comment]
Feel free to reopen if this is still an issue.
