### ISSUE TITLE
responseType on Google Drive API v3 Files: get

### ISSUE THREAD

**Issue by brunoimbrizi** [google/google-api-javascript-client#704]
Originally submitted to IssueTracker https://issuetracker.google.com/issues/174302344 and recommended to file this in here "Since your feature request seems to be related to `gapi.client` library"

**A short description of the request:**
Define `responseType` on Google Drive API v3 Files: get, which relevant with alt=media.

**What is the purpose of this new feature?**
To be able to get the response body as `blob` or `arraybuffer`. At the moment it seems only possible to get the body as plain text.

**Scenario**
I am using the Google Drive API to create an application in the browser. I need to download the content of a file stored on Drive.

The v3 documentation for [gapi.client.drive.files.get](https://developers.google.com/drive/api/v3/reference/files/get) mentions `alt=media` which works and returns a response `body`. The issue is that `body` is plain text and it is not clear it if is possible to define a different `responseType` i.e. `blob` or `arraybuffer`.

The v2 documentation sheds some light on the topic with a JavaScript example to [download a file's content](https://developers.google.com/drive/api/v2/reference/files/get?authuser=1#javascript). Using a custom `XMLHttpRequest` it is possible to define a `responseType`.

Shouldn't it be possible to do the same with `gapi.client.drive.files.get`?

**Comment by h0x91b-wix** [comment]
Hey dude, I am succeded to do it in this way:

```
const res = await drive.files.get({
  fileId: ctx.params.fileId,
  alt: 'media',
}, {
  responseType: 'arraybuffer',
});
```

**Comment by afinetapestry** [comment]
Hey,

I get a 502 from the server when I try it. I can see that my browser is POSTing to the API with the request body `{"responseType":"arraybuffer"}` when I.

    var data = gapi.client.drive.files.get({
        'fileId': fileId,
        'alt': 'media'
    }, {
        'responseType': 'arraybuffer',
    });

**Comment by dvanderb** [comment]
Thanks for the feature request. Unfortunately the GAPI client does not support binary blobs well and the Drive [documentation](download a file's content) is the appropriate way to perform this task.

**Comment by ShilvantM** [comment]
Managed to read the body response in this manner (Angular) - 

`
getFileFromPicker(fileId: string, mimeType: string){
    return gapi.client.drive.files.get({
      "fileId": fileId,
      "mimeType": mimeType,
      "alt": "media",
    })
}
.
.
.
this.getPickedFile(fileId, mimeType).then(async (value: any) => {
     const blob = await this.base64toBlob(`data:${mimeType};base64,${btoa(value.body)}`);
     let file = new File([blob], fileName); //File of the pdf document
});

async base64toBlob(base64string: string) {
      const base64 = await fetch(base64string);
      return await base64.blob();
}
`
