### ISSUE TITLE
403 PERMISSION_DENIED accessing BigQuery discovery endpoint

### ISSUE THREAD

**Issue by twschiller** [google/google-api-javascript-client#708]
Update: oops, discovered I forgot to add BigQuery to the list of API restrictions for the key.

---

BigQuery discovery is returning 403 response when accessing the discovery endpoint.

I've tried multiple discovery URLs (both which I can access via my browser)

* https://bigquery.googleapis.com/discovery/v1/apis/bigquery/v2/rest
* https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest

II also get the error in both forms of the load method

* `gapi.client.load('bigquery', 'v2')`
* `gapi.client.load(' https://bigquery.googleapis.com/discovery/v1/apis/bigquery/v2/rest')`
* `gapi.client.init({discoveryDocs: [...], ...})`

I'm calling it from the background page of a Chrome Extension. The goal is to have the user access their BigQuery using OAuth2. 

Here's the response:

```
{
  "error": {
    "code": 403,
    "message": "Requests to this API bigquery method google.discovery.Discovery.GetDiscoveryRest are blocked.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_SERVICE_BLOCKED",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/<id>",
          "service": "bigquery.googleapis.com"
        }
      }
    ]
  }
}
```

The reason API_KEY_SERVICE_BLOCKED seems to suggest I'm missing a configuration option somewhere. However, the current setup is working with the Google Sheets API

**Comment by ccdunder** [comment]
> Update: oops, discovered I forgot to add BigQuery to the list of API restrictions for the key.

Sounds like this issue was resolved. Feel free to reopen if i misunderstood.
