### ISSUE TITLE
Getting issue while Opening Drive Picker that is: { "error": "IMMEDIATE_FAILED", "detail": "Request could not be auto-approved

### ISSUE THREAD

**Issue by ashraftalib** [google/google-api-javascript-client#730]
HI,

We are using Drive Picker in our app since many years and It was working fine for all users. Now a days It is working fine for some users and  not working fine for some users. When they are clicking a button(onclick="onApiLoad();") to open a Drive Picker in our app. But Drive Picker does not appear and they are getting the error as below:
{
  "error": "IMMEDIATE_FAILED",
  "detail": "Request could not be auto-approved."
}
I have taken this error response from developer console of Chrome. But in some case users are able to view Drive Picker and access_token also as below:
{
  "token_type": "Bearer",
  "access_token": "ya29.a0AfH6SM..............................................",
  "scope": "email https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/userinfo.email openid",
  "login_hint": "AJDLj6IhozD2z4fIdXJd0w2f8iqU8EQ4-AcwELtcfV3AKE9tKKSPQN1gPcK1IwMhyXUq8mn7usZRwsba9tFJTXXGkt_VeLjkbwik9WiFZvQz_KbKVhQFhPg",
  "expires_in": 3599,
  "session_state": {
    "extraQueryParams": {
      "authuser": "0"
    }
  }
}
Please help us why is this happening with some users ?

Our sample code is as below:

      //The API developer key obtained from the Google Cloud Console.
    	var developerKey = '{developerkey value}';
    	
    // The Client ID obtained from the Google Cloud Console.
    	var clientId = '{clientId value}';

        // Scope to use to access user's Drive.
        var scope = ['https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/userinfo.email'];

        var pickerApiLoaded = false;
        var oauthToken;

         // Use the API Loader script to load google.picker and gapi.auth.

	      function onApiLoad() {
	    	   gapi.load('auth', {'callback': onAuthApiLoad});
	           gapi.load('picker', {'callback': onPickerApiLoad});
	      }
	      
          function onAuthApiLoad() {
            window.gapi.auth.authorize(
                {
                  'client_id': clientId,
                  'scope': scope,
                  'immediate': false
                },
                handleAuthResult);
          }

          function onPickerApiLoad() {
                 pickerApiLoaded = true;
                 createPicker();
          }

          function handleAuthResult(authResult) {
            if (authResult && !authResult.error) {
                oauthToken = authResult.access_token;
                createPicker();
            }
          }
        
      // Create and render a Picker object.
      function createPicker() {
       
        var DocsView  = new google.picker.DocsView (google.picker.ViewId.DOCS)
						.setOwnedByMe(true);
        var picker = new google.picker.PickerBuilder()
            .enableFeature(google.picker.Feature.MULTISELECT_ENABLED)
            .enableFeature(google.picker.Feature.SUPPORT_DRIVES)
            .addView(DocsView)
            .addView(new google.picker.DocsUploadView())
            .setDeveloperKey(developerKey)
            .setOAuthToken(oauthToken)
            .setCallback(pickerCallback)
            .build();
         picker.setVisible(true);
      }

**Comment by sidharthp** [comment]
Hey ashraftalib@, we fixed the bug that was causing this issue late last week. Could you check whether you are still observing the issue? For the sake of completeness, also test the flow in Incognito to rule out the possibility of having stale cookies.

**Comment by ashraftalib** [comment]
@sidharthp I changed the scope from 'https://www.googleapis.com/auth/drive' to' https://www.googleapis.com/auth/drive.file' as per Picker API docs says to use scope: 'https://www.googleapis.com/auth/drive.file'. Now It is working fine for affected users. 
But before it was working file in all users with scope:  'https://www.googleapis.com/auth/drive' . Can you tell me Is there any updates in Picker API or the issue has been been resolved ?
Thanks.

**Comment by sidharthp** [comment]
@ashraftalib , the issue has been resolved now so I think it should work fine even if you use '.../auth/drive' scope. But if the Picker API doc suggests using the '.../auth/drive.file' scope, it might be better to use that instead.

**Comment by ashraftalib** [comment]
@sidharthp 

Still we the same issue while using scope as : https://www.googleapis.com/auth/drive.readonly
in case opening drive picker. Can you check with the /drive.readonly  It was working since many days now It is not working.
