### ISSUE TITLE
Error 400: invalid_request Permission denied to generate login hint for target domain.

### ISSUE THREAD

**Issue by ly-william** [google/google-api-javascript-client#733]
I was able to successfully integrate Google Sign-in via Javascript on my website site but after checking on it recently it suddenly broke. Under Authorized JavaScript origins, I have a link to the site but I'm still getting the error listed in the title. I've looked at other posts surrounding this issue on StackOverflow but the cause in those cases seemed to be linking an IP to their website rather than putting the domain name. Again, I do have the domain name listed yet it is still not working. Any advice/direction would be greatly appreciated.

**Comment by DanielRedgate** [comment]
Having exactly the same issue

**Comment by wasyyyy** [comment]
Hi @ly-william, @DanielRedgate, would you be able to provide the website URL with this issue? And which browser you were using?

**Comment by ly-william** [comment]
@wasyyyy Sure, here's the [url](https://lywilliam.pythonanywhere.com). I've been testing it on Google Chrome and Brave, and it is still coming up with the same error.

**Comment by DanielRedgate** [comment]
> Hi @ly-william, @DanielRedgate, would you be able to provide the website URL with this issue? And which browser you were using?

I was using chrome and safari and i get exactly the same result as above. Identical code works on localhost with no issues, so guessing the issue is with some change to the pythonanywhere domain settings? 

In the case of localhost, I just set the /etc/hosts setting for the local IP address to resolve my address to mydevserver.com and added http://mydevserver.com:8080 to the authorised javascript origins on google cloud console.

for pythonanywhere, i both added http://pythonanywhere.com and my custom domain, to no avail :(

**Comment by ly-william** [comment]
@DanielRedgate I just checked again today and it seems to be working now

**Comment by Trojan-engaging88** [comment]
> > Hi [@ly-william](https://github.com/ly-william), [@DanielRedgate](https://github.com/DanielRedgate), would you be able to provide the website URL with this issue? And which browser you were using?
> 
> I was using chrome and safari and i get exactly the same result as above. Identical code works on localhost with no issues, so guessing the issue is with some change to the pythonanywhere domain settings?
> 
> In the case of localhost, I just set the /etc/hosts setting for the local IP address to resolve my address to mydevserver.com and added http://mydevserver.com:8080 to the authorised javascript origins on google cloud console.
> 
> for pythonanywhere, i both added http://pythonanywhere.com and my custom domain, to no avail :(
> 
> [@ly-william](https://github.com/ly-william) - i added a slightly more indepth question on stackoverflow. appreciate if you can vote up and try to garner some support! https://stackoverflow.com/q/67439724/8252612





https://yahir-embodiment.github.io/theft576/
