### ISSUE TITLE
Deleting a file using JS client fails

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#77]
_From [boris.jo...@gmail.com](https://code.google.com/u/104097404183448846368/) on March 21, 2013 09:22:37_

I've described the problem on StackOverflow and will keep updating the thread with new info. http://stackoverflow.com/questions/15532468/deleting-a-google-drive-file-using-js-client

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=77_

**Comment by grant** [comment]
This an issue with the Drive API v2, not the gapi client.
