### ISSUE TITLE
Nothing happens when clicking "Sign in with Google"

### ISSUE THREAD

**Issue by ClandestineClout** [google/google-api-javascript-client#798]
edit: somehow fixed this... not sure how it worked, but instead of trying to disable one extension at a time and testing individually, I disabled all extensions (at which point it worked) and then re-enabled the extensions one by one while repeatedly testing and was actually able to re-enable all the extensions without the problem coming back. Strange. But I'll leave this here for now. 

old post:
 Often when I come across a login page the 'Sign in with Google' option doesn't work. I click and nothing seems to happen (well, the nav bar flashes for a split second as if it's going to load something but goes back to normal immediately). I've tried resetting all flags, disabling all extensions, restarting the browser and restarting the computer, multiple times. I've tried clearing cache and cookies, I've made sure to allow all third party cookies and added an entry for accounts.google.com specifically just in case. None of the above solutions work, however switching to a fresh profile solves the problem. I'd rather find out what's going wrong that migrate everything to a new profile. Any ideas? Thanks

**Comment by tbakerx** [comment]
Do you have 3rd party cookies disabled by chance? I believe it's enabled by default in incognito and is pretty widely used otherwise. 
https://developers.google.com/identity/sign-in/web/troubleshooting#third-party_cookies_and_data_blocked

We recently ran into this issue for some of our users and wound up just migrating to the new Identity Services login.

**Comment by tbakerx** [comment]
Sure, apologies I didn't read the old post section thoroughly enough. Out of curiosity, if you believe this issue to be due to some combination of extensions on your own side rather than a problem with this library, why not close the ticket?

**Comment by ClandestineClout** [comment]
I didn't know that was possible. I'm new to GitHub. Thanks.
