### ISSUE TITLE
mybusiness Discovery Document Returns a 404 Response

### ISSUE THREAD

**Issue by washamdev** [google/google-api-javascript-client#802]
I have been trying to load the Discovery Document for the "mybusiness" or "mybusinessaccountmanagement" API, but have been unsuccessful.

First off, we are including the API JS file on our site like this:

    <script async defer src="https://apis.google.com/js/api.js" onload="this.onload=function(){};handleClientLoad();" onreadystatechange="if(this.readyState==='complete'){this.onload();}"></script>
    <script>
        function handleClientLoad() {
            gapi.load('client:auth2', initClient);
        }
        function initClient() {
            gapi.client.init({
                'clientId': '[MY-CLIENT-ID].apps.googleusercontent.com',
                'discoveryDocs': ['https://mybusinessaccountmanagement.googleapis.com/$discovery/rest?version=v1'],
                'scope': 'https://www.googleapis.com/auth/business.manage'
            })
            .then(function () {
                console.log('gapi.client.init complete.');
            });
        }
    </script>

In the [My Business Account Management documentation](https://developers.google.com/my-business/reference/accountmanagement/rest), it lists the Discovery Document URL explicitly as:

https://mybusinessaccountmanagement.googleapis.com/$discovery/rest?version=v1

I get a 404 response in the DevTools console when I try to `init` using that Discovery Document URL, and the request in the Network tab shows that the URL it was trying to load is:

https://developers.google.com/static/proxy.html?usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.lb.en.NnK9YPjtg-w.O%2Fd%3D1%2Frs%3DAHpOoo9KePDGVlGjp-rlXwDM1kUO2Eh4gg%2Fm%3D__features__

I read elsewhere that you can try to load an actual JSON file that's supposed to load the Discovery Document more directly from a URL like https://developers.google.com/my-business/samples/mybusiness_google_rest_v4p9.json, but when I use that as the `discoveryDocs` URL in the `init`, I see the exact same 404 response.

I also saw someone mention trying to use a URL like https://www.googleapis.com/discovery/v1/apis/mybusiness/v1/rest, I get a different 404 response in the console:

https://content.googleapis.com/discovery/v1/apis/mybusiness/v1/rest?pp=0&fields=kind%2Cname%2Cversion%2CrootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods%2CbatchPath%2Cid

The error says `"Requested entity was not found."`.

Is there a problem with the JS API file, or is there something wrong with the way we are trying to load and use the mybusiness API?

(it appears our issue may be similar to the issue reported at https://github.com/google/google-api-javascript-client/issues/801)

**Comment by dvanderb** [comment]
Yeah this is the same as issue #801 and you should stick with the https://mybusinessaccountmanagement.googleapis.com/$discovery/rest?version=v1 discovery document. The issue will go away on it's own once #801 is resolved.

**Comment by ccdunder** [comment]
#801 is resolved. https://content-mybusinessaccountmanagement.googleapis.com/static/proxy.html returns 200.
