### ISSUE TITLE
mybusinessaccountmanagement not loading properly

### ISSUE THREAD

**Issue by dvanderb** [google/google-api-javascript-client#807]
I've got API code running on GMB API v4.9 right now that needs to transition to the Account Management API v1 before the sunset date (2022-04-30). I'm getting this same error trying to use the new API.

Do we know if this fix will be rolled out in time, AND/OR will the sunset date be delayed, since the new API isn't working?

Thanks

_Originally posted by @khussain-cars in https://github.com/google/google-api-javascript-client/issues/801#issuecomment-1098300808_

**Comment by dvanderb** [comment]
Breaking this out into a new issue since it is for a different API than the one in issue #801

**Comment by khussain-cars** [comment]
Sorry about that. Thanks for moving it over.

For additional context, I started here #802 

And was redirected over to the #801 ticket

**Comment by ccdunder** [comment]
The issue with mybusinessaccountmanagement API is resolved; https://content-mybusinessaccountmanagement.googleapis.com/static/proxy.html returns 200.
