### ISSUE TITLE
error: "popup_closed_by_user"  gapi credentials popup 

### ISSUE THREAD

**Issue by hakermi** [google/google-api-javascript-client#811]
On chrome Version 101.0.4951.54 (Official Build) (64-bit)

We no longer able to use gapi to connect google calendars to our platform 
the google credentials popup appears and then after validate the user mail, it closes and show this error on browser console :
error: "popup_closed_by_user"  instead to login the user account.

`this.gapi.auth2.getAuthInstance().signIn({
      scope: 'https://www.googleapis.com/auth/calendar.events',
    })
      .then(currentUser => {
        // do something
      }`

BTW, tried to clear the cache and even allow third-party cookies but the issue still persist

used code to initialize the api.
DISCOVERY_DOCS: ['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest']
SCOPE_WRITE: 'https://www.googleapis.com/auth/calendar.events',

` window.require(['https://apis.google.com/js/api.js'], () => {
    connector.gapi = gapi;
    connector.gapi.load('client:auth2', function() {
      gapi.client.init({
        clientId: //client_id,
        discoveryDocs: connector.DISCOVERY_DOCS,
        scope: connector.SCOPE_WRITE,
      }).then(function () {
     //code
}`

**Comment by udbmnm** [comment]
https://developers.google.com/identity/gsi/web/guides/features#exponential_cooldown
https://developers.google.com/identity/sign-in/web/troubleshooting
