### ISSUE TITLE
How to recognize start of authentication flow in new Google Identity Services library?

### ISSUE THREAD

**Issue by niksauer** [google/google-api-javascript-client#819]
While migrating to the new Google Identity Services client library, I noticed that there is no way to get notified when the authentication flow actually starts, i.e. when the user has clicked the _Sign in with Google_ button. Such a callback, however, is needed to instruct other (React) components to reset their state, especially when performing multiple login attempts upon failure and mixing this with a password-based sign in or other social providers.

Previously, this was possible by overloading the button's `onClick` handler. This approach does not work anymore since the button will be injected as an `iframe`. 

How can I now recognize when a user has clicked _Sign in with Google_? 

See JavaScript API reference: https://developers.google.com/identity/gsi/web/reference/js-reference

**Comment by henrybanzon** [comment]
I encountered same issue here. Hope that your question will get an answer.

**Comment by henryb0119** [comment]
I think I got an idea. You have to invoke first the initTokenClient and requestAccessToken. In the callback function you have to check if all or any of the scopes were granted using google.accounts.oauth2.hasGrantedAllScopes or google.accounts.oauth2.hasGrantedAnyScope. If not yet granted then that's the time you have to invoke initCodeClient and requestCode.

**Comment by henryb0119** [comment]
I tried what I thought but it didn't work. Authorization is not needed. When you invoke authentication but you are not authorized yet, it will then automatically show you the scopes that you're going to grant. 
In summary, authentication is enough to run an application via google API.

**Comment by niksauer** [comment]
Yes, we explicitly do not want to have to ask the user to grant additional autorization scopes as that gives the impression of us requiring more data than necessary. This should be possible with the standard authentication flow. 

I have asked the same question on the React integration library and they suggested to wrap the button in a `<div>` and use its `onClick` but that seems unreliable at best.

**Comment by rousso1** [comment]
Upvoting. 
A "login process started" callback or some way to report it would be nice

**Comment by imoby** [comment]
We are also very dependent on having a callback to know when the user has initiated the sign in process. I feel that as more people begin to migrate from the old api's to this this will become a blocker for them too.

**Comment by imoby** [comment]
We were able to 'somewhat' get around this by listening to the blur event in the window and filtering out any that were iframe or had gsi_ as the id in the element. I wish this issue could get more attention but for now the below could hopefully help others who might have ran into this issue. The below snippet is used in a react project but can be retrofitted in others means.

```
  useEffect(() => {
      const listener = window.addEventListener('blur', () => {
        if (
          (document.activeElement === document.querySelector('iframe') &&
            document.activeElement?.getAttribute('src')?.includes('google')) ||
          document.activeElement?.getAttribute('id')?.includes('gsi_')
        ) {
          // Run whatever logic you want here
        }
      });
      return window.removeEventListener('blur', listener);
  }, []);
```

**Comment by ShreyasAiyar** [comment]
+1. This is a use case for us too. We would like to know when the user started the authentication flow not just the final result.

**Comment by ade-git** [comment]
You can now use the `[click_listener](https://developers.google.com/identity/gsi/web/reference/js-reference#click_listener)` property to specify a function to be called when the Sign in with Google button is clicked.

**Comment by niksauer** [comment]
Awesome, that's exactly what we needed!
