### ISSUE TITLE
CORS issue only when revoking Token by calling (Google Identity Services) GIS's google.accounts.oauth2.revoke

### ISSUE THREAD

**Issue by datvm** [google/google-api-javascript-client#821]
**Summary**

I have [this question on StackOverflow](https://stackoverflow.com/questions/71532935/cors-issue-only-when-revoking-token-by-calling-google-identity-services-giss) and apparently many (at least 6) are encountering the issue as well but there is no response.

I am trying to invoke GSI Javascript [`google.accounts.oauth2.revoke`](https://developers.google.com/identity/oauth2/web/reference/js-reference#google.accounts.oauth2.revoke) method. Under the hood it sends a request to https://oauth2.googleapis.com/revoke. However there is CORS issue:

```js
await new Promise(r => google.accounts.oauth2.revoke(token, r));
```

> Access to XMLHttpRequest at 'https://oauth2.googleapis.com/revoke' from origin 'https://localhost:44397' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

These are CORS-related response headers:

```text
- access-control-allow-origin: https://localhost:44397

- access-control-expose-headers: date,vary,vary,vary,content-encoding,server,content-length
```

All other functions (logging in, refresh token etc.) works well without issue like this. I think this is an API server issue but I don't know where to report it so I am making this issue. Please tell me where I should post it if it is not the correct place.

**Browser(s)/Version(s)**

Microsoft Edge
Version 102.0.1245.44 (Official build) (64-bit)

**Expected Behavior**

Token should be revoked with no error.

**Actual Behavior**

Response fails due to CORS error

**Steps to Reproduce**

See the Summary section.

**Comment by JonHolman** [comment]
I am experiencing this as well with the example from https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#gapi-asyncawait

**Comment by csihar** [comment]
I'm also experiencing this when testing the example code Jon linked to on localhost.

**Comment by shivam4tek** [comment]
I am facing the same issue

**Comment by brdaugherty** [comment]
Thanks for reporting, and your patience. You should now be able to successfully call `revoke()`.

**Comment by datvm** [comment]
Can anyone confirm please? Sorry I am not with any project that uses GSI now so I can't confirm

**Comment by JonHolman** [comment]
I'm no longer working on that project, but I just tried again, copied the example from https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#gapi-asyncawait replaced `YOUR_CLIENT_ID` with my CLIENT ID.  My CLIENT ID has http://localhost:3000 as an authorized origin and an authorized redirect.  I tested and I still get:
Access to XMLHttpRequest at 'https://oauth2.googleapis.com/revoke' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by Evan0307** [comment]
> I'm no longer working on that project, but I just tried again, copied the example from https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#gapi-asyncawait replaced `YOUR_CLIENT_ID` with my CLIENT ID. My CLIENT ID has http://localhost:3000 as an authorized origin and an authorized redirect. I tested and I still get: Access to XMLHttpRequest at 'https://oauth2.googleapis.com/revoke' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
@brdaugherty  
I face the same error .

**Comment by rsuresh27** [comment]
I am following the Google Picker API example from Google which is found [here](https://developers.google.com/drive/picker/guides/sample) and can confirm I am getting the same error: 
`Access to XMLHttpRequest at 'https://oauth2.googleapis.com/revoke' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by overseacloud** [comment]
The library has been updated. I have verified in my environment and the revoke API works with no error.
