### ISSUE TITLE
Callback of `google.accounts.oauth2.initCodeClient` is not called when browser Google sign-in popup window is closed

### ISSUE THREAD

**Issue by specnazzz** [google/google-api-javascript-client#829]
**Summary**
When requesting authorization code with `gapi.auth2.authorize`, the `callback` function was also called, when the user closed the Google sign-in popup window by clicking on popup window "X" icon. The `response.error` was then set to `popup_closed_by_user`. This could be used to show for example some loading overlay before calling `gapi.auth2.authorize` and removing the overlay after the Google sign-in popup windows was closed. But the new "Google Identity Services" `google.accounts.oauth2.initCodeClient` callback is not called when the Google sign-in popup window is closed in this way.

**Expected Behavior**
Expected behavior would be to call `google.accounts.oauth2.initCodeClient` callback also when the user is closing Google sign-in popup window by clicking on "X" icon. This could return the same error `popup_closed_by_user` as for `gapi.oauth2.authorize`.

**Actual Behavior**
Google sign-in popup window is closed, but the `google.accounts.oauth2.initCodeClient` callback is not called.

**Steps to Reproduce**
```
const client = google.accounts.oauth2.initCodeClient({
  client_id: <client_id>,
  scope: <scopes>,
  ux_mode: 'popup',
  select_account: true,
  callback: (response) => {
    // not called when Google sign-in popup window closed with "X" icon
    console.log('response', response);
  });
client.requestCode();
```

**Comment by kongguibin** [comment]
https://developers.google.com/identity/oauth2/web/guides/error#non-oauth_errors

**Comment by specnazzz** [comment]
@kongguibin Thanks for adding.
