### ISSUE TITLE
Google Identity Services and calls to Calendar API

### ISSUE THREAD

**Issue by adammartiska** [google/google-api-javascript-client#845]
Hello, we have really simple app, where I am using new **Google Identity Services** for authenticating users. In our app they can create event, and it should be possible to add this event into their Google Calendar. What am I missing or isn't really clear for me how can I call Google Calendar API endpoints with information returned from Google Identity Services - in response I get JWT token, which after decoding looks like this : 
![image](https://user-images.githubusercontent.com/55830313/208320803-0a36b431-cf36-45ab-91a1-d7f6c8a953ec.png)

I tried to use this JWT token as **Authorization header** when calling Google Calendar API endpoint for getting events **https://www.googleapis.com/calendar/v3/calendars/thefaston@gmail.com/events** but without success. Should use of this library somehow help me to call this Google API? Sorry if anything mentioned isn't fully making sense, but I really lack of some Google Documentation of this. 

Any help is really appreciated, thank you :)

**Comment by coopercodes** [comment]
Bumping this, I am working with the Calendars API currently and it seems like all of the code they have currently all uses gapi (which is outdated). Commenting here so if I find a solution I'll let you know.

**Comment by dvanderb** [comment]
gapi.client is not deprecated, just gapi.auth2. Calendar API docs are updated with how to use the two libraries together to make API calls: https://developers.google.com/calendar/api/quickstart/js
