### ISSUE TITLE
Will Google API Client Library for JavaScript (gapi.client) be unavailable after March 31, 2023?

### ISSUE THREAD

**Issue by tasuku-sasaki** [google/google-api-javascript-client#846]
I am developing a web application on Google App Engine. This application uses [Google API Client Library for JavaScript](https://github.com/google/google-api-javascript-client) to call Google APIs with access tokens.

We recently received the following notice: https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html

> Complete your migration prior to March 31, 2023, after which the Platform Library will no longer be available for download and web apps relying upon deprecated authorization features to obtain access tokens for calling Google APIs will no longer work as intended.

> Web applications using gapi.client from the Google API Client Library implicitly load and use the Platform Library’s soon to be deprecated gapi.auth2 module when working with access tokens to call Google APIs. Updates to your web app to explicitly include the new Identity Services library, manage access token requests, and replace auth2 module references with newer equivalent methods are necessary.

In accordance with this notice, I have replaced gapi.auth2 module with [Google Identity Services JavaScript library](https://developers.google.com/identity/oauth2/web/guides/overview). But I plan to continue to use gapi.client module to call Google APIs.

Will Google API Client Library for JavaScript (gapi.client) be unavailable after March 31, 2023?

**Comment by dvanderb** [comment]
Hi thanks for reaching out to clarify this(and we'll clarify it in our docs when they are updated). The only thing being deprecated is gapi.auth2. The part of the library you are using(gapi.client) will continue to be available and work as expected so you will be good to go.
